### ISSUE TITLE
Cannot switch context and access a native element on a js alert in Selendroid

### ISSUE THREAD

**Issue by hardik-d** [selendroid/selendroid#1008]
here is the logcat:

java.lang.ClassCastException: io.selendroid.server.model.AndroidNativeElement$WebViewSourceClient cannot be cast to org.apache.cordova.CordovaChromeClient
at org.apache.cordova.CordovaWebView.setWebChromeClient(CordovaWebView.java:332)
at io.selendroid.server.model.AndroidNativeElement$4.run(AndroidNativeElement.java:383)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

i get below appium selendroid error:

info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_7002 mapped to pid 7002
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps"
info: [debug] Parsed pid: 7002 pkg: com.paynearme.consumer.dev
info: [debug] from: u0_a58,7002,945,966124,232304,ffffffff,b76bb0b5,S,com.paynearme.consumer.dev
info: [debug] returning process name: com.paynearme.consumer.dev
info: [debug] Available contexts: WEBVIEW_0,NATIVE_APP
info: [debug] ["WEBVIEW_com.paynearme.consumer.dev"]
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/window_handles","method":"GET"}
info: [debug] Available contexts: ["WEBVIEW_0","NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: <-- POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context 200 92.415 ms - 76 {"status":0,"value":null,"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: --> POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_7002 mapped to pid 7002
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps"
info: [debug] Parsed pid: 7002 pkg: com.paynearme.consumer.dev
info: [debug] from: u0_a58,7002,945,966124,232372,ffffffff,b76bb0b5,S,com.paynearme.consumer.dev
info: [debug] returning process name: com.paynearme.consumer.dev
info: [debug] Available contexts: WEBVIEW_0,NATIVE_APP
info: [debug] ["WEBVIEW_com.paynearme.consumer.dev"]
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/window_handles","method":"GET"}
info: [debug] Available contexts: ["WEBVIEW_0","NATIVE_APP"]
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context","method":"POST","json":{"name":"NATIVE_APP"}}
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: <-- POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context 200 103.534 ms - 76 {"status":0,"value":null,"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: --> GET /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: <-- GET /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context 200 0.624 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: --> POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_7002 mapped to pid 7002
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps"
info: [debug] Parsed pid: 7002 pkg: com.paynearme.consumer.dev
info: [debug] from: u0_a58,7002,945,966124,232668,ffffffff,b7658d52,S,com.paynearme.consumer.dev
info: [debug] returning process name: com.paynearme.consumer.dev
info: [debug] Available contexts: WEBVIEW_0,NATIVE_APP
info: [debug] ["WEBVIEW_com.paynearme.consumer.dev"]
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/window_handles","method":"GET"}
info: [debug] Available contexts: ["WEBVIEW_0","NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: <-- POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/context 200 98.641 ms - 76 {"status":0,"value":null,"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: --> POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/element {"using":"xpath","value":"//*[@name=\"Unknown zip code\"]"}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/element","method":"POST","json":{"using":"xpath","value":"//*[@name=\"Unknown zip code\"]"}}
info: [debug] [SELENDROID] -1
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"76b74361-b307-b7e9-67fa-9da66b281a96"}
info: <-- POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/element 500 83.468 ms - 210 
info: --> POST /wd/hub/session/76b74361-b307-b7e9-67fa-9da66b281a96/element {"using":"xpath","value":"//*[@name=\"Unknown zip code\"]"}

Steps:

set webview context and perform actions
switch to native app view and try to find element in the pop up. this is where it fails.
Info:

appium --automation-name Selendroid
info: Welcome to Appium v1.4.16 (REV d11c15a516f16d20c77ccc8e1d501957fb65d9eb)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"automationName":"Selendroid"}
info: Console LogLevel: debug

Emulator: Nexus_5_API_21_x86 API Level 21

**Comment by lukeis** [comment]
can you check your logcat for more errors? The error in the logcat provided should only occur when trying to get the 'page source' or get the element source.

**Comment by hardik-d** [comment]
that is all i get in appcrash.log. If you want i can give you full logcat or anything in particular i should be looking at?

**Comment by hardik-d** [comment]
here is the cleaned up end part of logcat:

7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#executeAtom:199 - jsResult: {"status":0,"value":{"ELEMENT":":wdc:1448476879491"}}
11-25 10:41:31.875 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 776 tx_bytes 3625
11-25 10:41:31.888 7002-7085/com.paynearme.consumer.dev E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
11-25 10:41:31.900 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:1539 - checking currentAlertMessage: 0
11-25 10:41:31.900 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.handler.ClickElement#safeHandle:33 - Click element command
11-25 10:41:31.905 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:167 - convertToJsArgs: {"ELEMENT":":wdc:1448476879491"}
1-25 10:41:31.959 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:167 - convertToJsArgs: {"ELEMENT":":wdc:1448476879491"}
11-25 10:41:31.959 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:109 - convertToJsArgs: {"ELEMENT":":wdc:1448476879491"}
11-25 10:41:31.975 7002-7085/com.paynearme.consumer.dev E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
11-25 10:41:31.993 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#executeAtom:199 - jsResult: {"status":0,"value":true}
11-25 10:41:31.993 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:167 - convertToJsArgs: {"ELEMENT":":wdc:1448476879491"}
11-25 10:41:31.993 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:109 - convertToJsArgs: {"ELEMENT":":wdc:1448476879491"}
11-25 10:41:31.996 7002-7085/com.paynearme.consumer.dev E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000bd0
11-25 10:41:32.038 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#executeAtom:199 - jsResult: {"status":0,"value":{"x":24,"y":283,"clone":"function (){return new Ka(this.x,this.y)}","toString":"function (){return\"(\"+this.x+\", \"+this.y+\")\"}","ceil":"function (){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this}","floor":"function (){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this}","round":"function (){this.x=Math.round(this.x);this.y=Math.round(this.y);return this}","scale":"function (a,b){var c=ca(b)?b:a;this.x*=a;this.y*=c;return this}"}}
11-25 10:41:32.038 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:167 - convertToJsArgs: {"ELEMENT":":wdc:1448476879491"}
11-25 10:41:32.606 7002-7002/com.paynearme.consumer.dev D/CordovaLog: file:///android_asset/www/deps.js: Line 12299 : Intercepting http request: url = http://192.168.1.74:3000/api/v2/registered_users/create.json
11-25 10:41:32.606 7002-7002/com.paynearme.consumer.dev I/chromium: [INFO:CONSOLE(12299)] "Intercepting http request: url = http://192.168.1.74:3000/api/v2/registered_users/create.json", source: file:///android_asset/www/deps.js (12299)
11-25 10:41:32.797 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 778 tx_bytes 3729
11-25 10:41:32.882 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:1539 - checking currentAlertMessage: 0
11-25 10:41:32.882 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.handler.GetContexts#safeHandle:34 - get contexts/windowHandles command
11-25 10:41:32.883 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 778 tx_bytes 3803
11-25 10:41:32.977 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:1539 - checking currentAlertMessage: 0
11-25 10:41:32.977 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.handler.GetContexts#safeHandle:34 - get contexts/windowHandles command
11-25 10:41:32.977 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 778 tx_bytes 3901
11-25 10:41:32.996 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:1539 - checking currentAlertMessage: 0
11-25 10:41:32.997 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.handler.SwitchContext#safeHandle:32 - Switch Context/Window command
11-25 10:41:32.997 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 799 tx_bytes 3999
11-25 10:41:33.096 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.handler.GetContexts#safeHandle:34 - get contexts/windowHandles command
11-25 10:41:33.099 7002-7087/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 799 tx_bytes 4073
11-25 10:41:33.108 7002-7090/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.handler.FindElement#safeHandle:38 - find element command using 'xpath' with selector '//*[@name="Unknown zip code"]'.
11-25 10:41:33.152 7002-7002/com.paynearme.consumer.dev D/AndroidRuntime: Shutting down VM
11-25 10:41:33.156 7002-7002/com.paynearme.consumer.dev I/SELENDROID: io.selendroid.server.UncaughtExceptionHandling$ExceptionDumper#uncaughtException:52 - Process has crashed, log has been written to: /storage/sdcard/appcrash.log
11-25 10:41:33.162 7002-7002/com.paynearme.consumer.dev I/art: System.exit called, status: -1
11-25 10:41:33.162 7002-7002/com.paynearme.consumer.dev I/AndroidRuntime: VM exiting with result code -1, cleanup skipped.

**Comment by hardik-d** [comment]
if it helps here is an older reference to similar problem it seems:

https://github.com/selendroid/selendroid/issues/658

**Comment by hardik-d** [comment]
code that fails is like:

    set_context "NATIVE_APP"
    within_context('NATIVE_APP') do
      wait(10){@driver.find_element(:xpath, '//*[@name = "CONTINUE ."]')}
      @driver.find_element(:xpath, '//*[@name = "CONTINUE ."]').click
    end

**Comment by hardik-d** [comment]
@lukeis any progress? what are the next steps?

**Comment by hardik-d** [comment]
@DominikDary can you help out here as i see you contributed to previous issue https://github.com/selendroid/selendroid/issues/658
