### ISSUE TITLE
io.selendroid.standalone.server.model.serlendroidstandaloneDriver stopSession

### ISSUE THREAD

**Issue by angelliu** [selendroid/selendroid#1021]
deletegzcity = self.driver.find_element_by_id('manage_imageView_indicator') 
        deletegzcity.click()

 Selendroid can find the element correct, but when to run the click(), the selendroid will hang up.
I do not know how to solve it, please help to resolve it.

File "C:/Python27/DemoTest/OnlineWeather.py", line 89, in test_weather_delete_city
    deletegzcity.click()
  File "C:\Python27\lib\site-packages\selenium-2.44.0-py2.7.egg\selenium\webdriver\remote\webelement.py", line 65, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium-2.44.0-py2.7.egg\selenium\webdriver\remote\webelement.py", line 385, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium-2.44.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.44.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: CATCH_ALL: java.lang.NullPointerException
	at io.selendroid.server.model.AndroidNativeElement.isDisplayed(AndroidNativeElement.java:110)
	at io.selendroid.server.model.AndroidNativeElement$1.apply(AndroidNativeElement.java:184)
	at io.selendroid.server.model.AndroidNativeElement$1.apply(AndroidNativeElement.java:181)
	at io.selendroid.server.android.AndroidWait.until(AndroidWait.java:65)
	at io.selendroid.server.model.AndroidNativeElement.waitUntilIsDisplayed(AndroidNativeElement.java:181)
	at io.selendroid.server.model.AndroidNativeElement.click(AndroidNativeElement.java:256)
	at io.selendroid.server.handler.ClickElement.safeHandle(ClickElement.java:36)
	at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:86)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)
	at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:856)

**Comment by holybible934** [comment]
From your log I doubt if [manage_imageView_indicator] element really exists on the screen of your device.
Beware that "find element" will NEVER return you a null object, instead, it will return you the object with specified id/path/class/etc, but get Null Exception when you click() / getText() on it.

You have to handle this situation in your code.

**Comment by angelliu** [comment]
thanks holybible934 !

![imageview](https://cloud.githubusercontent.com/assets/16433358/12047306/591c47e4-af04-11e5-8095-77d99a0a3ad6.jpg)
I really can find the element .
Could you give me some way to resolve it?

**Comment by holybible934** [comment]
Here are some suggestions from me:  
1. Throw hierarchyviewer away.
2. Connect your Android Device and use "uiautomatorviewer" inside <Android SDK>\tools\  
3. You can find it as well in Android Device Monitor as attached picture.  
![uiautomationviewer](https://cloud.githubusercontent.com/assets/6605558/12060279/8297fd7e-afaf-11e5-994a-239cfe83c105.jpg)  
4. Run your application till the page your want to manipulate, then "dump" the view hierarchy of that page.  

Remember 2 things:  
You can see it DOES NOT mean you can manipulate it.
When you manipulate an element (getText(), click(), etc) and get NULL exception, it means you DID NOT find the element successfully.  

Good Luck.
