### ISSUE TITLE
Not able to start Selendorid Server 

### ISSUE THREAD

**Issue by ngohchuong** [selendroid/selendroid#1029]
I'm working on windows 7 64 bit machine. Set up ANDROID_HOME , JAVA_HOME , PATH successful.
When i run this command on cmd: 
![cmd](https://cloud.githubusercontent.com/assets/16876411/12546744/791f7d52-c37e-11e5-9231-35903328fb87.png)
Please help me
But when i start from java eclipse: 

INFO: Starting Selendroid standalone on port 4444
Jan 25, 2016 3:57:13 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/MANIFEST.MF
Jan 25, 2016 3:57:14 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/MANIFEST.MF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:142)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at AdvanceSelendroid.AdvanceTest.setup(AdvanceTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Jan 25, 2016 3:57:14 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/CERT.RSA
Jan 25, 2016 3:57:14 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/CERT.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)

**Comment by pver** [comment]
Actually, the entire aapt command being executed is:

```C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/MANIFEST.MF```

(you forgot the 'META-INF/MANIFEST.MF' argument)

This does not necessarily mean that this is the root cause: at startup the selendroid server is trying to remove a bunch of files from the apk 'just to be sure'. It doesn't check if every file is actually in the apk or not: https://github.com/selendroid/selendroid/blob/master/selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java#L140
When a file isn't present, it outputs the errors you see.. This is very confusing and spams the logs unnecessarily, but it shouldn't stop the server from starting. (I see those errors as well when I start the server, but everything is ok)

Do you have more logging after that error? After the 'aapt.exe remove' part, it should show a 'jarsigner.exe' command being executed

**Comment by ngohchuong** [comment]
Yeah, it is very confusing and spam a lot of, but server still can be started. But i don't want to see these exception. And i thought that there would be problem at aapt.exe.
Log after that error :


Jan 27, 2016 9:52:28 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/NDKEYSTO.RSA
Jan 27, 2016 9:52:28 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe remove C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at AdvanceSelendroid.AdvanceTest.setup(AdvanceTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Jan 27, 2016 9:52:28 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.8.0_65\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\resigned-toppay.apk -storepass android -keystore C:\Users\GCAFE\.android\debug.keystore C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\toppay.apk androiddebugkey
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2043-05-31) or after any future revocation date.
<--
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2043-05-31) or after any future revocation date.
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\resigned-toppay.apk
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe dump badging C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\resigned-toppay.apk
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='com.beeasy.toppay.internal' versionCode='190' versionName='0.2.2-internal' platformBuildVersionName='6.0-2438415'
sdkVersion:'10'
targetSdkVersion:'23'
 uses-feature: name='android.hardware.touchscreen'
  uses-feature-not-required: name='android.hardware.wifi'
  uses-feature: name='android.hardware.screen.portrait'
  uses-implied-feature: name='android.hardware.screen.portrait' reason='one or more activities have specified a portrait orientation'
main
other-activities
other-receivers
other-services
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'th' 'ca' 'da' 'fa' 'ja' 'nb' 'id' 'de' 'he' 'af' 'bg' 'fi' 'hi' 'vi' 'sk' 'uk' 'el' 'nl' 'pl' 'sl' 'tl' 'am' 'in' 'ko' 'ro' 'ar' 'fr' 'hr' 'sr' 'tr' 'cs' 'es' 'it' 'lt' 'pt' 'eu' 'hu' 'ru' 'zu' 'lv' 'sv' 'iw' 'sw' 'fr-CA' 'lo-LA' 'en-GB' 'bn-BD' 'et-EE' 'ka-GE' 'ky-KG' 'km-KH' 'zh-HK' 'si-LK' 'mk-MK' 'ur-PK' 'sq-AL' 'hy-AM' 'my-MM' 'zh-CN' 'pa-IN' 'ta-IN' 'te-IN' 'ml-IN' 'en-IN' 'kn-IN' 'mr-IN' 'gu-IN' 'mn-MN' 'ne-NP' 'pt-BR' 'gl-ES' 'eu-ES' 'is-IS' 'es-US' 'pt-PT' 'en-AU' 'zh-TW' 'ms-MY' 'az-AZ' 'kk-KZ' 'uz-UZ'
densities: '120' '160' '213' '240' '320' '480' '640'
native-code: 'arm64-v8a' 'armeabi' 'armeabi-v7a' 'mips' 'x86' 'x86_64'
<--
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\GCAFE\android-sdks\platform-tools\aapt.exe dump badging C:\Chuong\Work\Automation\AdvanceSelendroid\src\main\resources\resigned-toppay.apk
Jan 27, 2016 9:52:33 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
package: name='com.beeasy.toppay.internal' versionCode='190' versionName='0.2.2-internal' platformBuildVersionName='6.0-2438415'
sdkVersion:'10'
targetSdkVersion:'23'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.VIBRATE'
.......................
