### ISSUE TITLE
Can't resign my app on a Windows 8 x64 with Selendroid 0.17.0

### ISSUE THREAD

**Issue by holybible934** [selendroid/selendroid#1031]
I encounter a very strange situation and would like to know how to resolve it.
Here is the summary of my results:

1. Run Selendroid 0.17 to resign my app, it got an exception that only tells resigning had a problem then ended up.
2. Run Selendroid 0.17 to resign selendroid-Test-App, it worked and selendroid server was launched.
3. Run SelendroidServer on a Macbook to resign my app (A copy of my app in 1.), it resigned my app successfully, too.

Does anyone have an idea about this?

**Comment by holybible934** [comment]
Log of resigning my app

2 01, 2016 4:28:17 午後 io.selendroid.standalone.io.ShellCommand exec
情報: Executing shell command: C:\Program Files\Java\jdk1.8.0_72\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar c:\automation\ios_appium_junit\selendroid_server\resigned-Android-release.apk -storepass android -keystore C:\Users\xxxx\.android\debug.keystore c:\automation\ios_appium_junit\selendroid_server\Android-release.apk androiddebugkey
2 01, 2016 4:28:37 午後 io.selendroid.standalone.io.ShellCommand exec
重大: Error executing command: C:\Program Files\Java\jdk1.8.0_72\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar c:\automation\ios_appium_junit\selendroid_server\resigned-Android-release.apk -storepass android -keystore C:\Users\xxxx\.android\debug.keystore c:\automation\ios_appium_junit\selendroid_server\Android-release.apk androiddebugkey
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

2 01, 2016 4:28:37 午後 io.selendroid.standalone.SelendroidLauncher launchServer
重大: Error building server: An error occurred while resigning the app 'Android-release.apk'. 
Exception in thread "main" io.selendroid.server.common.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'Android-release.apk'. 
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:124)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Program Files\Java\jdk1.8.0_72\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar c:\automation\ios_appium_junit\selendroid_server\resigned-Android-release.apk -storepass android -keystore C:\Users\xxxx\.android\debug.keystore c:\automation\ios_appium_junit\selendroid_server\Android-release.apk androiddebugkey
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	... 6 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: 
	... 10 more

**Comment by operatiay** [comment]
it might help if you try executing the failing command manually: `C:\Program Files\Java\jdk1.8.0_72\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar c:\automation\ios_appium_junit\selendroid_server\resigned-Android-release.apk -storepass android -keystore C:\Users\xxxx.android\debug.keystore c:\automation\ios_appium_junit\selendroid_server\Android-release.apk androiddebugkey`

**Comment by holybible934** [comment]
I just tried jarsign command directly and it worked.
Now I become more confused and I can only guess it is because either PATH problem (like SPACE in Program Files) or Selendroid used wrong jarsign as the jarsign.exe it used is in <JDK>\jre\, which should be under <JDK>\bin

**Comment by operatiay** [comment]
if the exact command executed by selendroid works outside, then everything should be set up properly. the jarsigner location is seen in the logs.

**Comment by holybible934** [comment]
Well, I think this a bug related to `public static String javaHome() ` in JavaSdk.java  
For Windows case, by default Java will be either installed under C:\Program Files or C:\Program Files (x86), which requires further handling about the SPACE / Quote of its path.

To resolve this issue, there shall be 1 more block to handle default path problem of Windows in JavaSdk.javaHome()

**Comment by holybible934** [comment]
OK, I guess I shall close my issue and use https://github.com/selendroid/selendroid/issues/47 to track.
The symptom and error trace show me that my problem is around SHA1
