### ISSUE TITLE
Selendroid execute exception error with Android driver

### ISSUE THREAD

**Issue by qv44** [selendroid/selendroid#1033]
Hi ,
       I am trying to run tests on mobile web using android driver.I am running it using testng framework.
    My code is 
 try {
				 if (selendroidServer != null) {
				    selendroidServer.stopSelendroid();
				    }
				 SelendroidConfiguration config = new SelendroidConfiguration();
				 selendroidServer = new SelendroidLauncher(config);
			      selendroidServer.launchSelendroid();
			     DesiredCapabilities caps = SelendroidCapabilities.android();
			     common.driver = new SelendroidDriver(caps);
                             common.driver.get("https://m.ebay.in/");
catch (Exception e) {
               
             		 e.printStackTrace();
             	}
			

Error in console:
INFO: Starting Selendroid standalone on port 4444
Feb 16, 2016 1:24:24 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/MANIFEST.MF
Feb 16, 2016 1:24:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Feb 16, 2016 1:24:25 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/CERT.RSA
Feb 16, 2016 1:24:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Feb 16, 2016 1:24:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/CERT.SF
Feb 16, 2016 1:24:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Feb 16, 2016 1:24:26 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/ANDROIDD.SF
Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.Driver.setUp(Driver.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/ANDROIDD.RSA
Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/ANDROIDD.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.Driver.setUp(Driver.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/NDKEYSTO.SF
Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/NDKEYSTO.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.Driver.setUp(Driver.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/NDKEYSTO.RSA
Feb 16, 2016 1:24:27 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.Driver.setUp(Driver.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by sbartsa** [comment]
Damn I have the same problem and going nuts here. Apparently if you run the command "C:\Users\Sumedh\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe remove C:\Users\Sumedh\AppData\Local\Temp\android-driver842295131459285874.apk META-INF/MANIFEST.MF" you get "Error unzipping file"
