### ISSUE TITLE
io.selendroid.server.common.exceptions.SessionNotCreatedException: Error starting Selendroid session (0.17.0)

### ISSUE THREAD

**Issue by kazirashedulhaque** [selendroid/selendroid#1042]
This is the status on [http://localhost:4444/wd/hub/status](url)

`{"value":{"os":{"name":"Windows 7","arch":"x86","version":"6.1"},"build":{"browserName":"selendroid","version":"0.17.0"},"supportedDevices":[{"emulator":true,"screenSize":"(1080, 1920)","avdName":"Nexus_5_API_23_x86","platformVersion":"23","apiTargetType":"google"},{"emulator":true,"screenSize":"(240, 320)","avdName":"Xamarin_Android_API_23","platformVersion":"23","apiTargetType":"android"},{"emulator":true,"screenSize":"(240, 320)","avdName":"Xamarin_Android_API_15","platformVersion":"15","apiTargetType":"android"},{"emulator":false,"screenSize":"(480, 854)","serial":"44375325431491","platformVersion":"22","model":"V52","apiTargetType":"google"}],"supportedApps":[{"mainActivity":"io.selendroid.androiddriver.WebViewActivity","appId":"io.selendroid.androiddriver:0.17.0","basePackage":"io.selendroid.androiddriver"},{"mainActivity":"com.guru99app.MainActivity","appId":"com.guru99app:1.0","basePackage":"com.guru99app"}]},"status":0}`

This is my code,

    private SelendroidLauncher selendroidServer;
    private SelendroidDriver driver;
    
    @BeforeSuite
    public void setUp() throws Exception {
    
    SelendroidConfiguration config = new SelendroidConfiguration();
    config.addSupportedApp("/resigned-Guru99App.apk");
    selendroidServer = new SelendroidLauncher(config);
    selendroidServer.launchSelendroid();
    SelendroidCapabilities capabilities = new SelendroidCapabilities("com.guru99app:1.0");
    capabilities.setPlatformVersion(DeviceTargetPlatform.ANDROID22);

    capabilities.setEmulator(true);
    driver = new SelendroidDriver(capabilities);

    }
    
    @Test
    public void selendroidTest() throws Exception {

    System.out.print("Start executing test");
    WebElement inputField = driver.findElement(By.id("edtText"));
    WebElement button = driver.findElement(By.id("btnShow"));
    button.click();
    Thread.sleep(5000);
    WebElement txtView = driver.findElement(By.id("txtView"));
    String expected = txtView.getText();
    Assert.assertEquals(expected, inputField.getText());      
 
    }
    
    @AfterSuite
    public void tearDown() {
  	    driver.quit();
  	    selendroidServer.stopSelendroid();
    }

This is the output on Eclipse,

Mar 22, 2016 11:45:23 AM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.server.model.SelendroidStandaloneDriver initApplicationsUnderTest
SEVERE: Ignoring app because it was not found: C:\resigned-Guru99App.apk
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/MANIFEST.MF
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/CERT.RSA
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/CERT.SF
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/ANDROIDD.SF
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.guru.test.Guru99Test.setUp(Guru99Test.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/ANDROIDD.RSA
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/ANDROIDD.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.guru.test.Guru99Test.setUp(Guru99Test.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/NDKEYSTO.SF
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/NDKEYSTO.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.guru.test.Guru99Test.setUp(Guru99Test.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/NDKEYSTO.RSA
Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe remove C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.launchSelendroid(SelendroidLauncher.java:90)
	at com.guru.test.Guru99Test.setUp(Guru99Test.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

Mar 22, 2016 11:45:23 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.8.0_71\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Jafra\AppData\Local\Temp\resigned-android-driver5155709856555441790.apk -storepass android -keystore C:\Users\Jafra\.android\debug.keystore C:\Users\Jafra\AppData\Local\Temp\android-driver5155709856555441790.apk androiddebugkey
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2045-10-11) or after any future revocation date.
<--
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2045-10-11) or after any future revocation date.
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Users\Jafra\AppData\Local\Temp\resigned-android-driver5155709856555441790.apk
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -s 44375325431491 shell ls /system/framework/*map*
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/system/framework/com.google.android.maps.jar
<--
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=44375325431491, model=null, targetVersion=null, apiTargetType=google]
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe -s 44375325431491 shell ls /system/framework/*map*
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
/system/framework/com.google.android.maps.jar
<--
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=44375325431491, model=V52, targetVersion=ANDROID22, apiTargetType=google]
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
Mar 22, 2016 11:45:24 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\tools\android.bat list avds
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Access is denied.
Available Android Virtual Devices:
    Name: Nexus_5_API_23_x86
  Device: Nexus 5 (Google)
    Path: C:\Users\Jafra\.android\avd\Nexus_5_API_23_x86.avd
  Target: Google APIs (Google Inc.)
          Based on Android 6.0 (API level 23)
 Tag/ABI: google_apis/x86
    Skin: 1080x1920
  Sdcard: 200M
---------
    Name: Xamarin_Android_API_15
    Path: C:\Users\Jafra\.android\avd\Xamarin Android API 15.avd
  Target: Android 4.0.3 (API level 15)
 Tag/ABI: default/armeabi-v7a
    Skin: QVGA
  Sdcard: 512M
---------
    Name: Xamarin_Android_API_23
    Path: C:\Users\Jafra\.android\avd\Xamarin Android API 23.avd
  Target: Android 6.0 (API level 23)
 Tag/ABI: default/armeabi-v7a
    Skin: QVGA
  Sdcard: 512M
<--
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: E:\Rashed\Official\SDK\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe devices
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
List of devices attached
44375325431491	device
<--
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=(1080, 1920), targetPlatform=ANDROID23, serial=null, avdName=Nexus_5_API_23_x86, model=Nexus 5 (Google), apiTargetType=google]
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=(240, 320), targetPlatform=ANDROID15, serial=null, avdName=Xamarin_Android_API_15, model=, apiTargetType=android]
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=(240, 320), targetPlatform=ANDROID23, serial=null, avdName=Xamarin_Android_API_23, model=, apiTargetType=android]
Mar 22, 2016 11:45:26 AM io.selendroid.standalone.server.SelendroidStandaloneServer start
INFO: Selendroid standalone server has been started on port: 4444
Exception in thread "Thread-26" java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:476)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1021)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:455)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:844)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:195)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:339)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
FAILED CONFIGURATION: @BeforeSuite setUp
org.openqa.selenium.SessionNotCreatedException: Error starting Selendroid session
Command duration or timeout: 110 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Jafra-PC', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_73'
Driver info: io.selendroid.client.SelendroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at io.selendroid.client.SelendroidDriver.<init>(SelendroidDriver.java:71)
	at io.selendroid.client.SelendroidDriver.<init>(SelendroidDriver.java:84)
	at com.guru.test.Guru99Test.setUp(Guru99Test.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: io.selendroid.server.common.exceptions.SessionNotCreatedException: Error starting Selendroid session

SKIPPED: selendroidTest

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@2d56bf: 10 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@aa7bc2: 21 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@aa6d82: 10 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@161bd48: 30 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@1b4f649: 0 ms

i am stuck with this problem for two days. Any help will be really really appreciated.

**Comment by operatiay** [comment]
are you trying to launch Selendroid server from your code while the server has been started externally?

**Comment by kazirashedulhaque** [comment]
I got it now, I was trying to launch Selendroid both from my code and command prompt! Thanks a lot for pointing this out.

**Comment by kazirashedulhaque** [comment]
But, could you please help me with the following thing. Suppose I have not already started Selendroid server from the command prompt and rather I want to launch it from  my code, does the following code suffice?

@BeforeTest
    public void setUp() throws Exception {   
    SelendroidConfiguration config = new SelendroidConfiguration();
    config.addSupportedApp("Guru99App.apk");
    selendroidServer = new SelendroidLauncher(config);
    selendroidServer.launchSelendroid();
    SelendroidCapabilities capabilities = new SelendroidCapabilities("com.guru99app:1.0");
    capabilities.setPlatformVersion(DeviceTargetPlatform.ANDROID22);
    capabilities.setEmulator(false);
    driver = new SelendroidDriver(capabilities);
    }

**Comment by operatiay** [comment]
:) why don't you try it out? I guess the main issue here might be the path to your app.

another thing I wanted to mention: this doesn't seem to be an issue with the framework itself. why don't you try asking questions in the forum https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/selendroid
