### ISSUE TITLE
The requested command is currently not yet supported by selendroid

### ISSUE THREAD

**Issue by sabrik2** [selendroid/selendroid#1053]
Hello, this is my first post. When I run the code, the pop up for a sec.Then this error pop up. Can someone please explain to me the error?

**org.openqa.selenium.UnsupportedCommandException: The requested command is currently not yet supported by selendroid.
Command duration or timeout: 36 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'BC877003-NB', ip: '192.168.0.110', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: io.selendroid.client.SelendroidDriver
Capabilities [{emulator=false, aut=com.cimbmalaysia.staging:03.23.00-staging, serial=a7dfc15a, platformVersion=18, automationName=selendroid, browserName=selendroid, platformName=android, platform=ANY}]
Session ID: 6ddfbcd3-7bd2-6f40-1ec1-79ba2cadce92
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:511)
	at cimb.mobile.tests.RemoteWebdriverTests.destroy(RemoteWebdriverTests.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.afterRun(TestRunner.java:1005)
	at org.testng.TestRunner.run(TestRunner.java:636)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.server.common.exceptions.SelendroidException: The requested command is currently not yet supported by selendroid.**

<2016-05-11 00:13:57> DEBUG [o.a.h.c.p.RequestAddCookies] CookieSpec selected: default
<2016-05-11 00:13:57> DEBUG [o.a.h.c.p.RequestAuthCache] Auth cache not set in the context
<2016-05-11 00:13:57> DEBUG [o.a.h.i.c.PoolingHttpClientConnectionManager] Connection request: [route: {}->http://localhost:4444][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
<2016-05-11 00:13:57> DEBUG [o.a.h.i.c.PoolingHttpClientConnectionManager] Connection leased: [id: 2][route: {}->http://localhost:4444][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
<2016-05-11 00:13:57> DEBUG [o.a.h.i.execchain.MainClientExec] Opening connection {}->http://localhost:4444
<2016-05-11 00:13:57> DEBUG [o.a.h.i.c.DefaultHttpClientConnectionOperator] Connecting to localhost/127.0.0.1:4444
<2016-05-11 00:13:57> DEBUG [o.a.h.i.c.DefaultHttpClientConnectionOperator] Connection established 127.0.0.1:2543<->127.0.0.1:4444
<2016-05-11 00:13:57> DEBUG [o.a.h.i.c.DefaultManagedHttpClientConnection] http-outgoing-2: set socket timeout to 10800000
<2016-05-11 00:13:57> DEBUG [o.a.h.i.execchain.MainClientExec] Executing request DELETE /wd/hub/session/6ddfbcd3-7bd2-6f40-1ec1-79ba2cadce32 HTTP/1.1
<2016-05-11 00:13:57> DEBUG [o.a.h.i.execchain.MainClientExec] Target auth state: UNCHALLENGED
<2016-05-11 00:13:57> DEBUG [o.a.h.i.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
<2016-05-11 00:13:57> DEBUG [org.apache.http.headers] http-outgoing-2 >> DELETE /wd/hub/session/6ddfbcd3-7bd2-6f40-1ec1-79ba2cadce32 HTTP/1.1
<2016-05-11 00:13:57> DEBUG [org.apache.http.headers] http-outgoing-2 >> Host: localhost:4444
<2016-05-11 00:13:57> DEBUG [org.apache.http.headers] http-outgoing-2 >> Connection: Keep-Alive
<2016-05-11 00:13:57> DEBUG [org.apache.http.headers] http-outgoing-2 >> User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_92)
<2016-05-11 00:13:57> DEBUG [org.apache.http.headers] http-outgoing-2 >> Accept-Encoding: gzip,deflate
<2016-05-11 00:13:57> DEBUG [org.apache.http.wire] http-outgoing-2 >> "DELETE /wd/hub/session/6ddfbcd3-7bd2-6f40-1ec1-79ba2cadce32 HTTP/1.1[\r][\n]"
<2016-05-11 00:13:57> DEBUG [org.apache.http.wire] http-outgoing-2 >> "Host: localhost:4444[\r][\n]"
<2016-05-11 00:13:57> DEBUG [org.apache.http.wire] http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]"
<2016-05-11 00:13:57> DEBUG [org.apache.http.wire] http-outgoing-2 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_92)[\r][\n]"
<2016-05-11 00:13:57> DEBUG [org.apache.http.wire] http-outgoing-2 >> "Accept-Encoding: gzip,deflate[\r][\n]"
<2016-05-11 00:13:57> DEBUG [org.apache.http.wire] http-outgoing-2 >> "[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "HTTP/1.1 200 OK[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "Connection: close[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "Content-Encoding: identity[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "Content-Type: application/json[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "Content-Length: 74[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "[\r][\n]"
<2016-05-11 00:13:58> DEBUG [org.apache.http.wire] http-outgoing-2 << "{"sessionId":"6ddfbcd3-7bd2-6f40-1ec1-79ba2cadce32","value":"","status":0}"
<2016-05-11 00:13:58> DEBUG [org.apache.http.headers] http-outgoing-2 << HTTP/1.1 200 OK
<2016-05-11 00:13:58> DEBUG [org.apache.http.headers] http-outgoing-2 << Connection: close
<2016-05-11 00:13:58> DEBUG [org.apache.http.headers] http-outgoing-2 << Content-Encoding: identity
<2016-05-11 00:13:58> DEBUG [org.apache.http.headers] http-outgoing-2 << Content-Type: application/json
<2016-05-11 00:13:58> DEBUG [org.apache.http.headers] http-outgoing-2 << Content-Length: 74
<2016-05-11 00:13:58> DEBUG [o.a.h.i.c.DefaultManagedHttpClientConnection] http-outgoing-2: Close connection
<2016-05-11 00:13:58> DEBUG [o.a.h.i.execchain.MainClientExec] Connection discarded
<2016-05-11 00:13:58> DEBUG [o.a.h.i.c.PoolingHttpClientConnectionManager] Connection released: [id: 2][ro

**Comment by makhov** [comment]
Please, show the code, which causes the error
