### ISSUE TITLE
selendroid-0.17.0 -> pom.xml -> mvn clean install fails with unknown failure during compilation

### ISSUE THREAD

**Issue by AdarshMaurya** [selendroid/selendroid#1091]
**Bug Replication -**

**1. Java Environment**
D:\selendroid-0.17.0>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_112

**2. Maven Version -**
D:\selendroid-0.17.0>mvn -v
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: D:\16.Maven\apache-maven-3.3.9
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_112\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "dos"

**3. Command**
D:\selendroid-0.17.0> mvn clean install -X

**4. Changes made in files -** 
Please note: for selendroid-0.17.0\pom.xml &  {Base.dir}\ selendroid-server\pom.xml

`<project
    ...
<build>
  ...
<plugin>
       <groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.5.1</version>
		<configuration>
			<source>1.8</source>
			<target>1.8</target>
		</configuration>
</plugin>
...
</build>
...
</project>`

**Fails at**
...
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\model\SearchContext.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\android\AndroidWait.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\handler\FrameSwitchHandler.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\handler\OpenUrl.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\model\TagNamePredicate.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\handler\DeleteSession.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\model\KnownElements.java
[DEBUG] Stale source detected: D:\selendroid-0.17.0\selendroid-server\src\main\java\io\selendroid\server\model\KnownElements.java
[INFO] Changes detected - recompiling the module!
[DEBUG] Classpath:
[DEBUG]  D:\selendroid-0.17.0\selendroid-server\target\classes
[DEBUG]  D:\selendroid-0.17.0\selendroid-server-common\target\selendroid-server-common-0.17.0.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\io\netty\netty-all\4.0.21.Final\netty-all-4.0.21.Final.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\com\google\android\android\4.1.1.4\android-4.1.1.4.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\org\khronos\opengl-api\gl1.1-android-2.1_r1\opengl-api-gl1.1-android-2.1_r1.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\xerces\xmlParserAPIs\2.6.2\xmlParserAPIs-2.6.2.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\xpp3\xpp3\1.1.4c\xpp3-1.1.4c.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\org\json\json\20080701\json-20080701.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\org\apache\cordova\cordova\3.7.0\cordova-3.7.0-android.jar
[DEBUG]  C:\Users\Adarsh\.m2\repository\org\apache\cordova-android\cordova\4.0.0\cordova-4.0.0-android.jar
[DEBUG] Source roots:
[DEBUG]  D:\selendroid-0.17.0\selendroid-server\src\main\java
[DEBUG]  D:\selendroid-0.17.0\selendroid-server\target\generated-sources\r
[DEBUG]  D:\selendroid-0.17.0\selendroid-server\target\generated-sources\aidl
[DEBUG] Command line options:
[DEBUG] -d D:\selendroid-0.17.0\selendroid-server\target\classes -classpath D:\selendroid-0.17.0\selendroid-server\target\classes;D:\selendroid-0.17.0\selendroid-server-common\target\selendroid-server-common-0.17.0.jar;C:\Users\Adarsh\.m2\repository\io\netty\netty-all\4.0.21.Final\netty-all-4.0.21.Final.jar;C:\Users\Adarsh\.m2\repository\com\google\android\android\4.1.1.4\android-4.1.1.4.jar;C:\Users\Adarsh\.m2\repository\org\khronos\opengl-api\gl1.1-android-2.1_r1\opengl-api-gl1.1-android-2.1_r1.jar;C:\Users\Adarsh\.m2\repository\xerces\xmlParserAPIs\2.6.2\xmlParserAPIs-2.6.2.jar;C:\Users\Adarsh\.m2\repository\xpp3\xpp3\1.1.4c\xpp3-1.1.4c.jar;C:\Users\Adarsh\.m2\repository\org\json\json\20080701\json-20080701.jar;C:\Users\Adarsh\.m2\repository\org\apache\cordova\cordova\3.7.0\cordova-3.7.0-android.jar;C:\Users\Adarsh\.m2\repository\org\apache\cordova-android\cordova\4.0.0\cordova-4.0.0-android.jar; -sourcepath D:\selendroid-0.17.0\selendroid-server\src\main\java;D:\selendroid-0.17.0\selendroid-server\target\generated-sources\r;D:\selendroid-0.17.0\selendroid-server\target\generated-sources\aidl; -s D:\selendroid-0.17.0\selendroid-server\target\generated-sources\annotations -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
**[INFO] Compiling 186 source files to D:\selendroid-0.17.0\selendroid-server\target\classes**
...
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
...
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] selendroid ......................................... SUCCESS [  0.219 s]
[INFO] android-driver-app ................................. SUCCESS [  8.690 s]
[INFO] selendroid-server-common ........................... SUCCESS [  2.467 s]
[INFO] selendroid-server .................................. FAILURE [  6.662 s]
[INFO] selendroid-grid-plugin ............................. SKIPPED
[INFO] selendroid-common .................................. SKIPPED
[INFO] selendroid-standalone .............................. SKIPPED
[INFO] selendroid-client .................................. SKIPPED
[INFO] selendroid-test-app ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.943 s
[INFO] Finished at: 2016-11-29T23:44:57+05:30
[INFO] Final Memory: 29M/89M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project selendroid-server: Compilation failure
[ERROR] An unknown compilation problem occurred
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project selendroid-server: Compilation failure
An unknown compilation problem occurred

>>http://stackoverflow.com/questions/26458675/maven-compilation-issue-the-system-is-out-of-resources

I would be thankful if some one can help me in getting it fixed. Thanks..

**Comment by arunkrishnamurthy** [comment]
Try compiling with JDK 1.7 or lower

**Comment by AdarshMaurya** [comment]
@arunkrishnamurthy : Hi Arun! Thanks but it was no futile.  I did try with JDK 1.7 and 1.6. Also with combination of Maven 3.3.9(with JDK 1.8) and Maven 3.2.5. The above compilation error due to JVM OOME  is kinda bugging me now.  I did try with JVM -xms & -xmx and MAVEN_OPTS flag too.  Tried and tested by importing in intelliJ and Eclipse Juno. -.- Seems like I have to get my RAM upgraded T.T

NOTE: When we do try with JDK 1.7 or lower, there is failure of build in android-driver module.  With JDK 1.8 with below specifications we can't build package due to OOME.

Specs - x86 , Windows 7, total physical mem - 2.99 GB, Available - 1.55 GB.

![sytem_property](https://cloud.githubusercontent.com/assets/11833079/21487046/3c18dfa4-cbe6-11e6-818f-c8bce449f3bd.PNG)

**Comment by marcelogomez** [comment]
Can you try using gradle to build instead?
`gradle celean build`

**Comment by AdarshMaurya** [comment]
It had been a been a while taking a new pull & i can see many updates had been done to the project. I would redo it, take a new fresh pull & would try to rebuilt the project and update my comment accordingly. 
`gradle clean build` :) 
Thanks!
