### ISSUE TITLE
start selendroid server fail!!!

### ISSUE THREAD

**Issue by szhuangli890944** [selendroid/selendroid#1105]
F:\robot1\selendroid>java -jar selendroid-standalone-0.17.0-with-dependencies.jar -app selendroid-test-app-0.17.0.apk
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.SelendroidLauncher main
信息: ################# Selendroid #################
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.SelendroidLauncher main
信息: ################# Configuration in use #################
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.SelendroidLauncher main
信息: io.selendroid.standalone.SelendroidConfiguration@732e3e73[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[selendroid-test-app-0.17.0.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  registerCycle=0
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
  deleteTmpFiles=true
]
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.SelendroidLauncher launchServer
信息: Starting Selendroid standalone on port 4444
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/MANIFEST.MF
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/MANIFEST.MF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:142)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/CERT.RSA
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/CERT.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:143)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/CERT.SF
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/CERT.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:144)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/ANDROIDD.SF
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/ANDROIDD.RSA
三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/ANDROIDD.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:50 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/NDKEYSTO.SF
三月 13, 2017 9:33:51 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/NDKEYSTO.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:51 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/NDKEYSTO.RSA
三月 13, 2017 9:33:51 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: D:\android-sdk_r24.4.1-windows2\sdk\build-tools\25.0.2\aapt.exe remove F:\robot1\selendroid\selendroid-test-app-0.17.0.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

三月 13, 2017 9:33:51 上午 io.selendroid.standalone.io.ShellCommand exec
信息: Executing shell command: C:\Program Files\Java\jdk1.7.0_51\jre\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar F:\robot1\selendroid\resigned-selendroid-test-app-0.17.0.apk -store
pass android -keystore C:\Users\li.huang\.android\debug.keystore F:\robot1\selendroid\selendroid-test-app-0.17.0.apk androiddebugkey
三月 13, 2017 9:33:51 上午 io.selendroid.standalone.io.ShellCommand exec
严重: Error executing command: C:\Program Files\Java\jdk1.7.0_51\jre\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar F:\robot1\selendroid\resigned-selendroid-test-app-0.17.0.apk -store
pass android -keystore C:\Users\li.huang\.android\debug.keystore F:\robot1\selendroid\selendroid-test-app-0.17.0.apk androiddebugkey
java.io.IOException: Cannot run program "C:\Program Files\Java\jdk1.7.0_51\jre\bin\jarsigner.exe" (in directory "."): CreateProcess error=2, ?????????
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:254)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:319)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: java.io.IOException: CreateProcess error=2, ?????????
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
        ... 16 more

三月 13, 2017 9:33:51 上午 io.selendroid.standalone.SelendroidLauncher launchServer
严重: Error building server: An error occurred while resigning the app 'selendroid-test-app-0.17.0.apk'.
Exception in thread "main" io.selendroid.server.common.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'selendroid-test-app-0.17.0.apk'.
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:124)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
        at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
        at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
        at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Program Files\Java\jdk1.7.0_51\jre\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedj
ar F:\robot1\selendroid\resigned-selendroid-test-app-0.17.0.apk -storepass android -keystore C:\Users\li.huang\.android\debug.keystore F:\robot1\selendroid\selendroid-test-app-0.17.0.apk androiddebugk
ey
        at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
        at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
        at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
        ... 6 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException:
        ... 10 more

**Comment by ray007** [comment]
I seem to have a similar (the same?) problem, output here ends with
```
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: The "android" command is no longer available.
For manual SDK and AVD management, please use Android Studio.                                                      
For command-line tools, use                                                                                        
tools\bin\sdkmanager.bat and tools\bin\avdmanager.bat                                                              
```
Seems the commands to use the android sdk tools have changed.

**Comment by DewaldSchoonderwoerd** [comment]
@ray007 Any work around you can recommend? I have the same problem.

**Comment by szhuangli890944** [comment]
it resolved by reset the Java home environment and restarted computer.
