### ISSUE TITLE
Cannot start Selendroid server

### ISSUE THREAD

**Issue by Sumitforyou** [selendroid/selendroid#1116]
$JAVA_HOME = /usr/lib/jvm/java-8-oracle
 $ANDROID_HOME = /home/sumit/Android/Sdk
==================================================

When the Run the below mentioned command :-> 
java -jar selendroid-standalone-0.17ith-dependencies.jar -app selendroid-test-app-0.17.0.apk

Output:

INFO: Adding: HardwareDevice [serial=FQJZQG8SAEHAZS5S, model=P7 Max, targetVersion=ANDROID23, apiTargetType=google]
May 19, 2017 8:04:43 AM io.selendroid.standalone.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
May 19, 2017 8:04:43 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/sumit/Android/Sdk/tools/android list avds
May 19, 2017 8:04:43 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/sumit/Android/Sdk/tools/android list avds
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
	at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

May 19, 2017 8:04:43 AM io.selendroid.standalone.SelendroidLauncher launchServer
SEVERE: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/sumit/Android/Sdk/tools/android list avds
Exception in thread "main" java.lang.RuntimeException: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/sumit/Android/Sdk/tools/android list avds
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:75)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/sumit/Android/Sdk/tools/android list avds
	at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:154)
	at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	... 1 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/sumit/Android/Sdk/tools/android list avds
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
	at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
	... 7 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: *************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "list avds"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk

	... 9 more

**Comment by celmaibunnebun** [comment]
I'm having the same issue on windows 10.

**Comment by MarkusPint** [comment]
Same issue on Mac OS

**Comment by celmaibunnebun** [comment]
Downgrade android sdk..

**Comment by PeterKieu** [comment]
Due to new android sdk remove some old commands.
I am finding 2 solutions:
1. Downgrade to older android sdk that supports ALL _android_ cmds => More risks/bugs on using Old Android Studio and Old Gradle and old AndroidSDK 
2. Change SelendroidStandaloneServer code to adapt new _android_ cmds
I'll reply as soon as I get success :)

**Comment by musabu** [comment]
@PeterKieu I actually did as you advised but was still getting the same error messages. Is it safe to assume that selendroid does not work on latest Android OS? If that is the case, how much downgrade is needed for it to work, I mean which API level should I use?

**Comment by rgoerner** [comment]
I recompiled this, using the fix which was adviced. Nevertheless, I also think, it is not compatible using the latest SDKs. Also, I think, that this project is not maintained anymore or?

**Comment by rgoerner** [comment]
Patched version without guarantee: https://ufile.io/ku8bl

**Comment by lpetre** [comment]
Fixed in #1136

**Comment by 9409215070** [comment]
how to solve this error:
io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: D:\android\sdk\build-tools\28.0.0\aapt.exe remo
ve C:\Users\Iconflux\AppData\Local\Temp\android-driver2694984706718533418.apk ME
TA-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value:1>

**Comment by keithvassallomt** [comment]
I've uploaded a fixed version of the Selenium Standalone Server 0.17 that should work with SDK 25+.
[https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing](https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing)

**Comment by PieceOfGood** [comment]
@keithvassallomt Great thanks!!! It is relly worked!

**Comment by leecottrellPTC** [comment]
@keithvassallomt thank you. The service started.

**Comment by tinashec** [comment]
> I've uploaded a fixed version of the Selenium Standalone Server 0.17 that should work with SDK 25+.
> https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing

Thank you, that solved hours of headaches I had yesterday trying to get Selendroid to run.

**Comment by kamlesh910** [comment]
Perfect!

**Comment by wikiwaleed2** [comment]
> > I've uploaded a fixed version of the Selenium Standalone Server 0.17 that should work with SDK 25+.
> > https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing
> 
> Thank you, that solved hours of headaches I had yesterday trying to get Selendroid to run.

Thannnnnnnnnks

**Comment by izagood** [comment]
> I've uploaded a fixed version of the Selenium Standalone Server 0.17 that should work with SDK 25+.
> https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing

thank you!!!!

**Comment by dawhudlaide** [comment]
> I've uploaded a fixed version of the Selenium Standalone Server 0.17 that should work with SDK 25+.
> https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing

Thanks Man!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by talestorylies** [comment]
> I've uploaded a fixed version of the Selenium Standalone Server 0.17 that should work with SDK 25+.
> https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing

cool , thank you ~~
