### ISSUE TITLE
Cannot run selendroid server in Windows

### ISSUE THREAD

**Issue by csanthosh13** [selendroid/selendroid#1123]
C:\Users\sanchand\Downloads>java -jar selendroid-standalone-0.17.0-with-dependencies.jar
`Jul 04, 2017 5:12:57 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Jul 04, 2017 5:12:58 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Configuration in use #################
Jul 04, 2017 5:12:58 PM io.selendroid.standalone.SelendroidLauncher main
INFO: io.selendroid.standalone.SelendroidConfiguration@3abc88[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[]
  verbose=true
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  registerCycle=0
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
  deleteTmpFiles=true
]
Jul 04, 2017 5:12:58 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Jul 04, 2017 5:12:59 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/MANIFEST.MF
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/CERT.RSA
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/CERT.SF
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/ANDROIDD.SF
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS:  'META-INF/ANDROIDD.SF' NOT FOUND
Jul 04, 2017 5:13:00 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Jul 04, 2017 5:13:01 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/ANDROIDD.RSA
Jul 04, 2017 5:13:01 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS:  'META-INF/ANDROIDD.RSA' NOT FOUND
Jul 04, 2017 5:13:01 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/ANDROIDD.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Jul 04, 2017 5:13:01 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/NDKEYSTO.SF
Jul 04, 2017 5:13:01 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS:  'META-INF/NDKEYSTO.SF' NOT FOUND
Jul 04, 2017 5:13:01 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/NDKEYSTO.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Jul 04, 2017 5:13:02 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/NDKEYSTO.RSA
Jul 04, 2017 5:13:02 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS:  'META-INF/NDKEYSTO.RSA' NOT FOUND
Jul 04, 2017 5:13:02 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\sanchand\AppData\Local\Android\sdk\build-tools\26.0.0\aapt.exe remove C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Jul 04, 2017 5:13:02 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files\Java\jdk1.8.0_92\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\sanchand\AppData\Local\Temp\resigned-android-driver7055235743330122438.apk -storepass android -keystore C:\Users\sanchand\.android\debug.keystore C:\Users\sanchand\AppData\Local\Temp\android-driver7055235743330122438.apk androiddebugkey
Jul 04, 2017 5:13:05 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: jar signed.
Jul 04, 2017 5:13:05 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: 
Jul 04, 2017 5:13:05 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: Warning: 
Jul 04, 2017 5:13:05 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-11-18) or after any future revocation date.
Jul 04, 2017 5:13:05 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-11-18) or after any future revocation date.
<--
Jul 04, 2017 5:13:06 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2044-11-18) or after any future revocation date.
Jul 04, 2017 5:13:06 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Users\sanchand\AppData\Local\Temp\resigned-android-driver7055235743330122438.apk
Jul 04, 2017 5:13:08 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\tools\android.bat list avds
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: **************************************************************************
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: The "android" command is deprecated.
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: For manual SDK, AVD, and project management, please use Android Studio.
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: For command-line tools, use tools\bin\sdkmanager.bat
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: and tools\bin\avdmanager.bat
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: **************************************************************************
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: 
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: Invalid or unsupported command "list avds"
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: 
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: Supported commands are:
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android list target
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android list avd
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android list device
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android create avd
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android move avd
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android delete avd
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android list sdk
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand$PrintingLogOutputStream processLine
FINE: OUTPUT FROM PROCESS: android update sdk
Jul 04, 2017 5:13:09 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\sanchand\AppData\Local\Android\sdk\tools\android.bat list avds
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
	at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Jul 04, 2017 5:13:09 PM io.selendroid.standalone.SelendroidLauncher launchServer
SEVERE: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Users\sanchand\AppData\Local\Android\sdk\tools\android.bat list avds
`
Can you check on this?

**Comment by PeterKieu** [comment]
Due to new android sdk remove some old commands: android list avds
I am finding 2 solutions:

    Downgrade to older android sdk that supports ALL android cmds => More risks/bugs on using Old Android Studio and Old Gradle and old AndroidSDK
    Change SelendroidStandaloneServer code to adapt new android cmds: change shellcmd android list avds to android list avd
    Line 148 of io.selendroid.standalone.android.impl.DefaultAndroidEmulator
    CommandLine cmd = new CommandLine(AndroidSdk.android());
    cmd.addArgument("list", false);
    cmd.addArgument("avds", false);

Rebuild selendroid on androidstudio again and run SelendroidStandaloneServer.
Hope this help:)
