### ISSUE TITLE
Issue running in .jar with "android list avds"

### ISSUE THREAD

**Issue by ghost** [selendroid/selendroid#1139]
SEVERE: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/acer/Android/Sdk/tools/android list avds
Exception in thread "main" java.lang.RuntimeException: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/acer/Android/Sdk/tools/android list avds
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:75)

The command is supposed to be "android list avd" not "android list avds" :(

**Comment by windysurf** [comment]
#1140 pending pull request with fix.

**Comment by lpetre** [comment]
Fixed with #1136
