### ISSUE TITLE
java.lang.NoClassDefFoundError caused by dependency conflict issue due to multiple versions of org.apache.commons:commons-exec:jar

### ISSUE THREAD

**Issue by LeoAugust19** [selendroid/selendroid#1169]
Hi, we found multiple versions of **org.apache.commons:commons-exec:jar** exist in io.selendroid:selendroid-standalone:jar:0.17.0. As shown in the following dependency tree, only **org.apache.commons:commons-exec:jar:1.1**  will be loaded, based on "Maven's nearest wins strategy", and the other versions will be shadowed during the packaging process.

However, method **<org.apache.commons.exec.DaemonExecutor: void <init>()>** only included in the shadowed version org.apache.commons:commons-exec:jar 1.3. As a result, an exception will be thrown with the following stack trace when your project referencing the missing method.

### Dependency tree
io.selendroid:selendroid-standalone:jar:0.17.0
+- **org.apache.commons:commons-exec:jar:1.1:compile**
+- org.seleniumhq.selenium:selenium-java:jar:2.48.0:compile
|  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.48.0:compile
|  |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:2.48.0:compile
|  |     +- cglib:cglib-nodep:jar:2.1_3:compile
|  |     +- com.google.code.gson:gson:jar:2.3.1:compile
|  |     +- org.seleniumhq.selenium:selenium-api:jar:2.48.0:compile
|  |     |  +- (com.google.guava:guava:jar:18.0:compile - omitted for conflict with 17.0)
|  |     |  +- (com.google.code.gson:gson:jar:2.3.1:compile - omitted for duplicate)
|  |     |  \- (org.apache.httpcomponents:httpclient:jar:4.3.4:compile - version managed from 4.5; omitted for duplicate)
|  |     +- (org.apache.httpcomponents:httpclient:jar:4.3.4:compile - version managed from 4.5; omitted for duplicate)
|  |     +- (com.google.guava:guava:jar:18.0:compile - omitted for conflict with 17.0)
|  |     +- **(org.apache.commons:commons-exec:jar:1.3:compile - omitted for conflict with 1.1)**
|  |     +- (net.java.dev.jna:jna:jar:4.1.0:compile - omitted for duplicate)
|  |     \- (net.java.dev.jna:jna-platform:jar:4.1.0:compile - omitted for duplicate)
|  +- org.seleniumhq.selenium:selenium-edge-driver:jar:2.48.0:compile
|  |  +- (org.seleniumhq.selenium:selenium-remote-driver:jar:2.48.0:compile - omitted for duplicate)
|  |  +- (commons-io:commons-io:jar:2.4:compile - omitted for conflict with 2.2)
|  |  \- **(org.apache.commons:commons-exec:jar:1.3:compile - omitted for conflict with 1.1)**
|  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.48.0:compile
|  |  +- (org.seleniumhq.selenium:selenium-remote-driver:jar:2.48.0:compile - omitted for duplicate)
|  |  +- (commons-io:commons-io:jar:2.4:compile - omitted for conflict with 2.2)
|  |  \- **(org.apache.commons:commons-exec:jar:1.3:compile - omitted for conflict with 1.1)**
|  \- org.seleniumhq.selenium:selenium-leg-rc:jar:2.48.0:compile
|     \- (org.seleniumhq.selenium:selenium-remote-drive

### Solution
Upgrade commons-exec to 1.3.

Thanks a lot!
Regards,
Leo

**Comment by LeoAugust19** [comment]
@shs96c Hi, the above information is abtained by static analysis, do you need further information to confirm   its a bug? I can try to provide you more.

**Comment by LeoAugust19** [comment]
### Stack trace

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/exec/DaemonExecutor
	at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:52)
	at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:108)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:42)

**Comment by LeoAugust19** [comment]
@lukeis, Hi, could you please help me review this issue?

Thanks a lot.
Leo
