### ISSUE TITLE
Error when starting selendroid server in ubuntu 16.04

### ISSUE THREAD

**Issue by sindhujabd** [selendroid/selendroid#1176]
When starting selendroid server, am getting the error as follows:

Mar 25, 2019 3:46:54 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Configuration in use #################
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.SelendroidLauncher main
INFO: io.selendroid.standalone.SelendroidConfiguration@20ad9418[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  registerCycle=0
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
  deleteTmpFiles=true
]
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/MANIFEST.MF
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/CERT.RSA
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/CERT.SF
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/ANDROIDD.SF
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/ANDROIDD.RSA
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/ANDROIDD.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/NDKEYSTO.SF
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/NDKEYSTO.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/NDKEYSTO.RSA
Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/build-tools/28.0.3/aapt remove /tmp/android-driver6823693364200275779.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
    at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Mar 25, 2019 3:46:54 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /usr/lib/jvm/java-8-oracle/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /tmp/resigned-android-driver6823693364200275779.apk -storepass android -keystore /home/test-laptop/.android/debug.keystore /tmp/android-driver6823693364200275779.apk androiddebugkey
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
jar signed.

Warning:
The signer's certificate is self-signed.
The MD5withRSA algorithm specified for the -sigalg option is considered a security risk.
<--
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning:
The signer's certificate is self-signed.
The MD5withRSA algorithm specified for the -sigalg option is considered a security risk.
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: /tmp/resigned-android-driver6823693364200275779.apk
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:171)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:166)
    at io.selendroid.standalone.android.impl.AbstractDevice.runAdbCommand(AbstractDevice.java:447)
    at io.selendroid.standalone.android.impl.DefaultHardwareDevice.<init>(DefaultHardwareDevice.java:40)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.deviceConnected(DefaultDeviceManager.java:155)
    at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:816)
    at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:400)
    at com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:320)
    at com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:193)
    at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:44)
    at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:84)

Mar 25, 2019 3:46:55 PM io.selendroid.standalone.android.impl.AbstractDevice executeCommandQuietly
WARNING: Could not execute command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:171)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:166)
    at io.selendroid.standalone.android.impl.AbstractDevice.runAdbCommand(AbstractDevice.java:447)
    at io.selendroid.standalone.android.impl.DefaultHardwareDevice.<init>(DefaultHardwareDevice.java:40)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.deviceConnected(DefaultDeviceManager.java:155)
    at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:816)
    at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:400)
    at com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:320)
    at com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:193)
    at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:44)
    at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:84)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: error: insufficient permissions for device: user test-laptop is not in the plugdev group
See [http://developer.android.com/tools/device.html] for more information

    ... 12 more

Mar 25, 2019 3:46:55 PM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=1621b9d4ee6ba6b3, model=null, targetVersion=null, apiTargetType=google]
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:171)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:166)
    at io.selendroid.standalone.android.impl.AbstractDevice.runAdbCommand(AbstractDevice.java:447)
    at io.selendroid.standalone.android.impl.DefaultHardwareDevice.<init>(DefaultHardwareDevice.java:40)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.deviceConnected(DefaultDeviceManager.java:155)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.initializeAdbConnection(DefaultDeviceManager.java:90)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.initialize(DefaultDeviceManager.java:213)
    at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:122)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Mar 25, 2019 3:46:55 PM io.selendroid.standalone.android.impl.AbstractDevice executeCommandQuietly
WARNING: Could not execute command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/platform-tools/adb -s 1621b9d4ee6ba6b3 shell ls /system/framework/*map*
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:171)
    at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:166)
    at io.selendroid.standalone.android.impl.AbstractDevice.runAdbCommand(AbstractDevice.java:447)
    at io.selendroid.standalone.android.impl.DefaultHardwareDevice.<init>(DefaultHardwareDevice.java:40)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.deviceConnected(DefaultDeviceManager.java:155)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.initializeAdbConnection(DefaultDeviceManager.java:90)
    at io.selendroid.standalone.android.impl.DefaultDeviceManager.initialize(DefaultDeviceManager.java:213)
    at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:122)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: error: insufficient permissions for device: user test-laptop is not in the plugdev group
See [http://developer.android.com/tools/device.html] for more information

    ... 15 more

Mar 25, 2019 3:46:55 PM io.selendroid.standalone.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=1621b9d4ee6ba6b3, model=null, targetVersion=null, apiTargetType=google]
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/tools/android list avds
Mar 25, 2019 3:46:55 PM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: /home/test-laptop/TOOLS/android-sdk-linux/tools/android list avds
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
    at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
    at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Mar 25, 2019 3:46:55 PM io.selendroid.standalone.SelendroidLauncher launchServer
SEVERE: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/tools/android list avds
Exception in thread "main" java.lang.RuntimeException: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/tools/android list avds
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:75)
    at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/tools/android list avds
    at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:154)
    at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
    at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
    at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
    at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
    ... 1 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /home/test-laptop/TOOLS/android-sdk-linux/tools/android list avds
    at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
    at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
    ... 7 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: *************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "list avds"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk

    ... 9 more

**Comment by kamlesh910** [comment]
is it fixed?

**Comment by itseasy21** [comment]
Getting the same issue on the latest Android SDK
