### ISSUE TITLE
Error on windows machine

### ISSUE THREAD

**Issue by tathastu871** [selendroid/selendroid#1197]
```
Apr 20, 2021 11:00:58 AM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Apr 20, 2021 11:00:59 AM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Configuration in use #################
Apr 20, 2021 11:00:59 AM io.selendroid.standalone.SelendroidLauncher main
INFO: io.selendroid.standalone.SelendroidConfiguration@1c2faae[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  registerCycle=0
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
  deleteTmpFiles=true
]
Apr 20, 2021 11:00:59 AM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/MANIFEST.MF
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/CERT.RSA
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/CERT.SF
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->

<--
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/ANDROIDD.SF
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/ANDROIDD.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/ANDROIDD.RSA
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/ANDROIDD.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/NDKEYSTO.SF
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/NDKEYSTO.SF
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/NDKEYSTO.RSA
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Users\Don\AppData\Local\Android\Sdk\build-tools\30.0.2\aapt.exe remove C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk META-INF/NDKEYSTO.RSA
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: C:\Program Files (x86)\Java\jre1.8.0_281\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Don\AppData\Local\Temp\resigned-android-driver882724200945800822.apk -storepass android -keystore C:\Users\Don\.android\debug.keystore C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk androiddebugkey
Apr 20, 2021 11:01:00 AM io.selendroid.standalone.io.ShellCommand exec
SEVERE: Error executing command: C:\Program Files (x86)\Java\jre1.8.0_281\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Don\AppData\Local\Temp\resigned-android-driver882724200945800822.apk -storepass android -keystore C:\Users\Don\.android\debug.keystore C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk androiddebugkey
java.io.IOException: Cannot run program "C:\Program Files (x86)\Java\jre1.8.0_281\bin\jarsigner.exe" (in directory "."): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:254)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:319)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 16 more

Apr 20, 2021 11:01:00 AM io.selendroid.standalone.SelendroidLauncher launchServer
SEVERE: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Program Files (x86)\Java\jre1.8.0_281\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Don\AppData\Local\Temp\resigned-android-driver882724200945800822.apk -storepass android -keystore C:\Users\Don\.android\debug.keystore C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk androiddebugkey
Exception in thread "main" java.lang.RuntimeException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Program Files (x86)\Java\jre1.8.0_281\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Don\AppData\Local\Temp\resigned-android-driver882724200945800822.apk -storepass android -keystore C:\Users\Don\.android\debug.keystore C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk androiddebugkey
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:175)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Program Files (x86)\Java\jre1.8.0_281\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\Don\AppData\Local\Temp\resigned-android-driver882724200945800822.apk -storepass android -keystore C:\Users\Don\.android\debug.keystore C:\Users\Don\AppData\Local\Temp\android-driver882724200945800822.apk androiddebugkey
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
	... 5 more
Caused by: io.selendroid.standalone.exceptions.ShellCommandException: 
	... 9 more

```

**Comment by tathastu871** [comment]
Please reply
