### ISSUE TITLE
DeviceStoreException: No devices are found. This can happen if the devices are in use or no device screen matches the required capabilities.

### ISSUE THREAD

**Issue by beiersdo** [selendroid/selendroid#189]
Trying to run the Hybrid test app by java -jar selendroid-standalone-0.6.0-with-dependencies.jar -app "C:\Install Files\selendroid\employee-directory.apk"

I downgraded webbit to version 0.4.10 before I ran the app, as is halted as described in one of the other posts (issue 107). 

In window one can see tht the selendroid server is started. Then I run the hybrid test app code in debug mode, and it stops in step SelendroidCapabilities.device("io.selendroid.directory:0.0.1")) when trying to start the emulator/device, then I get the following messages: 

INFO: executing command: C:\Install Files\appium\adt-bundle-windows-x86_64-20130917\sdk\tools\android.bat list avds
Dez 22, 2013 10:37:11 PM io.selendroid.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=480x800, targetPlatform=ANDROID18, avdName=ursulaDeviceEmulator]
Dez 22, 2013 10:37:11 PM io.selendroid.server.SelendroidStandaloneServer start
INFO: selendroid-standalone server has been started on port: 5555
Dez 22, 2013 10:17:33 PM io.selendroid.server.handler.CreateSessionHandler handle
INFO: new session command with capabilities: {"desiredCapabilities": {
  "aut": "io.selendroid.directory:0.0.1",
  "browserName": "selendroid",
  "emulator": false,
  "locale": "en_US"
}}
io.selendroid.exceptions.DeviceStoreException: No devices are found. This can happen if the devices are in use or no device screen matches the required capabilities.
        at io.selendroid.server.model.DeviceStore.findAndroidDevice(DeviceStore.java:240)
        at io.selendroid.server.model.SelendroidStandaloneDriver.getAndroidDevice(SelendroidStandaloneDriver.java:406)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:224)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:130)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:81)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
        at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
io.selendroid.exceptions.AndroidDeviceException: Error occured while looking for devices/emulators.
        at io.selendroid.server.model.SelendroidStandaloneDriver.getAndroidDevice(SelendroidStandaloneDriver.java:410)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:224)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:130)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:81)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
        at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.DeviceStoreException: No devices are found. This can happen if the devices are in use or no device screen matches the required capabil
        at io.selendroid.server.model.DeviceStore.findAndroidDevice(DeviceStore.java:240)
        at io.selendroid.server.model.SelendroidStandaloneDriver.getAndroidDevice(SelendroidStandaloneDriver.java:406)
        ... 19 more
Dez 22, 2013 10:17:33 PM io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
SEVERE: Error occured while finding android device: Error occured while looking for devices/emulators.
Dez 22, 2013 10:17:33 PM io.selendroid.server.handler.CreateSessionHandler handle
SEVERE: Error while creating new session: Error occured while finding android device: Error occured while looking for devices/emulators.
io.selendroid.exceptions.SessionNotCreatedException: Error occured while finding android device: Error occured while looking for devices/emulators.
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:226)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:130)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:81)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
        at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Ujjwalag** [comment]
hii
 i am facing some issue to run on the emulator, it is opening but it is not moving further.
Kindly help me...
 Below is the error i am facing 

[TestNG] Running:
  C:\Users\ug00334381\AppData\Local\Temp\testng-eclipse--1904140288\testng-customsuite.xml

FAILED CONFIGURATION: @BeforeSuite setUp
org.openqa.selenium.SessionNotCreatedException: Selendroid server on the device didn't come up after 20sec:
Command duration or timeout: 503.29 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: 'INBASDPC06690', ip: '10.53.99.44', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_51'
Driver info: io.selendroid.SelendroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:63)
	at com.guru.test.GuruAppTest1.setUp(GuruAppTest1.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: io.selendroid.server.common.exceptions.SelendroidException: Selendroid server on the device didn't come up after 20sec:

SKIPPED: selendroidTest

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@154145: 8 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@374ed5: 8 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@167198e: 192 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@1602bbc: 33 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@de24c5: 30 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 9 ms
