### ISSUE TITLE
Getting Exception in command line while performing mobile web testing

### ISSUE THREAD

**Issue by nikhiludgirkar** [selendroid/selendroid#261]
I am getting following exception while testing mobile web
```bash
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.IllegalStateException: cannot send more responses than requ
ests
        at org.jboss.netty.handler.codec.http.HttpContentEncoder.writeRequested(
HttpContentEncoder.java:101)
        at org.jboss.netty.channel.Channels.write(Channels.java:712)
        at org.jboss.netty.channel.Channels.write(Channels.java:679)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:24
6)
        at org.webbitserver.netty.NettyHttpResponse.write(NettyHttpResponse.java
:208)
        at org.webbitserver.netty.NettyHttpResponse.flushResponse(NettyHttpRespo
nse.java:196)
        at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java
:169)
        ... 4 more
org.webbitserver.WebbitException: cannot send more responses than requests on [i
d: 0x018fb1f7, /127.0.0.1:52548 :> /127.0.0.1:4444]
        at org.webbitserver.WebbitException.fromException(WebbitException.java:3
6)
        at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java
:171)
        at org.webbitserver.netty.NettyHttpChannelHandler$3.run(NettyHttpChannel
Handler.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.IllegalStateException: cannot send more responses than requ
ests
        at org.jboss.netty.handler.codec.http.HttpContentEncoder.writeRequested(
HttpContentEncoder.java:101)
        at org.jboss.netty.channel.Channels.write(Channels.java:712)
        at org.jboss.netty.channel.Channels.write(Channels.java:679)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:24
6)
        at org.webbitserver.netty.NettyHttpResponse.write(NettyHttpResponse.java
:208)
        at org.webbitserver.netty.NettyHttpResponse.flushResponse(NettyHttpRespo
nse.java:196)
        at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java
:169)
        ... 4 more
org.webbitserver.WebbitException: cannot send more responses than requests on [i
d: 0x018fb1f7, /127.0.0.1:52548 :> /127.0.0.1:4444]
        at org.webbitserver.WebbitException.fromException(WebbitException.java:3
6)
        at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java
:171)
        at org.webbitserver.netty.NettyHttpChannelHandler$3.run(NettyHttpChannel
Handler.java:94)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.IllegalStateException: cannot send more responses than requ
ests
        at org.jboss.netty.handler.codec.http.HttpContentEncoder.writeRequested(
HttpContentEncoder.java:101)
        at org.jboss.netty.channel.Channels.write(Channels.java:712)
        at org.jboss.netty.channel.Channels.write(Channels.java:679)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:24
6)
        at org.webbitserver.netty.NettyHttpResponse.write(NettyHttpResponse.java
:208)
        at org.webbitserver.netty.NettyHttpResponse.flushResponse(NettyHttpRespo
nse.java:196)
        at org.webbitserver.netty.NettyHttpResponse.error(NettyHttpResponse.java
:169)
        ... 4 more
Exception in thread "Thread-16" java.lang.OutOfMemoryError: unable to create new
 native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:597)
        at org.apache.commons.exec.PumpStreamHandler.start(PumpStreamHandler.jav
a:153)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecut
or.java:330)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
147)
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:51)
        at io.selendroid.android.impl.AbstractDevice.kill(AbstractDevice.java:20
8)
        at io.selendroid.server.model.DeviceStore.release(DeviceStore.java:78)
        at io.selendroid.server.model.SelendroidStandaloneDriver.stopSession(Sel
endroidStandaloneDriver.java:525)
        at io.selendroid.server.model.SelendroidStandaloneDriver.quitSelendroid(
SelendroidStandaloneDriver.java:538)
        at io.selendroid.server.SelendroidStandaloneServer.stop(SelendroidStanda
loneServer.java:106)
        at io.selendroid.SelendroidLauncher$1.run(SelendroidLauncher.java:83)
org.webbitserver.WebbitException: cannot send more responses than requests on [i
d: 0x018fb1f7, /127.0.0.1:52548 :> /127.0.0.1:4444]
```
In failure trace of junit it is showing NoSuchElementException even though the code is correct and element is identifiable

Thanks

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
