### ISSUE TITLE
Exception while executing android.bat list avds

### ISSUE THREAD

**Issue by GokulAthi** [selendroid/selendroid#282]
Getting the following exception while trying to execute Mobile web automation using selendriod,

```
Feb 18, 2014 10:58:31 AM io.selendroid.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
Feb 18, 2014 10:58:31 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\css97949\AppData\Local\Android\android-sdk\tools\android.bat list avds
Feb 18, 2014 10:58:51 AM io.selendroid.SelendroidLauncher lauchServer
SEVERE: Error occurred while building server: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\Users\css97949\AppData\Local\Android\android-sdk\tools\android.bat list avds
io.selendroid.exceptions.AndroidDeviceException: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\Users\css97949\AppData\Local\Android\android-sdk\tools\android.bat list avds
    at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:117)
    at io.selendroid.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:183)
    at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
    at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
    at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
    at io.selendroid.SelendroidLauncher.lauchServer(SelendroidLauncher.java:67)
    at io.selendroid.SelendroidLauncher.lauchSelendroid(SelendroidLauncher.java:90)
    at gui.selnew.main(selnew.java:24)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\Users\css97949\AppData\Local\Android\android-sdk\tools\android.bat list avds
    at io.selendroid.io.ShellCommand.exec(ShellCommand.java:53)
    at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:115)
    ... 7 more
Caused by: io.selendroid.exceptions.ShellCommandException: 'xcopy' is not recognized as an internal or external command,
operable program or batch file.

    ... 9 more
```

Can anyone sort it out??

**Comment by paulmartis** [comment]
Hello, I managed to get a workaround to list the avds faster and keeping it inside timeout timeout.
In android.bat delete this lines : 
:MkTempCopy
    rem Copy android.bat and its required libs to a temp dir.
    rem This avoids locking the tool dir in case the user is trying to update it.

    set tmp_dir=%TEMP%\temp-android-tool
    xcopy "%swt_path%" "%tmp_dir%\%swt_path%" /I /E /C /G /R /Y /Q > nul
    copy /B /D /Y lib\common.jar         "%tmp_dir%\lib\"          > nul
  
    copy /B /D /Y lib\gson*              "%tmp_dir%\lib\"          > nul
    copy /B /D /Y lib\guava*             "%tmp_dir%\lib\"          > nul
    copy /B /D /Y lib\httpclient*        "%tmp_dir%\lib\"          > nul
    copy /B /D /Y lib\httpcore*          "%tmp_dir%\lib\"          > nul
    copy /B /D /Y lib\httpmime*          "%tmp_dir%\lib\"          > nul

    copy /B /D /Y lib\org-eclipse-*      "%tmp_dir%\lib\"          > nul
    copy /B /D /Y lib\sdk*               "%tmp_dir%\lib\"          > nul
 

    rem jar_path and swt_path are relative to PWD so we don't need to adjust them, just change dirs.
    set tools_dir=%cd%
    cd /d "%tmp_dir%"

:EndTempCopy


All this lines create a temp copy for crashing. After you delete this lines the execution of android.bat list avds takes ~3-4 seconds and it gives back the entire avds list successful.

Hope it helps.
