### ISSUE TITLE
Selendroid server not running because of io.selendroid.exceptions.ShellCommandException:

### ISSUE THREAD

**Issue by sivasu38** [selendroid/selendroid#307]
Pre-Requisities  set up.
1.Updated Android SDK.
2.ANDROID HOME Set .
3.path variable set to Android_sdk/platformtools ,android_sdk/tools and as well as android_sdk/build-tools.
4.JAVA JDK is also set as java home correctly.
5.cloned the latest GIT repositry and packaged it as well to get the selendroid-standalone-jar-0.9.0.

Code 

 SelendroidConfiguration config = new SelendroidConfiguration();
 config.addSupportedApp("D:\\Selenium\\selendroid-test-app-0.9.0-SNAPSHOT.apk");
SelendroidLauncher selendroidServer = new SelendroidLauncher(config);
selendroidServer.lauchSelendroid();

SelendroidCapabilities capa=new     SelendroidCapabilities("io.selendroid.testapp:0.9.0-SNAPSHOT");

		WebDriver driver =  new SelendroidDriver(capa);
		driver.switchTo().window("NATIVE_APP");
	    driver.get("and-activity://io.selendroid.testapp.HomeScreenActivity");
		WebElement inputField = driver.findElement(By.id("my_text_field"));
		Assert.assertEquals("true", inputField.getAttribute("enabled"));
		inputField.sendKeys("Selendroid");
		Assert.assertEquals("Selendroid", inputField.getText());
		driver.findElement(By.name("visibleButtonTestCD")).click();
		driver.quit();

Logs:

Mar 01, 2014 2:45:48 AM io.selendroid.SelendroidLauncher lauchServer
INFO: Starting selendroid-server port 4444
Mar 01, 2014 2:45:48 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove D:\Selenium\selendroid-test-app-0.9.0-SNAPSHOT.apk META-INF/MANIFEST.MF
Mar 01, 2014 2:45:49 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove D:\Selenium\selendroid-test-app-0.9.0-SNAPSHOT.apk META-INF/CERT.RSA
Mar 01, 2014 2:45:49 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove D:\Selenium\selendroid-test-app-0.9.0-SNAPSHOT.apk META-INF/CERT.SF
Mar 01, 2014 2:45:49 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove D:\Selenium\selendroid-test-app-0.9.0-SNAPSHOT.apk META-INF/ANDROIDD.SF
Mar 01, 2014 2:45:49 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove D:\Selenium\selendroid-test-app-0.9.0-SNAPSHOT.apk META-INF/ANDROIDD.RSA
Mar 01, 2014 2:45:49 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.7.0_51\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\Selenium\resigned-selendroid-test-app-0.9.0-SNAPSHOT.apk -storepass android -keystore C:\Users\sivasubramanian_c\.android\debug.keystore D:\Selenium\selendroid-test-app-0.9.0-SNAPSHOT.apk androiddebugkey
Mar 01, 2014 2:45:51 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2041-07-01) or after any future revocation date.

Mar 01, 2014 2:45:51 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: D:\Selenium\resigned-selendroid-test-app-0.9.0-SNAPSHOT.apk
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe dump badging D:\Selenium\resigned-selendroid-test-app-0.9.0-SNAPSHOT.apk
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe dump badging D:\Selenium\resigned-selendroid-test-app-0.9.0-SNAPSHOT.apk
Mar 01, 2014 2:45:51 AM io.selendroid.server.model.SelendroidStandaloneDriver initApplicationsUnderTest
INFO: App io.selendroid.testapp:0.9.0-SNAPSHOT has been added to selendroid standalone server.
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove C:\Users\SIVASU~1\AppData\Local\Temp\android-driver4570779458428250570.apk META-INF/MANIFEST.MF
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove C:\Users\SIVASU~1\AppData\Local\Temp\android-driver4570779458428250570.apk META-INF/CERT.RSA
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove C:\Users\SIVASU~1\AppData\Local\Temp\android-driver4570779458428250570.apk META-INF/CERT.SF
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove C:\Users\SIVASU~1\AppData\Local\Temp\android-driver4570779458428250570.apk META-INF/ANDROIDD.SF
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\aapt.exe remove C:\Users\SIVASU~1\AppData\Local\Temp\android-driver4570779458428250570.apk META-INF/ANDROIDD.RSA
Mar 01, 2014 2:45:51 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.7.0_51\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\SIVASU~1\AppData\Local\Temp\resigned-android-driver4570779458428250570.apk -storepass android -keystore C:\Users\sivasubramanian_c\.android\debug.keystore C:\Users\SIVASU~1\AppData\Local\Temp\android-driver4570779458428250570.apk androiddebugkey
Mar 01, 2014 2:45:52 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2041-07-01) or after any future revocation date.

Mar 01, 2014 2:45:52 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Users\SIVASU~1\AppData\Local\Temp\resigned-android-driver4570779458428250570.apk
Mar 01, 2014 2:45:53 AM io.selendroid.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: Sample
Mar 01, 2014 2:45:53 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\tools\android.bat list avds
Mar 01, 2014 2:46:13 AM io.selendroid.SelendroidLauncher lauchServer
SEVERE: Error occurred while building server: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\tools\android.bat list avds
io.selendroid.exceptions.AndroidDeviceException: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\tools\android.bat list avds
	at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:117)
	at io.selendroid.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:183)
	at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
	at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
	at io.selendroid.SelendroidLauncher.lauchServer(SelendroidLauncher.java:67)
	at io.selendroid.SelendroidLauncher.lauchSelendroid(SelendroidLauncher.java:90)
	at com.symc.android.AndroidTest.main(AndroidTest.java:24)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: D:\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\tools\android.bat list avds
	at io.selendroid.io.ShellCommand.exec(ShellCommand.java:53)
	at io.selendroid.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:115)
	... 7 more
Caused by: io.selendroid.exceptions.ShellCommandException: 
	... 9 more

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
