### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: For input string: ""

### ISSUE THREAD

**Issue by RahulS99** [selendroid/selendroid#322]
I am trying to run below script to launch www.google.com with emulator (API 17).

                 SelendroidConfiguration config = new SelendroidConfiguration();

		selendroidServer = new SelendroidLauncher(config);
		selendroidServer.lauchSelendroid();

		DesiredCapabilities caps = SelendroidCapabilities.android();
		

		driver = new SelendroidDriver(caps);
		driver.manage().timeouts().implicitlyWait(8, TimeUnit.SECONDS);
		driver.get("http://www.google.com");

I am able to launch Selendroid server on 4444 and emulator successfully but it fail while creating SelendroidDriver instance with below error.

Mar 13, 2014 12:13:11 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Users\RAHULS~1\AppData\Local\Temp\resigned-android-driver1778822732476866602.apk
Mar 13, 2014 12:13:13 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\AndroidSDK\adt-bundle-windows-x86_64-20131030\sdk\tools\android.bat list avds
Mar 13, 2014 12:13:14 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\AndroidSDK\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe devices
Mar 13, 2014 12:13:14 AM io.selendroid.server.model.DeviceStore addEmulators
INFO: Adding: AndroidEmulator [screenSize=, targetPlatform=null, serial=null, avdName=dev1]
Mar 13, 2014 12:13:14 AM io.selendroid.server.SelendroidStandaloneServer start
INFO: selendroid-standalone server has been started on port: 4444
org.openqa.selenium.SessionNotCreatedException: For input string: ""
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at io.selendroid.android.impl.DefaultAndroidEmulator.allAppsGridView(DefaultAndroidEmulator.java:348)
	at io.selendroid.android.impl.DefaultAndroidEmulator.start(DefaultAndroidEmulator.java:265)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:300)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:41)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:127)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
	at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Could you please suggest the possible cause for this error.

Thanks,
Rahul

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
