### ISSUE TITLE
Unable to start selendroid sever on Win7x64

### ISSUE THREAD

**Issue by VladimirRkv** [selendroid/selendroid#331]
Hi,
I'm unable to start selendroid server on Win7x64. I downloaded selendroid-standalone-0.8.0-with-dependencies.jar and selendroid-test-app-0.8.0.apk and tried to run  java -jar selendroid-standalone-0.8.0-with-dependencies.jar -app selendroid-test-app-0.8.0.apk

I'm newbie in java so I need your help. What am I doing wrong?

Thank you in advance.

Log:
D:\_SOFT\Development\Selendroid>java -jar selendroid-standalone-0.8.0-with-dependencies.jar -app selendroid-test-app-0.8.0.apk
Mar 18, 2014 10:12:18 AM io.selendroid.SelendroidLauncher main
INFO: ################# Selendroid #################
Mar 18, 2014 10:12:18 AM io.selendroid.SelendroidLauncher lauchServer
INFO: Starting selendroid-server port 4444
Mar 18, 2014 10:12:18 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\_SOFT\Development\adt-bundle-windows-x86-20131030\sdk\build-tools\android-4.4\aapt.exe remove D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk META-INF/MANIFEST.MF
Mar 18, 2014 10:12:18 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\_SOFT\Development\adt-bundle-windows-x86-20131030\sdk\build-tools\android-4.4\aapt.exe remove D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk META-INF/CERT.RSA
Mar 18, 2014 10:12:18 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\_SOFT\Development\adt-bundle-windows-x86-20131030\sdk\build-tools\android-4.4\aapt.exe remove D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk META-INF/CERT.SF
Mar 18, 2014 10:12:18 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\_SOFT\Development\adt-bundle-windows-x86-20131030\sdk\build-tools\android-4.4\aapt.exe remove D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk META-INF/ANDROIDD.SF
Mar 18, 2014 10:12:18 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\_SOFT\Development\adt-bundle-windows-x86-20131030\sdk\build-tools\android-4.4\aapt.exe remove D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk META-INF/ANDROIDD.RSA
Mar 18, 2014 10:12:18 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.7.0_51\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\_SOFT\Development\Selendroid\resigned-selendroid-test-app-0.8.0.apk -storepass android -keystore C:\Users\Lelik\.android\
debug.keystore D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk androiddebugkey
Mar 18, 2014 10:12:18 AM io.selendroid.SelendroidLauncher lauchServer
SEVERE: Error occurred while building server: An error occurred while resigning the app 'selendroid-test-app-0.8.0.apk'.
io.selendroid.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'selendroid-test-app-0.8.0.apk'.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:125)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:93)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
        at io.selendroid.SelendroidLauncher.lauchServer(SelendroidLauncher.java:67)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:114)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\Program Files\Java\jdk1.7.0_51\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar D:\_SOFT\Development\Selendroid\resigned-selendroid-test-app-0.8.0.apk -storepass android -keystore C:\Users\Lelik\.android\debug.keystore D:\_SOFT\Development\Selendroid\selendroid-test-app-0.8.0.apk androiddebugkey
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:53)
        at io.selendroid.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:274)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:134)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:123)
        ... 5 more
Caused by: io.selendroid.exceptions.ShellCommandException: jarsigner error: java.security.SignatureException: private key algorithm is not compatible with signature algorithm

        ... 9 more
Exception in thread "main" io.selendroid.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'selendroid-test-app-0.8.0.apk'.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:125)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:93)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
        at io.selendroid.SelendroidLauncher.lauchServer(SelendroidLauncher.java:67)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:114)

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
