### ISSUE TITLE
Problem with executeScript

### ISSUE THREAD

**Issue by danielwagner** [selendroid/selendroid#337]
I'm getting an exception whenever I use a WebElement returned by executeScript as an argument for another executeScript call, which works fine in plain WebDriver:

```
WebElement element = (WebElement) driver.executeScript("return document.body;");
driver.executeScript("return arguments[0].tagName", element);
```

Stack trace:

```
Exception in thread "main" org.openqa.selenium.WebDriverException: Error occured while communicating with selendroid server on the device: 
io.selendroid.exceptions.SelendroidException: Error occured while communicating with selendroid server on the device: 
	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:74)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:127)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
	at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 0
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at io.selendroid.server.util.HttpClientUtil.parseJsonResponse(HttpClientUtil.java:57)
	at io.selendroid.server.handler.RequestRedirectHandler.redirectRequest(RequestRedirectHandler.java:121)
	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:64)
	... 17 more
```

I'm using Selendroid 0.8.0 to run tests on a Samsung Galaxy Nexus running Android 4.3.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
