### ISSUE TITLE
Unable to select value when drop down list values are out of screen area

### ISSUE THREAD

**Issue by sreevatsa-ramya** [selendroid/selendroid#353]
There is drop down selection in one of the scripts. Things work fine when the emulator is in portrait mode but when switched to landscape mode, list values are not shown completely and selection fails. The value is the last in the shown list. Check the screenshot and part of console log

![screen shot 2014-03-27 at 8 42 40 am](https://cloud.githubusercontent.com/assets/5677204/2533481/d7f0e02c-b55d-11e3-966a-5719fab5609d.png)

Console log - INFO: Payload? {"using":"xpath","value":"//*[@value='PayPal']"}
Mar 26, 2014 10:03:47 PM io.selendroid.server.handler.RequestRedirectHandler handle
INFO: return value from selendroid android server: {"message":"Element was not found.\nio.selendroid.exceptions.NoSuchElementException: Element was not found.\n\tat io.selendroid.server.handler.FindElement.ha...
Mar 26, 2014 10:03:47 PM io.selendroid.server.handler.CaptureScreenshot handle
INFO: take screenshot command
Mar 26, 2014 10:06:16 PM io.selendroid.server.handler.DeleteSessionHandler handle
INFO: delete session command

**Comment by Ravi0008** [comment]
org.openqa.selenium.support.ui.UnexpectedTagNameException: Element should have been "select" but was "AppCompatEditText"
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'sdl7663', ip: '172.25.14.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:47)
	at Spice_Money.Spice_Money_Sel.test_case_one(Spice_Money_Sel.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

Sep 13, 2017 1:09:17 PM io.selendroid.standalone.SelendroidLauncher$1 run
INFO: Shutting down Selendroid standalone

I'm facing this issue while selecting the value from drop down List.
Could you please help on this.

**Comment by Ravi0008** [comment]
org.openqa.selenium.support.ui.UnexpectedTagNameException: Element should have been "select" but was "AppCompatEditText"
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'sdl7663', ip: '172.25.14.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:47)
	at S_M.S_Sel.test_case_one(S_M_Sel.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

I'm facing the above error, could you please help me on this, how to get it resolved..?

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

Sep 13, 2017 1:09:17 PM io.selendroid.standalone.SelendroidLauncher$1 run
INFO: Shutting down Selendroid standalone
