### ISSUE TITLE
POST /session/:sessionId/touch/longclick throws INJECT_EVENTS permission exception

### ISSUE THREAD

**Issue by csnover** [selendroid/selendroid#372]
selendroid 0.9.0 on Android 19 (4.4) using emulator64-x86

```
UnknownError: Unhandled exception from application under test.
io.selendroid.exceptions.AppCrashedException: Unhandled exception from application under test.
	at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:410)
	at io.selendroid.ServerInstrumentation.sendInputEventSync(ServerInstrumentation.java:396)
	at io.selendroid.ServerInstrumentation.sendPointerSync(ServerInstrumentation.java:373)
	at io.selendroid.android.AndroidTouchScreen.longPress(AndroidTouchScreen.java:143)
	at io.selendroid.server.handler.LongPressOnElement.handle(LongPressOnElement.java:47)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:286)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
	at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.util.concurrent.ExecutionException: io.selendroid.exceptions.SelendroidException: Event injection failed.
	at java.util.concurrent.FutureTask.report(FutureTask.java:93)
	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
	at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:408)
	... 24 more
Caused by: io.selendroid.exceptions.SelendroidException: Event injection failed.
	at io.selendroid.UiThreadController.injectInputEventWaitingForCompletion(UiThreadController.java:71)
	at io.selendroid.ServerInstrumentation$5.run(ServerInstrumentation.java:399)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at java.util.concurrent.FutureTask.report(FutureTask.java:93)
	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
	at io.selendroid.UiThreadController.injectInputEventWaitingForCompletion(UiThreadController.java:69)
	... 12 more
Caused by: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.readException(Parcel.java:1465)
	at android.os.Parcel.readException(Parcel.java:1419)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:356)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:641)
	at android.app.Instrumentation.sendPointerSync(Instrumentation.java:937)
	at io.selendroid.ServerInstrumentation.access$301(ServerInstrumentation.java:43)
	at io.selendroid.ServerInstrumentation$3.sendEvent(ServerInstrumentation.java:377)
	at io.selendroid.UiThreadController$1.call(UiThreadController.java:59)
	at io.selendroid.UiThreadController$1.call(UiThreadController.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

There are no errors in the log for the run indicating that there was a failure signing the package. See https://gist.github.com/csnover/d4d55f9af71a0511866b for the command-line logs. All other events (sendKeys, tap, flick, etc.) work OK, only longclick has this problem. I made sure to test against a freshly created AVD to avoid any problems caused by using an existing AVD.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
