### ISSUE TITLE
Selendroid selenium-webdriver executeScript - UnknownError: {"message":"Parse error"}

### ISSUE THREAD

**Issue by pmudrak** [selendroid/selendroid#374]
<pre>Hi,
I have problem executing simple test script using executeScript function:
var webdriver = require('selenium-webdriver');
var capabilities = webdriver.Capabilities.android().set('emulator', true).set('platformVersion', '13');
var driver = new  webdriver.Builder().usingServer('http://localhost:4444/wd/hub').withCapabilities(capabilities).build();
driver.get("http://www.google.com/");
driver.executeScript("return document.body.innerHTML; //test comment").then(console.log);
driver.quit();
After test script is executed, emulator, SelendroidDriver  Webview App and web browser with web page is started correctly but exception io.selendroid.exceptions.SelendroidException: {"message":"Parse error"} is thrown.
This is caused by “test comment”. Executing script without this comment runs as expected.
My environment:
Windows 7 Enterprise,
Android SDK tools 22.6.2
Android SDK Platform-tools 19.0.1
Java SDK 1.7.0.510
selendroid-standalone-0.9.0-with-dependencies.jar

Full exception:
timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
UnknownError: {"message":"Parse error"}
io.selendroid.exceptions.SelendroidException: {"message":"Parse error"}
        at io.selendroid.server.handler.script.ExecuteScript.handle(ExecuteScript.java:56)
        at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:286)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
        at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
        at java.lang.Thread.run(Thread.java:1020)

    at new bot.Error (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\atoms\error.js:109:18)
    at Object.bot.response.checkResponse (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:276:20
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\goog\base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:1598:20)
    at notify (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:428:12)
    at notifyAll (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:397:7)
    at resolve (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:375:7)
    at fulfill (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:493:5)
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:1465:10
==== async task ====
WebDriver.executeScript()
    at webdriver.WebDriver.schedule (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:267:15)
    at webdriver.WebDriver.executeScript (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:401:15)
    at Object.<anonymous> (c:\dev\sts-workspace\web-test\examples-selenium\pm.js:72:8)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
</pre>

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
