### ISSUE TITLE
Selendroid selenium-webdriver findElement(By.js()) -> getText() throws exception

### ISSUE THREAD

**Issue by pmudrak** [selendroid/selendroid#377]
<pre>Hi,
I have problem executing simple test script that uses function findElement(By.js(...)) 
Example script:
var webdriver = require('selenium-webdriver');
var By = webdriver.By;
var capabilities = webdriver.Capabilities.android()
	.set('emulator', true)
	.set('platformVersion', '13');
var driver = new webdriver.Builder().usingServer('http://localhost:4444/wd/hub').withCapabilities(capabilities).build();
driver.get("http://http://www.w3.org//");
driver.findElement(By.css("h1"))
	.then(logElement); //this works

driver.findElement(By.js("var e = document.getElementsByTagName('h1')[0]; return e;"))
	.then(logElement); //this throws exception
function logElement(e){
	e.getText().then(function(value){
		console.log(value);
	});
}
driver.quit();
------------------------------------------------------------------
Function getText throws following exception:
timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
StaleElementReferenceError: Element with id ':wdc:1396877733364' was not found.
io.selendroid.exceptions.SelendroidException: Element with id ':wdc:1396877733364' was not found.
        at io.selendroid.server.handler.GetText.handle(GetText.java:40)
        at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:286)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
        at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
        at java.lang.Thread.run(Thread.java:1020)

    at new bot.Error (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\atoms\error.js:109:18)
    at Object.bot.response.checkResponse (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:276:20
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\goog\base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:1598:20)
    at notify (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:428:12)
    at notifyAll (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:397:7)
    at resolve (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:375:7)
    at fulfill (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:493:5)
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:1465:10
==== async task ====
WebElement.getText()
    at webdriver.WebDriver.schedule (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:267:15)
    at webdriver.WebElement.schedule_ (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:1609:23)
    at webdriver.WebElement.getText (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:1857:15)
    at logElement (c:\dev\sts-workspace\web-test\examples-selenium\selendroidByJs.js:35:4)
    at c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\goog\base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:1598:20)
    at notify (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:428:12)
    at notifyAll (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:397:7)
    at resolve (c:\dev\sts-workspace\web-test\node_modules\selenium-webdriver\lib\webdriver\promise.js:375:7)
-------------------------------------------------------------------------------------------------------------
My environment:
Windows 7 Enterprise,
Android SDK tools 22.6.2
Android SDK Platform-tools 19.0.1
Java SDK 1.7.0.510
selendroid-standalone-0.9.0-with-dependencies.jar
</pre>

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
