### ISSUE TITLE
Selendroid corrupting the apk?

### ISSUE THREAD

**Issue by tektsu** [selendroid/selendroid#383]
I have an apk, written in Xamarin, which runs fine when installed through adb. When I try to test it using Selendroid, the apk becomes corrupted. The error I see in logcat is below. Notice the reference to zipalign.

Can anyone shed any light on this?

I/ActivityThread(23575): Pub com.tmln.jscan.mono.MonoRuntimeProvider.__mono_init__: mono.MonoRuntimeProvider
D/dalvikvm(23575): Trying to load lib /data/data/com.tmln.jscan/lib/libmonodroid.so 0x40d3c3e8
D/dalvikvm(23575): Added shared lib /data/data/com.tmln.jscan/lib/libmonodroid.so 0x40d3c3e8
F/monodroid-assembly(23575): Assembly 'assemblies/tmln.JACS.jscan.dll' is located at a bad address 0x52108122
F/monodroid-assembly(23575): You MUST run `zipalign` on com.tmln.jscan-1.apk
E/ActivityManager(  254): fail to set top app changed! (2)
E/ActivityManager(  254): java.lang.NullPointerException
E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService.handleTopAppChanged(ActivityManagerService.java:15598)

E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:15035) E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService.updateLruProcessInternalLocked(ActivityManagerService.java:1934)
E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService.updateLruProcessLocked(ActivityManagerService.java:1941)
E/ActivityManager(  254):       at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1513)
E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:2990) E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3069)
E/ActivityManager(  254):       at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:908)
E/ActivityManager(  254):       at android.os.BinderProxy.sendDeathNotice(Binder.java:417)
E/ActivityManager(  254):       at dalvik.system.NativeStart.run(Native Method)
I/ActivityManager(  254): Process com.tmln.jscan (pid 23575) has died.
4):       at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:908)
E/ActivityManager(  254):       at android.os.BinderProxy.sendDeathNotice(Binder.java:417)
E/ActivityManager(  254):       at dalvik.system.NativeStart.run(Native Method)
I/ActivityManager(  254): Process com.ticketmaster.jacscanner (pid 23575) has died.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
