### ISSUE TITLE
selendroid does not start selendroid-server on device (INSTRUMENTATION_FAILED )

### ISSUE THREAD

**Issue by mgehlen** [selendroid/selendroid#417]
Hello all,

I am trying to use selendroid to test an Android apk, which I receive from a supplier.

Previously I used selenium on the selendroid testapp, an app from another supplier and a mobile website.
So I hope I do not have general settings issues ... at least I do not find them myself at this point anymore. ;-)

The app I want to test now simply does not start and throws me the following error:

Mai 26, 2014 2:30:03 PM io.selendroid.server.handler.CreateSessionHandler handle
Schwerwiegend: Error while creating new session: Error occurred while starting selendroid-server on the device
io.selendroid.exceptions.SelendroidException: Error occurred while starting selendroid-server on the device
        at io.selendroid.android.impl.AbstractDevice.startSelendroid(AbstractDevice.java:235)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:290)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:142)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
        at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
        at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
        at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Throwable: android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.de.myapp.client.android/io.selendroid.ServerInstrumentation
        at com.android.commands.am.Am.runInstrument(Am.java:802)
        at com.android.commands.am.Am.onRun(Am.java:242)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:75)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:297)
        at dalvik.system.NativeStart.main(Native Method)

Details:
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: de.myapp.client.android
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid.de.myapp.client.android/io.selendroid.ServerInstrumentation
        at com.android.commands.am.Am.runInstrument(Am.java:802)
        at com.android.commands.am.Am.onRun(Am.java:242)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:75)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:297)
        at dalvik.system.NativeStart.main(Native Method)
        ... 20 more

The Java Code is quite rudimentary at this point as you can imagine:

  @Test(enabled=true)
  public void testMXonAndroid() throws Exception {
	  
	  SelendroidCapabilities capa = new SelendroidCapabilities() ;
	  
	  capa.setAut("de.myapp.client.android:4.3.1");
	  capa.setEmulator(false);
	  WebDriver driver = new SelendroidDriver(capa);
	  
	  driver.quit() ;
  }

The aut is taken from http://localhost:4444/wd/hub/status:

{"status":0,"value":{"supportedApps":[{"appId":"io.selendroid.androiddriver:0.10.0","mainActivity":"io.selendroid.androiddriver.WebViewActivity","basePackage":"io.selendroid.androiddriver"},{"appId":"de.myapp.client.android:4.3.1","mainActivity":"de.payback.client.android.controller.activity.SplashActivity","basePackage":"de.payback.client.android"}],"os":{"arch":"amd64","name":"Windows 7","version":"6.1"},"build":{"browserName":"selendroid","version":"0.10.0"},"supportedDevices":[{"screenSize":"WQVGA400","platformVersion":"19","emulator":true,"avdName":"Nexus5"},{"screenSize":"800x1280","platformVersion":"19","emulator":true,"avdName":"Nexus7NSE_Emulator"},{"screenSize":"1280x720","platformVersion":"18","model":"GT-I9300","emulator":false},{"screenSize":"1280x720","platformVersion":"18","model":"GT-I9300","emulator":false},{"screenSize":"1280x720","platformVersion":"18","model":"GT-I9300","emulator":false}]}}  

Strange thing is that adb lists the app as instrumented:

C:\Projekte\Mobile\Android\sdk\sdk\platform-tools>adb shell pm list instrumentation
instrumentation:io.selendroid.de.myapp.client.android/io.selendroid.ServerInstrumentation (target=de.myapp.client.android)
instrumentation:io.selendroid.io.selendroid.androiddriver/io.selendroid.ServerInstrumentation (target=io.selendroid.androiddriver)

I also find an exception in the adb-log, which I do not find for the sucessfully tested apps:

--------- beginning of /dev/log/system
I/PackageManager( 2346): Copying native libraries to /data/app-lib/vmdl738428305
D/dalvikvm( 2346): GC_CONCURRENT freed 1595K, 17% free 42238K/50728K, paused 4ms+8ms, total 122ms
D/dalvikvm( 2346): WAIT_FOR_CONCURRENT_GC blocked 106ms
W/PackageParser( 2346): Exception reading assets/ADBMobileConfig.json in /data/app/vmdl738428305.tmp
W/PackageParser( 2346): java.lang.SecurityException: /data/app/vmdl738428305.tmp failed verification of META-INF/MYAPP.SF
W/PackageParser( 2346): 	at java.util.jar.JarVerifier.failedVerification(JarVerifier.java:146)
W/PackageParser( 2346): 	at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:341)
W/PackageParser( 2346): 	at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:263)
W/PackageParser( 2346): 	at java.util.jar.JarFile.getInputStream(JarFile.java:379)
W/PackageParser( 2346): 	at android.content.pm.PackageParser.loadCertificates(PackageParser.java:466)
W/PackageParser( 2346): 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:678)
W/PackageParser( 2346): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:10691)
W/PackageParser( 2346): 	at com.android.server.pm.PackageManagerService.access$2000(PackageManagerService.java:218)
W/PackageParser( 2346): 	at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:8456)
W/PackageParser( 2346): 	at android.os.Handler.handleCallback(Handler.java:730)
W/PackageParser( 2346): 	at android.os.Handler.dispatchMessage(Handler.java:92)
W/PackageParser( 2346): 	at android.os.Looper.loop(Looper.java:176)
W/PackageParser( 2346): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/PackageParser( 2346): Package de.myapp.client.android has no certificates at entry assets/ADBMobileConfig.json; ignoring!
D/dalvikvm( 2346): GC_CONCURRENT freed 1066K, 15% free 43220K/50728K, paused 4ms+9ms, total 144ms
D/dalvikvm( 2346): WAIT_FOR_CONCURRENT_GC blocked 120ms
D/dalvikvm( 2346): GC_EXPLICIT freed 391K, 16% free 42830K/50728K, paused 4ms+15ms, total 129ms
D/AndroidRuntime(20039): Shutting down VM
D/dalvikvm(20039): GC_CONCURRENT freed 126K, 16% free 687K/816K, paused 0ms+1ms, total 2ms
D/STATUSBAR-NetworkController( 2586): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 2586): checkOverflow(336), More:false, Req:false Child:1
D/STATUSBAR-NetworkController( 2586): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 2586): checkOverflow(336), More:false, Req:false Child:1
D/AndroidRuntime(20055): 
D/AndroidRuntime(20055): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime(20055): CheckJNI is OFF
D/AndroidRuntime(20055): setted country_code = Germany
D/AndroidRuntime(20055): setted countryiso_code = DE
D/AndroidRuntime(20055): setted sales_code = VD2
D/AndroidRuntime(20055): readGMSProperty: start
D/AndroidRuntime(20055): readGMSProperty: already setted!!
D/AndroidRuntime(20055): readGMSProperty: end
D/AndroidRuntime(20055): addProductProperty: start
D/dalvikvm(20055): Trying to load lib libjavacore.so 0x0
D/dalvikvm(20055): Added shared lib libjavacore.so 0x0
D/dalvikvm(20055): Trying to load lib libnativehelper.so 0x0
D/dalvikvm(20055): Added shared lib libnativehelper.so 0x0
D/SSRMv2:Monitor( 2346): SIOP:: AP = 360 (read only)
D/dalvikvm(20055): Note: class Landroid/app/ActivityManagerNative; has 177 unimplemented (abstract) methods
D/AndroidRuntime(20055): Calling main entry com.android.commands.pm.Pm
D/SensorService( 2346):   -0.0 0.1 10.0
E/Parcel  (20055): Reading a NULL string not supported here.
D/AndroidRuntime(20055): Shutting down VM
D/dalvikvm(20055): GC_CONCURRENT freed 525K, 44% free 699K/1228K, paused 0ms+0ms, total 4ms
D/AndroidRuntime(20069): 
D/AndroidRuntime(20069): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime(20069): CheckJNI is OFF
D/AndroidRuntime(20069): setted country_code = Germany
D/AndroidRuntime(20069): setted countryiso_code = DE
D/AndroidRuntime(20069): setted sales_code = VD2
D/AndroidRuntime(20069): readGMSProperty: start
D/AndroidRuntime(20069): readGMSProperty: already setted!!
D/AndroidRuntime(20069): readGMSProperty: end
D/AndroidRuntime(20069): addProductProperty: start
D/dalvikvm(20069): Trying to load lib libjavacore.so 0x0
D/dalvikvm(20069): Added shared lib libjavacore.so 0x0
D/dalvikvm(20069): Trying to load lib libnativehelper.so 0x0
D/dalvikvm(20069): Added shared lib libnativehelper.so 0x0
D/dalvikvm(20069): Note: class Landroid/app/ActivityManagerNative; has 177 unimplemented (abstract) methods
D/AndroidRuntime(20069): Calling main entry com.android.commands.am.Am
W/ActivityManager( 2346): Unable to find instrumentation target package: de.myapp.client.android
I/AndroidRuntime(20069): VM exiting with result code 1.
D/AndroidRuntime(20081): 
D/AndroidRuntime(20081): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<

I searched this site and googled in general, but did not find a solution, that helped me.
Sadly I have single to no influence on how the app is build at the moment (we are working on this).

Do you guys have any idea?

Thank you very much,

  mgehlen

**Comment by mgehlen** [comment]
Hello all,

as stated in my last post that the problem on my site was in our App. In the meantime the supplier has fixed the issue and I can access the App with Appium and Selendroid. Both identification in test code and the respective inspectors work well.

I also see that @DominikDary did improve the clean up strategy in SelendroidSeverBuilder.java by adding the missing Android files like .SF and .RSA and this is the only possible issue we found in Selendroid connected to the INSTRUMENTATION_FAILED app.

So from my point of view this issue can be closed if @DominikDary or somebody else does not want to use it for something else. 

Best regards,

  mgehlen

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
