### ISSUE TITLE
Selenium grid+ Selendriod  - Exception "Error forwarding the new session "

### ISSUE THREAD

**Issue by DenZie** [selendroid/selendroid#424]
I am following the documentation http://selendroid.io/scale.html .
All the set up goes well, but when I execute the sample java code provided I am getting ht exception. Pasted below.

I could see the 

Exception in thread "main" org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request null
Command duration or timeout: 17.08 seconds
Build info: version: '2.40.0', revision: '4c5c0568b004f67810ee41c459549aa4b09c651e', time: '2014-02-19 11:13:01'
System info: host: 'PC292708', ip: '172.20.33.51', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_25'
Driver info: io.selendroid.SelendroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:113)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:61)

Also pasting snippet from the selendriod-server log.

May 29, 2014 2:10:35 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
SEVERE: Error getting status: java.net.SocketException: Connection reset
May 29, 2014 2:10:37 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: using url: http://localhost:8080/wd/hub/status
May 29, 2014 2:10:38 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: got response status code: 200
May 29, 2014 2:10:38 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: got response value: {"value":{"supportedApps":[],"build":{"browserName":"selendroid","version":"0.10.0"},"os":{"arch":"armeabi-v7a","version":"19","name":"Android"},"supportedDevices":[]},"status":0}
new Session URL: http://localhost:4444/wd/hub/session/670ee25c-1dfa-4e77-c6b5-c4a92afbb283

**Comment by ShailBag** [comment]
Hi

I'm getting same error. How to resolve this?

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
