### ISSUE TITLE
Cannot run .jar file 

### ISSUE THREAD

**Issue by a-shynkevich** [selendroid/selendroid#431]
When I try run my project as .jar file an exception appears but when I run the project in IDEA it's work correctly.

Logs:
ш■э 06, 2014 4:41:03 PM io.selendroid.SelendroidLauncher lauchServer
INFO: Starting selendroid-server port 4444
ш■э 06, 2014 4:41:03 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe remove e:\Automatisation\Apk's\Browser.apk META-INF/MANIFEST
.MF
ш■э 06, 2014 4:41:03 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe remove e:\Automatisation\Apk's\Browser.apk META-INF/CERT.RSA

ш■э 06, 2014 4:41:03 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe remove e:\Automatisation\Apk's\Browser.apk META-INF/CERT.SF
ш■э 06, 2014 4:41:03 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe remove e:\Automatisation\Apk's\Browser.apk META-INF/ANDROIDD
.SF
ш■э 06, 2014 4:41:03 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe remove e:\Automatisation\Apk's\Browser.apk META-INF/ANDROIDD
.RSA
ш■э 06, 2014 4:41:03 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\Program Files\Java\jdk1.7.0_51\bin\jarsigner.exe -si
galg MD5withRSA -digestalg SHA1 -signedjar e:\Automatisation\Apk's\resigned-Brow
ser.apk -storepass android -keystore C:\Users\Alecs.android\debug.keystore e:\A
utomatisation\Apk's\Browser.apk androiddebugkey
ш■э 06, 2014 4:41:04 PM io.selendroid.builder.SelendroidServerBuilder signTestSe
rver
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a times
tamp, users may not be able to validate this jar after the signer certificate's
expiration date (2015-06-02) or after any future revocation date.

ш■э 06, 2014 4:41:04 PM io.selendroid.builder.SelendroidServerBuilder signTestSe
rver
INFO: The app has been signed: e:\Automatisation\Apk's\resigned-Browser.apk
ш■э 06, 2014 4:41:04 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe dump badging e:\Automatisation\Apk's\resigned-Browser.apk
ш■э 06, 2014 4:41:04 PM io.selendroid.io.ShellCommand exec
INFO: executing command: c:\adt-bundle-windows-x86_64-20130911\sdk\build-tools\a
ndroid-4.3\aapt.exe dump badging e:\Automatisation\Apk's\resigned-Browser.apk
ш■э 06, 2014 4:41:04 PM io.selendroid.server.model.SelendroidStandaloneDriver in
itApplicationsUnderTest
INFO: App com.softteco.browser:1.0 has been added to selendroid standalone serve
r.
ш■э 06, 2014 4:41:04 PM io.selendroid.SelendroidLauncher lauchServer
SEVERE: Error occurred while building server: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:144)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(Selendro
idStandaloneDriver.java:82)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidS
erver(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStan
daloneServer.java:65)
        at io.selendroid.SelendroidLauncher.lauchServer(SelendroidLauncher.java:
67)
        at io.selendroid.SelendroidLauncher.lauchSelendroid(SelendroidLauncher.j
ava:90)
        at by.shynkevich.selendroid.MobileTest.startSelendroidServer(MobileTest.
java:26)
        at by.shynkevich.selendroid.MobileTest.main(MobileTest.java:58)
Caused by: java.lang.NullPointerException
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1488)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1465)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1440)
        at io.selendroid.builder.AndroidDriverAPKBuilder.extractAndroidDriverAPK
(AndroidDriverAPKBuilder.java:33)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:140)
        ... 7 more
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerExce
ption
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:144)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(Selendro
idStandaloneDriver.java:82)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidS
erver(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStan
daloneServer.java:65)
        at io.selendroid.SelendroidLauncher.lauchServer(SelendroidLauncher.java:
67)
        at io.selendroid.SelendroidLauncher.lauchSelendroid(SelendroidLauncher.j
ava:90)
        at by.shynkevich.selendroid.MobileTest.startSelendroidServer(MobileTest.
java:26)
        at by.shynkevich.selendroid.MobileTest.main(MobileTest.java:58)
Caused by: java.lang.NullPointerException
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1488)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1465)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1440)
        at io.selendroid.builder.AndroidDriverAPKBuilder.extractAndroidDriverAPK
(AndroidDriverAPKBuilder.java:33)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplication
sUnderTest(SelendroidStandaloneDriver.java:140)
        ... 7 more

**Comment by wa1one** [comment]
I fixed just by added Version : 0-18-1 to MANIFEST.MF 
That's not great deal
