### ISSUE TITLE
Error when trying to start standalone server with APK

### ISSUE THREAD

**Issue by subeeshb** [selendroid/selendroid#47]
A 'Severe' error occurs when the standalone server tries to resign the APK file. No details of the error are displayed. The output is attached below.

I've verified that the ANDROID_HOME environment variable is set.

Jun 5, 2013 11:09:46 AM io.selendroid.SelendroidLauncher main
INFO: ################# Selendroid #################
Jun 5, 2013 11:09:46 AM io.selendroid.SelendroidLauncher lauchSelendroid
INFO: Starting selendroid-server port 5555
Jun 5, 2013 11:09:46 AM io.selendroid.io.ShellCommand exec
INFO: executing command: /usr/libexec/java_home -v 1.7/bin/jarsigner -sigalg MD5withRSA -digestalg SHA1 -signedjar /Users/scb/Downloads/resigned-HelloWorld.apk -storepass android -keystore /Users/scb/.android/debug.keystore /Users/scb/Downloads/HelloWorld.apk androiddebugkey
Jun 5, 2013 11:09:46 AM io.selendroid.SelendroidLauncher lauchSelendroid
SEVERE: Error occured while building server: An error occured while resigning the app 'HelloWorld.apk'. 
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.3', java.version: '1.6.0_45'
Driver info: driver.version: SelendroidStandaloneDriver

**Comment by holybible934** [comment]
Hi there,
I am also encountering the same problem with SelendroidServer 0.17.0 as well. 
There is no problem to sign my application by executing jarsigner.exe manually; however, it failed when running selendroid-standalone-0.17.0-with-dependencies.jar
 
The error trace says it failed at SelendroidServerBuilder.java Line#296, and it is `commandline.addArgument("SHA1", false);`

Here is my log
==  
2 02, 2016 10:05:44 午前 io.selendroid.standalone.io.ShellCommand exec
情報: Executing shell command: C:\java\jdk-1.8.72\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar c:\automation\ios_appium_junit\selendroid_server\resigned-AndroidReader-japan-release.apk -storepass android -keystore C:\Users\xxxx\.android\debug.keystore c:\automation\ios_appium_junit\selendroid_server\AndroidReader-japan-release.apk androiddebugkey
2 02, 2016 10:06:04 午前 io.selendroid.standalone.io.ShellCommand exec
重大: Error executing command: C:\java\jdk-1.8.72\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar c:\automation\ios_appium_junit\selendroid_server\resigned-AndroidReader-japan-release.apk -storepass android -keystore C:\Users\xxxx\.android\debug.keystore c:\automation\ios_appium_junit\selendroid_server\AndroidReader-japan-release.apk androiddebugkey
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:296)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:154)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

**Comment by holybible934** [comment]
OK, I found my problem is caused by JDK 1.8.0_72, while JDK 1.8.0_71 can sign my app correctly.
