### ISSUE TITLE
I getting server error i tried everything but not able to solved

### ISSUE THREAD

**Issue by krunal8191** [selendroid/selendroid#470]
io.selendroid.SelendroidConfiguration@b1074a[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
]
8 Jul, 2014 3:15:39 PM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
8 Jul, 2014 3:15:39 PM io.selendroid.SelendroidLauncher launchServer
SEVERE: Error occurred while building server: io.selendroid.exceptions.SelendroidException: Environment variable 'ANDROID_HOME' was not found!
java.lang.RuntimeException: io.selendroid.exceptions.SelendroidException: Environment variable 'ANDROID_HOME' was not found!
    at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:142)
    at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:80)
    at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
    at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
    at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:49)
    at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:105)
Caused by: io.selendroid.exceptions.SelendroidException: Environment variable 'ANDROID_HOME' was not found!
    at io.selendroid.android.AndroidSdk.androidHome(AndroidSdk.java:97)
    at io.selendroid.android.AndroidSdk.platformToolsHome(AndroidSdk.java:86)
    at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:39)
    at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:102)
    at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:116)
    at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:125)
    at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:138)
    ... 5 more
Exception in thread "main" java.lang.RuntimeException: io.selendroid.exceptions.SelendroidException: Environment variable 'ANDROID_HOME' was not found!
    at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:142)
    at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:80)
    at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
    at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
    at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:49)
    at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:105)
Caused by: io.selendroid.exceptions.SelendroidException: Environment variable 'ANDROID_HOME' was not found!
    at io.selendroid.android.AndroidSdk.androidHome(AndroidSdk.java:97)
    at io.selendroid.android.AndroidSdk.platformToolsHome(AndroidSdk.java:86)
    at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:39)
    at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:102)
    at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:116)
    at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:125)
    at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:138)
    ... 5 more

**Comment by tinashec** [comment]
For those on Windows, use the command below to set your JAVA_HOME variable:
`setx -m JAVA_HOME "C:\Progra~1\Java\jdk1.8.0_XX"`

Note: if you have the jre and jdk in the same location, remove the jre
