### ISSUE TITLE
isElementDisplayedInViewport reporting inaccurate results

### ISSUE THREAD

**Issue by EliseLebeau** [selendroid/selendroid#471]
Since isVisible is not working, we use this workaround (provided by Dominik) to check if an element is visible:
         WebElement element = driver.findElement(By.partialLinkText(label));
         condition = (Boolean) driver.executeScript("isElementDisplayedInViewport", element);
         Assert.assertTrue(condition);
 
We inaccurate results when using this method.
Any idea what's happening? How can we debug this?

For example:
[testng] java.lang.AssertionError: Could not find label Watch
   [testng] 	at com.ebay.mobile.qa.utilities.AssertionUtilities.assertElementLabelIsDisplayed(AssertionUtilities.java:47)
   [testng] 	at com.ebay.mobile.qa.activities.ItemView.validateWatchExists(ItemView.java:283)

But screenshot shows it's there:
![screen shot 2014-07-08 at 10 58 40 am](https://cloud.githubusercontent.com/assets/2006651/3514158/a594ada8-06c9-11e4-9ca3-88101c2cd886.png)

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
