### ISSUE TITLE
App crashes : Permission denied: injecting event 

### ISSUE THREAD

**Issue by sukoneru** [selendroid/selendroid#481]
Hi Dominik,
 
 I have created a test suite which works fine when I execute the tests independently. But fails(INJECT_EVENTS permission) almost 95% of time when I kick off the suite pointing to a selendroid grid. 

Any suggestion will be great.
```
Error noticed in the window where the selendroid server is running:-
====================================================
 I/appLifecycle(24586): com.ebay.mobile.sell.ListingFragmentActivity.onPause() - ListingFragmentActivity.java:355
I/appLifecycle(24586): com.ebay.mobile.search.MainSearchActivity.onDestroy() - com.ebay.nautilus.shell.app.BaseActivity
I/appLifecycle(24586): com.ebay.mobile.activities.eBay.onDestroy() - eBay.java:855
I/appLifecycle(24586): com.ebay.mobile.itemview.ItemViewActivity.onDestroy() - ItemViewActivity.java:1264
D/AndroidRuntime(24721): 
D/AndroidRuntime(24721): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime(24721): CheckJNI is OFF
I/Choreographer(  515): Skipped 66 frames!  The application may be doing too much work on its main thread.
W/InputDispatcher(  258): Permission denied: injecting event from pid 24586 uid 10067 to window Window{4199a488 com.android.launcher/com.android.launcher2.Launcher paused=false} owned by uid 10027
W/InputManager(  258): Input event injection from pid 24586 permission denied.
D/AndroidRuntime(24721): Calling main entry com.android.commands.am.Am
I/ActivityManager(  258): Force stopping package com.ebay.mobile uid=10067
I/ActivityManager(  258): Killing proc 24586:com.ebay.mobile/u0a67: force stop
W/ActivityManager(  258): Crash of app com.ebay.mobile running instrumentation ComponentInfo{io.selendroid.com.ebay.mobile/io.selendroid.ServerInstrumentation}
I/ActivityManager(  258): Force stopping package com.ebay.mobile uid=10067
D/AndroidRuntime(24721): Shutting down VM
I/AndroidRuntime(24721): NOTE: attach of thread 'Binder_1' failed
I/WindowState(  258): WIN DEATH: Window{41f58838 com.ebay.mobile/com.ebay.mobile.sell.ListingFragmentActivity paused=false}
I/LocationManagerService(  258): remove network (pid 258), next minTime = 86400000
Jul 15, 2014 10:07:31 AM io.selendroid.server.handler.DeleteSessionHandler handle
INFO: delete session command
Jul 15, 2014 10:07:31 AM io.selendroid.server.handler.CreateSessionHandler handle


Test failed with below exception:-
=========================

Failed tests: 
  DeferredSellerRegistration.testReviseItem:316 Test case testReviseItem failedUnhandled exception from application under test.
io.selendroid.exceptions.AppCrashedException: Unhandled exception from application under test.
	at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:402)
	at io.selendroid.ServerInstrumentation.sendInputEventSync(ServerInstrumentation.java:389)
	at io.selendroid.ServerInstrumentation.sendKeySync(ServerInstrumentation.java:360)
	at android.app.Instrumentation.sendStringSync(Instrumentation.java:848)
	at io.selendroid.android.InstrumentedKeySender.send(InstrumentedKeySender.java:104)
	at io.selendroid.server.model.AndroidNativeElement.send(AndroidNativeElement.java:257)
	at io.selendroid.server.model.AndroidNativeElement.enterText(AndroidNativeElement.java:160)
	at io.selendroid.server.handler.SendKeys.handle(SendKeys.java:52)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:290)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at io.selendroid.server.inspector.InspectorServlet.handleHttpRequest(InspectorServlet.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.PathMatchHandler.handleHttpRequest(PathMatchHandler.java:33)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.DateHeaderHandler.handleHttpRequest(DateHeaderHandler.java:21)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:62)
	at org.webbitserver.handler.ServerHeaderHandler.handleHttpRequest(ServerHeaderHandler.java:25)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:78)
	at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.java:67)
	at org.webbitserver.netty.NettyHttpChannelHandler$2.run(NettyHttpChannelHandler.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.util.concurrent.ExecutionException: io.selendroid.exceptions.SelendroidException: Event injection failed.
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
	at java.util.concurrent.FutureTask.get(FutureTask.java:82)
	at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:400)
	... 27 more
Caused by: io.selendroid.exceptions.SelendroidException: Event injection failed.
	at io.selendroid.UiThreadController.injectInputEventWaitingForCompletion(UiThreadController.java:71)
	at io.selendroid.ServerInstrumentation$5.run(ServerInstrumentation.java:391)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:223)
	at java.util.concurrent.FutureTask.get(FutureTask.java:82)
	at io.selendroid.UiThreadController.injectInputEventWaitingForCompletion(UiThreadController.java:69)
	... 13 more
Caused by: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.readException(Parcel.java:1425)
	at android.os.Parcel.readException(Parcel.java:1379)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:356)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:619)
	at android.app.Instrumentation.sendKeySync(Instrumentation.java:886)
	at io.selendroid.ServerInstrumentation.access$201(ServerInstrumentation.java:43)
	at io.selendroid.ServerInstrumentation$2.sendEvent(ServerInstrumentation.java:363)
	at io.selendroid.UiThreadController$1.call(UiThreadController.java:59)
	at io.selendroid.UiThreadController$1.call(UiThreadController.java:56)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)
```

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
