### ISSUE TITLE
Getting "AppCrashedException" when trying to interact with elements

### ISSUE THREAD

**Issue by amnsi** [selendroid/selendroid#527]
Hello....I am pretty new to Selendroid....I am receiving "AppCrashedException" when trying to interact with any of the elements....whether it is a text box or a button....When I am clicking a button using click() method or typing something into a text box using sendKeys() method,I get this error message.....

Following are the details:

Sample test app--->selendroid-test-app-0.11.0.apk
Selendroid standalone jar--->selendroid-standalone-0.11.0-with-dependencies.jar
Selendroid client jar--->selendroid-client-0.10.0.jar

Following is the code that is giving the problem:

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import io.selendroid.SelendroidCapabilities;
import io.selendroid.SelendroidDriver;

public class DummyClass1{

```
public static void main(String[] args) throws Exception {

    SelendroidCapabilities capa=new SelendroidCapabilities("io.selendroid.testapp:0.11.0");
    WebDriver ob=new SelendroidDriver(capa);
    ob.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    ob.findElement(By.id("visibleButtonTest")).click();

}
```

}

Following is the error message that I am getting:

Exception in thread "main" org.openqa.selenium.WebDriverException: Unhandled exception from application under test.
io.selendroid.exceptions.AppCrashedException: Unhandled exception from application under test.
    at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:412)
    at io.selendroid.ServerInstrumentation.sendInputEventSync(ServerInstrumentation.java:399)
    at io.selendroid.ServerInstrumentation.sendPointerSync(ServerInstrumentation.java:380)
    at io.selendroid.server.model.AndroidNativeElement.clickOnScreen(AndroidNativeElement.java:207)
    at io.selendroid.server.model.AndroidNativeElement.click(AndroidNativeElement.java:194)
    at io.selendroid.server.handler.ClickElement.handle(ClickElement.java:43)
    at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:301)
    at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
    at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: This message cannot be recycled because it is still in use.
    at java.util.concurrent.FutureTask.report(FutureTask.java:93)
    at java.util.concurrent.FutureTask.get(FutureTask.java:163)
    at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:410)
    ... 26 more
Caused by: java.lang.IllegalStateException: This message cannot be recycled because it is still in use.
    at android.os.Message.recycle(Message.java:261)
    at io.selendroid.UiThreadController.loopUiThreadUntilInjectionComplete(UiThreadController.java:96)
    at io.selendroid.UiThreadController.injectInputEventWaitingForCompletion(UiThreadController.java:66)
    at io.selendroid.ServerInstrumentation$5.run(ServerInstrumentation.java:401)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.Handler.handleCallback(Handler.java:738)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5070)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)

Command duration or timeout: 590 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Amneet', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: 7b1c6587-d11f-1436-aa4c-1fdfba1eb6a2
Driver info: io.selendroid.SelendroidDriver
Capabilities [{automationName=selendroid, platformVersion=20, platform=ANDROID, javascriptEnabled=true, acceptSslCerts=true, platformName=android, browserName=selendroid, handlesAlerts=true, networkConnectionEnabled=true, rotatable=true, takesScreenshot=true, version=0.11.0}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
    at DummyClass1.main(DummyClass1.java:28)
Caused by: io.selendroid.exceptions.AppCrashedException: Unhandled exception from application under test.
io.selendroid.exceptions.AppCrashedException: Unhandled exception from application under test.
    at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:412)
    at io.selendroid.ServerInstrumentation.sendInputEventSync(ServerInstrumentation.java:399)
    at io.selendroid.ServerInstrumentation.sendPointerSync(ServerInstrumentation.java:380)
    at io.selendroid.server.model.AndroidNativeElement.clickOnScreen(AndroidNativeElement.java:207)
    at io.selendroid.server.model.AndroidNativeElement.click(AndroidNativeElement.java:194)
    at io.selendroid.server.handler.ClickElement.handle(ClickElement.java:43)
    at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:301)
    at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
    at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: This message cannot be recycled because it is still in use.
    at java.util.concurrent.FutureTask.report(FutureTask.java:93)
    at java.util.concurrent.FutureTask.get(FutureTask.java:163)
    at io.selendroid.ServerInstrumentation.runSynchronouslyOnUiThread(ServerInstrumentation.java:410)
    ... 26 more
Caused by: java.lang.IllegalStateException: This message cannot be recycled because it is still in use.
    at android.os.Message.recycle(Message.java:261)
    at io.selendroid.UiThreadController.loopUiThreadUntilInjectionComplete(UiThreadController.java:96)
    at io.selendroid.UiThreadController.injectInputEventWaitingForCompletion(UiThreadController.java:66)
    at io.selendroid.ServerInstrumentation$5.run(ServerInstrumentation.java:401)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.Handler.handleCallback(Handler.java:738)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5070)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)

Can anyone please figure out why this is happening>

**Comment by 5654566** [comment]
I am also facing the same issue.
