### ISSUE TITLE
selendroid shell crashes, NoMethodError: undefined method 'retriable' for main:Object

### ISSUE THREAD

**Issue by probonopd** [selendroid/selendroid#531]
When trying to run selendroid shell, I get:
```
android.util.AndroidException: INSTRUMENTATION_FAILED: io.selendroid/io.selendroid.ServerInstrumentation
	at com.android.commands.am.Am.runInstrument(Am.java:586)
	at com.android.commands.am.Am.run(Am.java:117)
	at com.android.commands.am.Am.main(Am.java:80)
	at com.android.internal.os.RuntimeInit.finishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:238)
	at dalvik.system.NativeStart.main(Native Method)
load error: /var/lib/gems/1.9.1/gems/selendroid-0.4.0/bin/../irbrc
NoMethodError: undefined method `retriable' for main:Object
	/var/lib/gems/1.9.1/gems/selendroid-0.4.0/lib/selendroid/selendroid_driver.rb:94:in `wait_for_selendroid_server'
	/var/lib/gems/1.9.1/gems/selendroid-0.4.0/irbrc:21:in `<top (required)>'
	/usr/lib/ruby/1.9.1/irb/init.rb:236:in `load'
	/usr/lib/ruby/1.9.1/irb/init.rb:236:in `run_config'
	/usr/lib/ruby/1.9.1/irb/init.rb:19:in `setup'
irb(main):001:0> 
```

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
