### ISSUE TITLE
Selendroid 0.11.0 Couldn't find AAPT eventhough path and other settings were correct.

### ISSUE THREAD

**Issue by krishnamvb** [selendroid/selendroid#538]
Sorry for reposting this, but I am stuck with it here. I referred
https://github.com/selendroid/selendroid/issues/66 as well as https://github.com/selendroid/selendroid/issues/198 but still i am nowhere close to a solution. 

C:\Users\automation>echo %ANDROID_HOME%
D:\android-sdk-windows;D:\android-sdk-windows\build-tools;D:\android-sdk-windows\platform-tools;D:\android-sdk-windows\tools;

C:\Users\automation>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_05

D:\AppiumForWindows>java -jar selendroid-standalone-0.11.0-with-dependencies.jar
###### ########### Configuration in use

io.selendroid.SelendroidConfiguration@2f2c9b19[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
]
Aug 21, 2014 8:03:01 PM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Aug 21, 2014 8:03:01 PM io.selendroid.SelendroidLauncher launchServer
SEVERE: Error occurred while building server: io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
java.lang.RuntimeException: io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:142)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:80)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:49)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:105)
Caused by: io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
        at io.selendroid.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
        at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:47)
        at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:102)
        at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:116)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:125)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:138)
        ... 5 more
Exception in thread "main" java.lang.RuntimeException: io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:142)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:80)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:49)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:105)
Caused by: io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
        at io.selendroid.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
        at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:47)
        at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:102)
        at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:116)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:125)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:138)
        ... 5 more

I din't understand why it is trying to resign app > SelendroidStandaloneDriver.java:142 
http://grepcode.com/file/repo1.maven.org/maven2/io.selendroid/selendroid-standalone/0.10.0/io/selendroid/server/model/SelendroidStandaloneDriver.java/#142

And when i use a -app with that command - 
D:\AppiumForWindows>java -jar selendroid-standalone-0.11.0-with-dependencies.jar -app selendroid-test-app-0.10.0.apk
###### ########### Configuration in use

io.selendroid.SelendroidConfiguration@2f2c9b19[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[selendroid-test-app-0.10.0.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
]
Aug 21, 2014 8:23:54 PM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Aug 21, 2014 8:23:54 PM io.selendroid.SelendroidLauncher launchServer
SEVERE: Error occurred while building server: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
        at io.selendroid.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
        at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:47)
        at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:102)
        at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:116)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:125)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:110)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:80)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:49)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:105)
Exception in thread "main" io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
        at io.selendroid.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
        at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:47)
        at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:102)
        at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:116)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:125)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:110)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:80)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:91)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:65)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:49)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:105)

I am connected to a real device and adb devices is showing me device id as well.

**Comment by stc2020plus** [comment]
You guys are awesome.. this solved problem to me aswell.

**Comment by satyaattili** [comment]
Thanks krishnamvb... 
The semi-colon irritated me.

**Comment by TrueBlueDrive** [comment]
how this issue gt resolved?

**Comment by satyaattili** [comment]
in my case, simply i removed semi-colon at the end of ANDROID_HOME path. it worked.
