### ISSUE TITLE
Could not install selendroid-server on device using 0.12.0-SNAPSHOT and error resigning apk

### ISSUE THREAD

**Issue by axelbarfod** [selendroid/selendroid#634]
Hi Guys,

I download 0.12.0-SNAPSHOT to use the new commands for the custom keystore (-keystorePassword, -keystoreAlias). I tried it on an apk which in which the password for the keystorepassword and storepassword where
the same and it worked. But I'm getting the following problem:
```
oct 07, 2014 11:39:22 AM io.selendroid.SelendroidLauncher launchServer
INFORMACIÓN: Starting selendroid-server port 4444
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/MANIFEST.MF
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/CERT.RSA
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/CERT.SF
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/ANDROIDD.SF
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/ANDROIDD.RSA
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/NDKEYSTO.SF
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk META-INF/NDKEYSTO.RSA
oct 07, 2014 11:39:22 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Program Files\Java\jdk1.6.0_45\bin\jarsigner.exe -sigalg SHA256withRSA -digestalg SHA1 -signedjar C:\workspaceEclipse\ipos\src\main\resources\resigned-resigned-com.dima.pencuy_debug.apk -storepass aperia -keystore src\main\resources\android_key.jks C:\workspaceEclipse\ipos\src\main\resources\resigned-com.dima.pencuy_debug.apk AndroidKey
oct 07, 2014 11:39:24 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFORMACIÓN: App signing output: 
oct 07, 2014 11:39:24 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFORMACIÓN: The app has been signed: C:\workspaceEclipse\ipos\src\main\resources\resigned-resigned-com.dima.pencuy_debug.apk
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\workspaceEclipse\ipos\src\main\resources\resigned-resigned-com.dima.pencuy_debug.apk
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\workspaceEclipse\ipos\src\main\resources\resigned-resigned-com.dima.pencuy_debug.apk
oct 07, 2014 11:39:24 AM io.selendroid.server.model.SelendroidStandaloneDriver initApplicationsUnderTest
INFORMACIÓN: App com.dima.pencuy:1.4.1 has been added to selendroid standalone server.
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/MANIFEST.MF
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/CERT.RSA
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/CERT.SF
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/ANDROIDD.SF
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/ANDROIDD.RSA
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/NDKEYSTO.SF
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk META-INF/NDKEYSTO.RSA
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Program Files\Java\jdk1.6.0_45\bin\jarsigner.exe -sigalg SHA256withRSA -digestalg SHA1 -signedjar C:\Users\7\AppData\Local\Temp\resigned-android-driver6878133422419552969.apk -storepass aperia -keystore src\main\resources\android_key.jks C:\Users\7\AppData\Local\Temp\android-driver6878133422419552969.apk AndroidKey
oct 07, 2014 11:39:24 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFORMACIÓN: App signing output: 
oct 07, 2014 11:39:24 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFORMACIÓN: The app has been signed: C:\Users\7\AppData\Local\Temp\resigned-android-driver6878133422419552969.apk
oct 07, 2014 11:39:24 AM io.selendroid.server.model.DeviceStore addDevice
INFORMACIÓN: Adding: HardwareDevice [serial=192.168.56.101:5555, model=null, targetVersion=null]
oct 07, 2014 11:39:24 AM io.selendroid.server.model.DeviceStore addDevice
INFORMACIÓN: Adding: HardwareDevice [serial=192.168.56.101:5555, model=IPOS_v2, targetVersion=ANDROID16]
oct 07, 2014 11:39:24 AM io.selendroid.android.impl.DefaultDeviceManager initializeAdbConnection
INFORMACIÓN: my devices: null
oct 07, 2014 11:39:24 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\tools\android.bat list avds
oct 07, 2014 11:39:26 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe devices
oct 07, 2014 11:39:26 AM io.selendroid.server.model.DeviceStore addEmulators
INFORMACIÓN: Adding: AndroidEmulator [screenSize=(240, 400), targetPlatform=ANDROID14, serial=null, avdName=Scantech]
selendroid-standalone server has been started on port: 4444
oct 07, 2014 11:39:26 AM io.selendroid.server.handler.ListSessionsHandler handle
INFORMACIÓN: list sessions command
oct 07, 2014 11:39:26 AM io.selendroid.server.handler.CreateSessionHandler handle
INFORMACIÓN: new session command with capabilities: {"desiredCapabilities": {
  "aut": "com.dima.pencuy:1.4.1",
  "automationName": "selendroid",
  "browserName": "selendroid",
  "platformName": "android"
}}
oct 07, 2014 11:39:26 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell pm list packages com.dima.pencuy
oct 07, 2014 11:39:27 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 install -r C:\workspaceEclipse\ipos\src\main\resources\resigned-resigned-com.dima.pencuy_debug.apk
oct 07, 2014 11:39:31 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell pm list packages io.selendroid.com.dima.pencuy
oct 07, 2014 11:39:31 AM io.selendroid.builder.SelendroidServerBuilder createSelendroidServer
INFORMACIÓN: create SelendroidServer for apk: C:\workspaceEclipse\ipos\src\main\resources\resigned-resigned-com.dima.pencuy_debug.apk
oct 07, 2014 11:39:31 AM io.selendroid.builder.SelendroidServerBuilder init
INFORMACIÓN: Creating customized Selendroid-server: C:\Users\7\AppData\Local\Temp\selendroid-server8828457596409533036.apk
oct 07, 2014 11:39:31 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\selendroid-server8828457596409533036.apk META-INF/CERT.RSA
oct 07, 2014 11:39:31 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\selendroid-server8828457596409533036.apk META-INF/CERT.SF
oct 07, 2014 11:39:31 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Users\7\AppData\Local\Temp\selendroid-server8828457596409533036.apk AndroidManifest.xml
oct 07, 2014 11:39:31 AM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFORMACIÓN: Adding target package 'com.dima.pencuy' to C:\Users\7\AppData\Local\Temp\com.dima.pencuy1412689171939\AndroidManifest.xml
oct 07, 2014 11:39:31 AM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFORMACIÓN: Final Manifest File:
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="0.12.0-SNAPSHOT" package="io.selendroid.com.dima.pencuy">

    <uses-sdk android:minSdkVersion="10"/>

    <instrumentation android:name="io.selendroid.ServerInstrumentation" android:targetPackage="io.selendroid.testapp"/>
    <instrumentation android:name="io.selendroid.LightweightInstrumentation" android:targetPackage="io.selendroid.testapp"/>

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION"/>
    <uses-permission android:name="android.permission.INJECT_EVENTS"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>

    <application android:debuggable="true" android:icon="@drawable/selenium_icon" android:label="Selendroid">
        <uses-library android:name="android.test.runner"/>
    </application>

</manifest>

oct 07, 2014 11:39:31 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe package -M C:\Users\7\AppData\Local\Temp\com.dima.pencuy1412689171939\AndroidManifest.xml -I C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\platforms\android-L\android.jar -F C:\Users\7\AppData\Local\Temp\com.dima.pencuy1412689171939\manifest.apk -f
oct 07, 2014 11:39:31 AM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFORMACIÓN: 
oct 07, 2014 11:39:32 AM io.selendroid.builder.SelendroidServerBuilder createAndAddCustomizedAndroidManifestToSelendroidServer
INFORMACIÓN: file: C:\Users\7\AppData\Local\Temp\com.dima.pencuy1412689171939selendroid-server.apk
oct 07, 2014 11:39:32 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Program Files\Java\jdk1.6.0_45\bin\jarsigner.exe -sigalg SHA256withRSA -digestalg SHA1 -signedjar C:\Users\7\AppData\Local\Temp\selendroid-server-com.dima.pencuy-0.12.0-SNAPSHOT.apk -storepass aperia -keystore src\main\resources\android_key.jks C:\Users\7\AppData\Local\Temp\com.dima.pencuy1412689171939selendroid-server.apk AndroidKey
oct 07, 2014 11:39:32 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFORMACIÓN: App signing output: 
oct 07, 2014 11:39:32 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFORMACIÓN: The app has been signed: C:\Users\7\AppData\Local\Temp\selendroid-server-com.dima.pencuy-0.12.0-SNAPSHOT.apk
oct 07, 2014 11:39:32 AM io.selendroid.io.ShellCommand exec
INFORMACIÓN: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 install -r C:\Users\7\AppData\Local\Temp\selendroid-server-com.dima.pencuy-0.12.0-SNAPSHOT.apk
oct 07, 2014 11:39:35 AM io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
GRAVE: Error occurred while starting Selendroid session
io.selendroid.exceptions.SessionNotCreatedException: Could not install selendroid-server on device
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:211)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```
	
And the logcat is throwing the following error: 

```
W/ActivityManager(  311): No content provider found for permission revoke: file:///data/local/tmp/selendroid-server-com.dima.pencuy-0.12.0-SNAPSHOT.apk
W/ActivityManager(  311): No content provider found for permission revoke: file:///data/local/tmp/selendroid-server-com.dima.pencuy-0.12.0-SNAPSHOT.apk
D/dalvikvm(  311): WAIT_FOR_CONCURRENT_GC blocked 0ms
E/PackageParser(  311): Package io.selendroid.com.dima.pencuy has no certificates at entry AndroidManifest.xml; ignoring!	



The other issue I faced is when the keystore has different storepass than keypass and when that happens this is error is thrown:

C:\Selendroid>java -jar selendroid-standalone-0.12.0-20141007.105459-78-with-dependencies.jar -app customApp.apk -keystore custom.keystore -keystorePassword keyPassword -keystoreAli
as customAlias
################# Selendroid #################
################# Configuration in use #################
io.selendroid.SelendroidConfiguration@398020cc[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[customApp.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=custom.keystore
  keystorePassword=keyPassword
  keystoreAlias=customAlias
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
]
07/10/2014 10:48:38 AM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/MANIFEST.MF
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/CERT.RSA
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/CERT.SF
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/ANDROIDD.SF
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/ANDROIDD.RSA
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/NDKEYSTO.SF
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Eclipses\adt-bundle-windows-x86_64-20140702\sdk\build-tools\android-4.4W\aapt.exe remove C:\Selendroid\customApp.apk META-INF/NDKEYSTO.RSA
07/10/2014 10:48:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.6.0_45\bin\jarsigner.exe -sigalg SHA1withRSA -digestalg SHA1 -signedjar C:\Selendroid\resigned-customApp.apk -storepass keyPassword -keystore com.sca
nntech.ipos.android.keystore C:\Selendroid\customApp.apk customAlias
07/10/2014 10:48:38 AM io.selendroid.SelendroidLauncher launchServer
GRAVE: Error occurred while building server: An error occurred while resigning the app 'customApp.apk'.
io.selendroid.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'customApp.apk'.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:116)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:84)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\Program Files\Java\jdk1.6.0_45\bin\jarsigner.exe -sigalg SHA1withRSA -digestalg SHA1 -signedjar C:\Selendroid\
resigned-customApp.apk -storepass keyPassword -keystore custom.keystore C:\Selendroid\customApp.apk customAlias
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:294)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:153)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:114)
        ... 5 more
Caused by: io.selendroid.exceptions.ShellCommandException: Enter key password for customAlias: jarsigner: you must enter key password

        ... 9 more
Exception in thread "main" io.selendroid.exceptions.SessionNotCreatedException: An error occurred while resigning the app 'customApp.apk'.
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:116)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:84)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Caused by: io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: C:\Program Files\Java\jdk1.6.0_45\bin\jarsigner.exe -sigalg SHA1withRSA -digestalg SHA1 -signedjar C:\Selendroid\
resigned-customApp.apk -storepass keyPassword -keystore custom.keystore C:\Selendroid\customApp.apk customAlias
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.builder.SelendroidServerBuilder.signTestServer(SelendroidServerBuilder.java:294)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:153)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:114)
        ... 5 more
Caused by: io.selendroid.exceptions.ShellCommandException: Enter key password for customAlias: jarsigner: you must enter key password

        ... 9 more
```

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
