### ISSUE TITLE
StaleElementReferenceException not thrown until 600 seconds later

### ISSUE THREAD

**Issue by jackwhitney** [selendroid/selendroid#650]
I am using Appium/Selendroid. Most of the time when a StaleElementReferenceException is thrown it happens right away, but sometimes it doesn't get thrown for 600 seconds. In the case below it is a click that is failing. It looks like the click was attempted, nothing happened for 600 seconds, at which point something timed out, and Appium (?) attempted the click again, which resulted in a StaleElementReferenceException. Where is it spinning for 600 seconds and why?

Here are the Eclipse, Appium and LogCat logs:

16:52:55.903 DEBUG - Satisfied FetchingHtmlElement{LazilyLaunchedWebDriver{sessionId: ad23d6ca-e784-dcd4-9bf7-1b4a46c6ee28}, By.name: HR_Contact_Visibility_Singular--IS} is displayed  - com.workday.testengineering.shared.polling.PollEventsLogger.conditionSatisfied() - PollEventsLogger.java:18
16:52:56.738 DEBUG - Satisfied FetchingHtmlElement{LazilyLaunchedWebDriver{sessionId: ad23d6ca-e784-dcd4-9bf7-1b4a46c6ee28}, By.linkText: Public} is displayed  - com.workday.testengineering.shared.polling.PollEventsLogger.conditionSatisfied() - PollEventsLogger.java:18
17:02:58.781 ERROR - FAILED: changeEmployeePhoneNumberAndEmailAddressAsAManager declared in ChangeContactInfoTest - com.workday.testengineering.shared.reporting.StatusLogger.afterInvocation() - StatusLogger.java:58
org.openqa.selenium.StaleElementReferenceException: An element command failed because the referenced element is no longer attached to the DOM. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 602.02 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'JAWHITNEY-02', ip: '10.236.7.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_45'
Session ID: ad23d6ca-e784-dcd4-9bf7-1b4a46c6ee28
Driver info: com.workday.testengineering.mobile.webdriver.SwipeableAndroidWebDriver
Capabilities [{automationName=selendroid, platformVersion=18, platform=ANDROID, acceptSslCerts=true, javascriptEnabled=true, platformName=android, handlesAlerts=true, browserName=selendroid, networkConnectionEnabled=true, rotatable=true, takesScreenshot=true, version=0.10.0}]
	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_45]
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204) ~[selenium-remote-driver-2.43.1.jar:na]
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156) ~[selenium-remote-driver-2.43.1.jar:na]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599) ~[selenium-remote-driver-2.43.1.jar:na]
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:176) ~[java-client-2.0.0.jar:na]
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268) ~[selenium-remote-driver-2.43.1.jar:na]
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79) ~[selenium-remote-driver-2.43.1.jar:na]
	at com.workday.testengineering.html.common.core.WebElementExpressions$1.actOn(WebElementExpressions.java:24) ~[html-common-svn-r29440.jar:na]
	at com.workday.testengineering.html.common.core.WebElementExpressions$1.actOn(WebElementExpressions.java:21) ~[html-common-svn-r29440.jar:na]
	at com.workday.testengineering.html.common.core.HtmlElementBase.perform(HtmlElementBase.java:174) ~[html-common-svn-r29440.jar:na]
	at com.workday.testengineering.html.common.core.HtmlElementBase.click(HtmlElementBase.java:30) ~[html-common-svn-r29440.jar:na]
	at com.workday.android.automation.pages.workerProfile.ContactPrimaryEmailPage.setVisibilityPublic(ContactPrimaryEmailPage.java:61) ~[test-classes/:na]
	at com.workday.android.automation.tests.ChangeContactInfoTest.changeEmailAddressVisibilityAndAddNote(ChangeContactInfoTest.java:157) ~[test-classes/:na]
	at com.workday.android.automation.tests.ChangeContactInfoTest.changeEmployeePhoneNumberAndEmailAddressAsAManager(ChangeContactInfoTest.java:65) ~[test-classes/:na]
	

10-16 19:52:10.217: I/SELENDROID(3273): io.selendroid.server.handler.FindElement#handle:40 - find element command using 'name' with selector 'HR_Contact_Visibility_Singular--IS'.
10-16 19:52:10.227: I/SELENDROID(3273): io.selendroid.server.handler.GetElementDisplayed#handle:34 - is element displayed command
10-16 19:52:10.247: I/SELENDROID(3273): io.selendroid.server.handler.FindElement#handle:40 - find element command using 'name' with selector 'HR_Contact_Visibility_Singular--IS'.
10-16 19:52:10.257: I/SELENDROID(3273): io.selendroid.server.handler.ClickElement#handle:35 - Click element command
10-16 19:52:10.867: I/ActivityManager(1214): START u0 {cmp=com.workday.workdroidapp/.max.widgets.moniker.PromptSelectionActivity (has extras)} from pid 3273
10-16 19:52:10.887: W/WindowManager(1214): Screenshot failure taking screenshot for (328x583) to layer 21025
10-16 19:52:10.907: I/SELENDROID(3273): io.selendroid.server.handler.FindElement#handle:40 - find element command using 'link text' with selector 'Public'.
10-16 19:52:10.917: I/SELENDROID(3273): io.selendroid.server.handler.GetElementDisplayed#handle:34 - is element displayed command
10-16 19:52:10.927: D/dalvikvm(1214): GC_FOR_ALLOC freed 740K, 51% free 5580K/11268K, paused 26ms, total 26ms
10-16 19:52:10.937: D/LIFECYCLE(3273): MaxTaskFragment@b1e0ed88.onPause()
10-16 19:52:10.937: D/LIFECYCLE(3273): RootModelFragment@b1952d08.onPause()
10-16 19:52:10.937: D/LIFECYCLE(3273): MaxActivity@b1b85f88.onPause()
10-16 19:52:10.957: D/LIFECYCLE(3273): PromptSelectionActivity@b1e5e3e0.onCreate()
10-16 19:52:10.967: D/LIFECYCLE(3273): PromptItemSelectionFragment@b1b0c300.onCreate()
10-16 19:52:10.967: D/LIFECYCLE(3273): PromptItemSelectionFragment@b1b0c300.onStart()
10-16 19:52:10.967: D/LIFECYCLE(3273): PromptSelectionActivity@b1e5e3e0.onStart()
10-16 19:52:11.057: D/LIFECYCLE(3273): PromptSelectionActivity@b1e5e3e0.onResume()
10-16 19:52:11.057: D/LIFECYCLE(3273): PromptItemSelectionFragment@b1b0c300.onResume()
10-16 19:52:11.077: I/SELENDROID(3273): io.selendroid.server.handler.FindElement#handle:40 - find element command using 'link text' with selector 'Public'.
10-16 19:52:11.107: I/SELENDROID(3273): io.selendroid.server.handler.ClickElement#handle:35 - Click element command
10-16 19:52:11.177: I/ActivityManager(1214): Displayed com.workday.workdroidapp/.max.widgets.moniker.PromptSelectionActivity: +230ms
10-16 19:52:11.947: D/LIFECYCLE(3273): MaxTaskFragment@b1e0ed88.onStop()
10-16 19:52:11.947: D/LIFECYCLE(3273): RootModelFragment@b1952d08.onStop()
10-16 19:52:11.947: D/LIFECYCLE(3273): MaxActivity@b1b85f88.onStop()
10-16 19:52:18.697: W/ActivityManager(1214): Activity stop timeout for ActivityRecord{b1384a08 u0 com.workday.workdroidapp/.max.taskorchestration.summary.TaskOrchestrationSummaryActivity}
10-16 19:53:49.318: D/dalvikvm(1395): GC_FOR_ALLOC freed 512K, 19% free 2986K/3668K, paused 3ms, total 3ms
10-16 19:54:04.779: D/dalvikvm(3273): GC_FOR_ALLOC freed 2231K, 29% free 14505K/20184K, paused 13ms, total 13ms
10-16 20:01:31.365: D/dalvikvm(3273): GC_FOR_ALLOC freed 2035K, 29% free 14518K/20184K, paused 11ms, total 11ms
10-16 20:02:12.066: I/SELENDROID(3273): io.selendroid.server.handler.ClickElement#handle:35 - Click element command
10-16 20:02:12.086: I/SELENDROID(3273): io.selendroid.server.handler.DeleteSession#handle:33 - delete session command

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
