### ISSUE TITLE
SEVERE: Error getting status: java.net.SocketException: Connection reset 十月 20, 2014 4:10:15 下午 io.selendroid.server.handler.CreateSessionHandler handle SEVERE: Error while creating new session: Selendroid server on the device didn't came up after 20sec: io.selendroid.exceptions.SelendroidException: Selendroid server on the device didn't came up after 20sec:

### ISSUE THREAD

**Issue by gqy727** [selendroid/selendroid#652]
Hi there,
    I have a problem that i can not solve.I have the app on mobile restarted  n(n>10) times,then in this progress , the port from 8080 to 8089 increased one by one.Until 8089,the app on mobile can not start.I think is the port is occupied,but i  don't know how to resolve it.
Thank you for your time.

The follow is the log ：
===============================================================================
十月 20, 2014 4:10:15 下午 org.apache.http.impl.client.DefaultHttpClient tryExecute
INFO: Retrying request to {}->http://localhost:8089
十月 20, 2014 4:10:15 下午 io.selendroid.android.impl.AbstractDevice isSelendroidRunning
SEVERE: Error getting status: java.net.SocketException: Connection reset
十月 20, 2014 4:10:15 下午 io.selendroid.server.handler.CreateSessionHandler handle
SEVERE: Error while creating new session: Selendroid server on the device didn't came up after 20sec:
io.selendroid.exceptions.SelendroidException: Selendroid server on the device didn't came up after 20sec:
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:31
5)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)
十月 20, 2014 4:10:15 下午 io.selendroid.server.handler.CreateSessionHandler handle
INFO: new session command with capabilities: {"desiredCapabilities": {
  "browserName": "android",
  "platform": "ANDROID",
  "version": ""
}}
十月 20, 2014 4:10:15 下午 io.selendroid.server.model.DeviceStore findAndroidDevice
INFO: Evaluating if this device is a match for this session: HardwareDevice [serial=ZTE-Grand-S, model=ZTE Grand S, targ
etVersion=ANDROID16]
十月 20, 2014 4:10:15 下午 io.selendroid.server.model.DeviceStore findAndroidDevice
INFO: Device is in use.
十月 20, 2014 4:10:15 下午 io.selendroid.server.model.DeviceStore findAndroidDevice
INFO: Evaluating if this device is a match for this session: AndroidEmulator [screenSize=, targetPlatform=null, serial=n
ull, avdName=test]
十月 20, 2014 4:10:15 下午 io.selendroid.io.ShellCommand exec
INFO: executing command: E:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe shell input keyevent 82
十月 20, 2014 4:10:35 下午 io.selendroid.io.ShellCommand exec
INFO: executing command: E:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe shell am force-stop io.selendr
oid.androiddriver
十月 20, 2014 4:10:41 下午 io.selendroid.server.model.DeviceStore removeAndroidDevice
INFO: Removing: HardwareDevice [serial=ZTE-Grand-S, model=ZTE Grand S, targetVersion=ANDROID16]
io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: E:\adt-bundle-windows-x8
6_64-20140702\sdk\platform-tools\adb.exe shell am force-stop io.selendroid.androiddriver
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevice.java:176)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevice.java:171)
        at io.selendroid.android.impl.AbstractDevice.kill(AbstractDevice.java:206)
        at io.selendroid.server.model.DeviceStore.release(DeviceStore.java:75)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:24
5)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.ShellCommandException: error: protocol fault (no status)
error: protocol fault (no status)

        ... 28 more
十月 20, 2014 4:10:41 下午 io.selendroid.io.ShellCommand exec
INFO: executing command: E:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe shell pm clear io.selendroid.a
ndroiddriver
io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: E:\adt-bundle-windows-x8
6_64-20140702\sdk\platform-tools\adb.exe shell pm clear io.selendroid.androiddriver
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevice.java:176)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevice.java:171)
        at io.selendroid.android.impl.AbstractDevice.clearUserData(AbstractDevice.java:199)
        at io.selendroid.server.model.DeviceStore.release(DeviceStore.java:81)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:24
5)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.ShellCommandException: error: device not found
error: device not found

        ... 28 more
十月 20, 2014 4:10:41 下午 io.selendroid.server.handler.CreateSessionHandler handle
SEVERE: Error while creating new session: null
java.lang.NullPointerException
        at io.selendroid.server.model.impl.DefaultPortFinder.release(DefaultPortFinder.java:59)
        at io.selendroid.server.model.DeviceStore.release(DeviceStore.java:93)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:24
5)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)
十月 20, 2014 4:10:57 下午 io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=0123456789ABCDEF, model=null, targetVersion=null]
十月 20, 2014 4:10:57 下午 io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=0123456789ABCDEF, model=ZTE Grand S, targetVersion=ANDROID16]
十月 20, 2014 4:11:12 下午 io.selendroid.server.model.DeviceStore removeAndroidDevice
INFO: Removing: HardwareDevice [serial=0123456789ABCDEF, model=ZTE Grand S, targetVersion=ANDROID16]
十月 20, 2014 4:11:50 下午 io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZTE-Grand-S, model=null, targetVersion=null]
十月 20, 2014 4:11:50 下午 io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZTE-Grand-S, model=ZTE Grand S, targetVersion=ANDROID16]

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
