### ISSUE TITLE
io.selendroid.exceptions.NoSuchElementException: Element was not found.

### ISSUE THREAD

**Issue by nithinshetty** [selendroid/selendroid#654]
![sf1 inspector](https://cloud.githubusercontent.com/assets/9336093/4718536/e45674f4-5921-11e4-8a65-a6e24d28d31a.png)
Hello , I am using selendroid to run the test on salesforce1 apk file. The salesforce app successfully launching but its throwing an exception while entering the 'User Name' that "io.selendroid.exceptions.NoSuchElementException: Element was not found."  But the element i have used is correct since it was located using selendroid inspector.  code is "WebElement element = driver.findElement(By.id("username")); ". I have successfully executed selendroid test app. But getting problem in salesforce1 login page. Please help since I am new to selendroid!

**Comment by 5654566** [comment]
Hi

I am new in Selendroid. I am getting "io.selendroid.exceptions.NoSuchElementException: Element was not found" when i have executed selendroid test app.

Any one Please help me to resolve this issue.It's Urgent...........

Thanks,
Gunjan.

**Comment by operatiay** [comment]
hi @5654566 if you want to have a reasonable answer to your problem please provide more information about your setup and the test you're executing in a new issue, since this one has been closed quite a while ago.
I also assume it's not really an issue but rather you trying to figure out how to use selendroid. have a look at selendroid.io for documentation. If you follow all the steps described there for the test app it should work.

**Comment by 5654566** [comment]
Hi        
Here are the steps



1. lnstalled JDK and java home path setup in machine.
2. Instlled Android SDK and set up path
3. Download Selenium jar file from: https://github.com/selendroid/selendroid/releases/download/0.15.0/selendroid-standalone-0.15.0-with-dependencies.jar
4. Create folder and put above jar file and selendroid-test-app-0.12.0.apk file
5. Run command (from where above files are available) - java -jar selendroid-standalone-0.15.0-with-dependencies.jar -app selendroid-test-app-0.12.0.apk
6. Check status here - http://localhost:4444/wd/hub/status
7. Eclipse with testNG framework.
8. Create new Emulator or attached real devices with you machine.
9.Created new java project.

Let me know if I missed something

**Comment by operatiay** [comment]
new issue, please. and your description doesn't have a problem

**Comment by 5654566** [comment]
Hi

Here is my Code
package com.test;

import io.selendroid.SelendroidCapabilities;
import io.selendroid.SelendroidConfiguration;
import io.selendroid.SelendroidDriver;
import io.selendroid.SelendroidLauncher;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;
 
public class SelendroidTest {
  
 private WebDriver driver ;
  
 @BeforeSuite
 public void setUp() throws Exception
 {  
	 
	 SelendroidConfiguration config = new SelendroidConfiguration();
	 SelendroidLauncher selendroidServer = new SelendroidLauncher(config);
	 selendroidServer.launchSelendroid();
	 DesiredCapabilities caps = SelendroidCapabilities.android();
	 driver = new SelendroidDriver(caps);
	 
	 config.addSupportedApp("selendroid-test-app-0.12.0");
 }
 
 @Test
 public void selendroidTest() throws Exception
 {  
	 

  WebElement inputField = driver.findElement(By.id("my_text_field"));
  Assert.assertEquals("true", inputField.getAttribute("enabled"));
  inputField.sendKeys("Selendroid");
 
  Assert.assertEquals("Selendroid", inputField.getText());
   
  //click EN button
 // WebElement button = driver.findElement(By.id("buttonTest"));  
 // button.click();
   
  //click accept button
 // button = driver.findElement(By.id("button2"));  
 // button.click();
   
 // Thread.sleep(5000);
  //click on registration button
 // button = driver.findElement(By.id("startUserRegistration"));  
 // button.click();
   
  //Thread.sleep(10000);
  // fill registration form data
 // WebElement element = driver.findElement(By.id("label_username"));
 // String text = element.getText();
 // System.out.println(text);
//  element = driver.findElement(By.id("inputUsername"));
  //element.sendKeys("bob");
   
  //element = driver.findElement(By.id("inputEmail"));
 // element.sendKeys("test@gmail.com");
   
  //element = driver.findElement(By.id("inputPassword"));
  //element.clear();
 // element.sendKeys("test1233");
   
  //element = driver.findElement(By.id("inputName"));
  //element.clear();
  //element.sendKeys("My Name ");
   
 // element = driver.findElement(By.id("input_preferedProgrammingLanguage"));
 // element.click();
   
  //element = driver.findElement(By.id("text1"));
 // element.click();
   
  //element = driver.findElement(By.id("input_adds"));
  //element.click();
   
 // element = driver.findElement(By.id("btnRegisterUser"));
 // element.click();
   
  //element = driver.findElement(By.id("buttonRegisterUser"));
 // element.click();  
 }
  
 @AfterSuite
 public void tearDown(){
        driver.quit();
 }
} 

And Following error i am getting while executing......
[TestNG] Running:
  C:\Users\MTech\AppData\Local\Temp\testng-eclipse--1822081479\testng-customsuite.xml

Jun 08, 2015 9:26:38 AM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/MANIFEST.MF
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/CERT.RSA
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/CERT.SF
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/ANDROIDD.SF
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/ANDROIDD.RSA
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/NDKEYSTO.SF
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\build-tools\21.1.2\aapt.exe remove C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk META-INF/NDKEYSTO.RSA
Jun 08, 2015 9:26:38 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.7.0_80\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\MTech\AppData\Local\Temp\resigned-android-driver3554300179536601908.apk -storepass android -keystore C:\Users\MTech\.android\debug.keystore C:\Users\MTech\AppData\Local\Temp\android-driver3554300179536601908.apk androiddebugkey
Jun 08, 2015 9:26:39 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: App signing output: jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2042-10-19) or after any future revocation date.

Jun 08, 2015 9:26:39 AM io.selendroid.builder.SelendroidServerBuilder signTestServer
INFO: The app has been signed: C:\Users\MTech\AppData\Local\Temp\resigned-android-driver3554300179536601908.apk
Jun 08, 2015 9:26:39 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZX1D636C4K, model=null, targetVersion=null]
Jun 08, 2015 9:26:39 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZX1D636C4K, model=XT1068, targetVersion=null]
Jun 08, 2015 9:26:39 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=ZX1D636C4K, model=XT1068, targetVersion=null]
Jun 08, 2015 9:26:39 AM io.selendroid.android.impl.DefaultDeviceManager initializeAdbConnection
INFO: my devices: null
Jun 08, 2015 9:26:39 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\tools\android.bat list avds
Jun 08, 2015 9:26:40 AM io.selendroid.io.ShellCommand exec
INFO: executing command: D:\SDK\platform-tools\adb.exe devices
Jun 08, 2015 9:26:40 AM io.selendroid.server.model.DeviceStore addEmulators
INFO: No emulators has been found.
selendroid-standalone server has been started on port: 4444
Exception in thread "Thread-22" java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:467)
	at sun.nio.ch.Net.bind(Net.java:459)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:476)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1021)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:455)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:844)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:195)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:339)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
FAILED: selendroidTest
org.openqa.selenium.NoSuchElementException: Element was not found.
io.selendroid.exceptions.NoSuchElementException: Element was not found.
	at io.selendroid.server.handler.FindElement.handle(FindElement.java:58)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:301)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:818)

Command duration or timeout: 5.26 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MTech-PC', ip: '192.168.1.21', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_80-ea'
Session ID: 2dce9abe-82cb-bf2c-c193-bebba64e8dd0
Driver info: io.selendroid.SelendroidDriver
Capabilities [{automationName=selendroid, platformVersion=21, platform=ANDROID, javascriptEnabled=true, acceptSslCerts=true, platformName=android, browserName=selendroid, handlesAlerts=true, networkConnectionEnabled=true, rotatable=true, takesScreenshot=true, version=0.11.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:393)
	at org.openqa.selenium.By$ById.findElement(By.java:214)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at com.test.SelendroidTest.selendroidTest(SelendroidTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: io.selendroid.exceptions.NoSuchElementException: Element was not found.
io.selendroid.exceptions.NoSuchElementException: Element was not found.
	at io.selendroid.server.handler.FindElement.handle(FindElement.java:58)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:301)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:818)



===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@933c07: 5 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@1609872: 24 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@1abcd5e: 7 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@e67c12: 35 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@11e170c: 5 ms
Jun 08, 2015 9:26:53 AM io.selendroid.SelendroidLauncher$1 run
INFO: Shutting down Selendroid standalone

**Comment by 5654566** [comment]
If you can help me Please........

**Comment by operatiay** [comment]
new issue, please.

**Comment by 5654566** [comment]
Ok. Thanks
