### ISSUE TITLE
Cannot run Cordova hybrid app.  

### ISSUE THREAD

**Issue by sebv** [selendroid/selendroid#658]
I get this error as soon as I do a 'view source' or find element within a Webview. There is some sort of conflict between Cordova and Selendroid WebDriver classes. 

```
E/SELENDROID(  952): io.selendroid.server.model.SelendroidWebDriver$4#run:354 - An error occured while configuring the web view
E/SELENDROID(  952): java.lang.ClassCastException: io.selendroid.server.model.SelendroidWebDriver$SelendroidWebChromeClient cannot be cast to org.apache.cordova.CordovaChromeClient
E/SELENDROID(  952): 	at org.apache.cordova.CordovaWebView.setWebChromeClient(CordovaWebView.java:316)
E/SELENDROID(  952): 	at io.selendroid.server.model.SelendroidWebDriver$4.run(SelendroidWebDriver.java:331)
E/SELENDROID(  952): 	at android.os.Handler.handleCallback(Handler.java:615)
E/SELENDROID(  952): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/SELENDROID(  952): 	at android.os.Looper.loop(Looper.java:137)
E/SELENDROID(  952): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/SELENDROID(  952): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/SELENDROID(  952): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/SELENDROID(  952): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/SELENDROID(  952): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/SELENDROID(  952): 	at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm-heap(  952): Grow heap (frag case) to 8.687MB for 143314-byte allocation
D/AndroidRuntime(  952): Shutting down VM
E/SEL
```

This can be reproduced this way:

1/ generate the app
```
npm install -g cordova
cordova create helloworld com.example.hello
cd helloworld
cordova platform add android
cordova build android
```
The generated app is <PATH>/helloworld/platforms/android/ant-build/CordovaApp-debug.apk

2/ start Selendroid server
```
java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app <PATH>/helloworld/platforms/android/ant-build/CordovaApp-debug.apk
```

3/ run test:
- init app
- switch_to WEBVIEW_0
- get page source 

wd.js gist here: https://gist.github.com/sebv/ad538e1db3d6a479f847

client output:
```
 > CALL init({"aut":"com.example.hello:0.0.1"})
 > POST /session {"desiredCapabilities":{"deviceName":"selendroid","aut":"com.example.hello:0.0.1"}}

Driving the web on session: c5a78f00-ba52-1268-8c30-25127f45dbb4

 > RESPONSE init({"aut":"com.example.hello:0.0.1"}) "c5a78f00-ba52-1268-8c30-25127f45dbb4",{"platform":"ANY","deviceName":"selendroid","aut":"com.example.hello:0.0.1"}
 > CALL windowHandles()
 > GET /session/:sessionID/window_handles
 > RESPONSE windowHandles() ["NATIVE_APP","WEBVIEW_0"]
 > CALL window("WEBVIEW_0")
 > POST /session/:sessionID/window {"name":"WEBVIEW_0"}
 > RESPONSE window("WEBVIEW_0")
 > CALL source()
 > GET /session/:sessionID/source

/Users/baba/Documents/Work/selendroid-hack/node_modules/wd/node_modules/q/q.js:126
                    throw e;
                          ^
Error: [source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Unexpected error communicating with selendroid server on the device
```

**Comment by kruchx** [comment]
@aaltat Could you share your working solution? I was trying to resolve it in way which @fqlyu show, but I wasn't able to do it.

**Comment by aaltat** [comment]
@kruchx I can't. But my code is same as @fqlyu, but if you tell what is your problem and errors you are getting, perhaps I can push you to the right direction.

**Comment by kruchx** [comment]
@aaltat I tried to extend CordovaChromeClient and override on onJsAlert. But I'm not sure what  should be in this overridden function. I can see, that you are using chromeClient, but I don't know, what is it, and how to declare it.

What I have:
```java
public class SelfWebChromeClient extends CordovaChromeClient{
    public SelfWebChromeClient(CordovaInterface cordova)
    {
        super(cordova);
    }

    @Override
    public boolean onJsAlert(WebView view, String url, String message, final JsResult result) {
        if (view instanceof CordovaWebView) {
            chromeClient = new SelfWebChromeClient();
        } else {
            chromeClient = new SelendroidWebChromeClient();
        }
        return true;
    }
}
```
Of course I know, this is not proper code, but I'm looking for some solution, how make it work. Any clue, how can I override this onJsAlert? I know what we want to achieve here, but I do not know how to do it...

**Comment by kruchx** [comment]
OK, I have some progress, but still have one problem. How did you create standard contructor, if in CordovaChromeClient there is no such thing? It seems, that if I want to create this client, I have to pass CordovaInterface as a parameter. But I do not know, from where I can get this object.

**Comment by aaltat** [comment]
As far I recall the code in my side looks about the same. The thing that I was missing was the runtime dependency for the Cordova library and the required library imports from cordova. 

In short, I did this: 
1) Clone the Cordova from github: https://github.com/apache/cordova-android
2) Build the library with Ant
3) Add jar to maven local repo, see this for details: http://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
4) Modify the selendroid-standalone pom.xml to contain the cordova jar as runtime dependency. 
5) Build selendroid with maven and you are ready to go.

**Comment by kruchx** [comment]
I managed to add maven Cordova dependency earlier (before my post). What I faced is fact, that when I'm trying to extend CordovaChromeClient, there is no standard constructor. In SelendroidWebDriver I  created null CordovaInterface object and pass it as parameter to extended CordoveWebDrive class, but it didn't work.

Now, when I'm starting tests on old Cordova application, everything is working fine. But when I'm trying to start it on new Cordova, and I have errors:

http://pastebin.com/NuCb4qD3

**Comment by TundraGeek** [comment]
@aaltat and @fqlyu 

Any chance one of you could post up the actual code you have implemented to get around this?  Sorry, I have tried to follow along with the snippets that have been posted thus far but I have to admit that I am lost.  I have the Cordova code and have compiled it into a JAR.  

I have also added a dependency on that JAR to the POM file for selendroid-standalone and compiled that JAR and updated my projects POM to reference the new selendroid-standalone JAR I compiled.  I have tried to follow along with the code snippets presented in this thread and tried various means but none seem to be working.

If one of you could post the full code for any classes that you either implemented or modified (in selendroid or Cordova) that would be a great help to me and others.

Thanks for any help.

**Comment by DominikDary** [comment]
Hi all,

I worked on a possible fix. You can see the pull request [here](https://github.com/selendroid/selendroid/pull/788). There I provide as well a jar so that it is easy to verify the fix.

Please let me know in the PR if it works fine in your cases.

Thanks!

Dominik

**Comment by Okanim** [comment]
Hi,
I have the same issue with the latest Selendroid version (I use Appium but I run from source to have the latest version). 

Cordova change their android framework ( [Apache Cordova Android 4.0.0](https://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html)). Does Selendroid support this version ? 

Thanks.

**Comment by Okanim** [comment]
Ok sorry to write here, but I don't think I have to make a new issue.

I found a solution. In the new framework they just change the name of classes, CordovaChromeClient became SystemWebChromeClient, Same for CordovaWebView which became SystemWebView. 

Here the code I change in SelendroidWebDriver.java
```
if (view.getClass().getSimpleName().equalsIgnoreCase("SystemWebView")) {
            SystemWebView webview=(SystemWebView)view;
            SystemWebViewEngine webEngine= new SystemWebViewEngine(webview);
            chromeClient = new ExtendedCordovaChromeClient(webEngine);

         } else {
            chromeClient = new SelendroidWebChromeClient();
          }
```

```
public class ExtendedCordovaChromeClient extends SystemWebChromeClient {


    public ExtendedCordovaChromeClient(SystemWebViewEngine parentEngine) {
      super(parentEngine);
    }
```

As you can see the constructor of the SystemWebChromeClient change.

And you must add the new library of Cordova in Selendroid.


If you have any idea to implement this in Selendroid to support both version ( Maybe create one class which extend CordovaChromeClient, and an another which extend of SystemWebChromeClient).

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
