### ISSUE TITLE
SELENDROID ERR on Android 4.4

### ISSUE THREAD

**Issue by luoshangyu** [selendroid/selendroid#660]
Dear folks,

I'm not sure if i'm in the right place to ask the question.

Recently, I'm trying to write hybrid code by using Appium via Selendroid mode.
Unfortunately, I never get my code running successfully.

Anybody can help me?

Here is my capability
            DesiredCapabilities cap = new DesiredCapabilities();
            cap.SetCapability(CapabilityType.BrowserName, "");
            cap.SetCapability("appium-version", "1.2");
            cap.SetCapability("platformName", "Android");
            cap.SetCapability("platformVersion", "4.4");
            cap.SetCapability("automationName", "Selendroid");
            cap.SetCapability("appPackage", "xxx");
            cap.SetCapability("appActivity", "xxx");
            cap.SetCapability("deviceName", "Nexus 4");

Here is the error
info: <-- GET /wd/hub/session/c6cdad17-e5a4-364d-d398-ace0fe111cfe 200 66.869 ms
 - 358
info: [debug] [SELENDROID ERR] length=0; regionStart=0; regionLength=3
info: [debug] [SELENDROID ERR]  at java.lang.String.startEndAndLength(String.jav
a:588)
info: [debug] [SELENDROID ERR]  at java.lang.String.substring(String.java:1475)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.core.c.c(ClientInfoUtil
.java:222)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.c.<init>(IGPSManager.ja
va:24)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.c.a(IGPSManager.java:31
)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.a.<init>(AMapLocationMa
nager.java:34)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.a.a(AMapLocationManager
.java:60)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.LocationManagerProxy.a(
LocationManagerProxy.java:97)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.LocationManagerProxy.<i
nit>(LocationManagerProxy.java:57)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.LocationManagerProxy.ge
tInstance(LocationManagerProxy.java:81)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.location.AMapLocationManager
.start(Unknown Source)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.location.LocationUtils.start
upLocationService(Unknown Source)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.activity.IndexActivity.onRes
ume(Unknown Source)
info: [debug] [SELENDROID ERR]  at android.app.Instrumentation.callActivityOnRes
ume(Instrumentation.java:1192)
info: [debug] [SELENDROID ERR]  at io.selendroid.ServerInstrumentation.callActiv
ityOnResume(ServerInstrumentation.java:170)
info: [debug] [SELENDROID ERR]  at android.app.Activity.performResume(Activity.j
ava:5310)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.performResumeActiv
ity(ActivityThread.java:2764)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.handleResumeActivi
ty(ActivityThread.java:2803)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.handleLaunchActivi
ty(ActivityThread.java:2238)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.access$800(Activit
yThread.java:135)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1196)
info: [debug] [SELENDROID ERR]  at android.os.Handler.dispatchMessage(Handler.ja
va:102)
info: [debug] [SELENDROID ERR]  at android.os.Looper.loop(Looper.java:136)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.main(ActivityThrea
d.java:5001)
info: [debug] [SELENDROID ERR]  at java.lang.reflect.Method.invokeNative(Native
Method)
info: [debug] [SELENDROID ERR]  at java.lang.reflect.Method.invoke(Method.java:5
15)
info: [debug] [SELENDROID ERR]  at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:785)
info: [debug] [SELENDROID ERR]  at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:601)
info: [debug] [SELENDROID ERR]  at dalvik.system.NativeStart.main(Native Method)

info: [debug] [SELENDROID ERR] length=0; regionStart=0; regionLength=3
info: [debug] [SELENDROID ERR]  at java.lang.String.startEndAndLength(String.jav
a:588)
info: [debug] [SELENDROID ERR]  at java.lang.String.substring(String.java:1475)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.core.c.c(ClientInfoUtil
.java:222)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.LocationManagerProxy.a(
LocationManagerProxy.java:99)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.LocationManagerProxy.<i
nit>(LocationManagerProxy.java:57)
info: [debug] [SELENDROID ERR]  at com.amap.api.location.LocationManagerProxy.ge
tInstance(LocationManagerProxy.java:81)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.location.AMapLocationManager
.start(Unknown Source)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.location.LocationUtils.start
upLocationService(Unknown Source)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.activity.IndexActivity.onRes
ume(Unknown Source)
info: [debug] [SELENDROID ERR]  at android.app.Instrumentation.callActivityOnRes
ume(Instrumentation.java:1192)
info: [debug] [SELENDROID ERR]  at io.selendroid.ServerInstrumentation.callActiv
ityOnResume(ServerInstrumentation.java:170)
info: [debug] [SELENDROID ERR]  at android.app.Activity.performResume(Activity.j
ava:5310)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.performResumeActiv
ity(ActivityThread.java:2764)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.handleResumeActivi
ty(ActivityThread.java:2803)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.handleLaunchActivi
ty(ActivityThread.java:2238)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.access$800(Activit
yThread.java:135)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1196)
info: [debug] [SELENDROID ERR]  at android.os.Handler.dispatchMessage(Handler.ja
va:102)
info: [debug] [SELENDROID ERR]  at android.os.Looper.loop(Looper.java:136)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.main(ActivityThrea
d.java:5001)
info: [debug] [SELENDROID ERR]  at java.lang.reflect.Method.invokeNative(Native
Method)
info: [debug] [SELENDROID ERR]  at java.lang.reflect.Method.invoke(Method.java:5
15)
info: [debug] [SELENDROID ERR]  at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:785)
info: [debug] [SELENDROID ERR]  at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:601)
info: [debug] [SELENDROID ERR]  at dalvik.system.NativeStart.main(Native Method)

info: [debug] [SELENDROID ERR] Class ref in pre-verified class resolved to unexp
ected implementation
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.utils.LogUtils.log2File(Unkn
own Source)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.app.activity.IndexActivity$4.onP
ageStarted(Unknown Source)
info: [debug] [SELENDROID ERR]  at com.ctrip.ct.frame.utils.jsBridge.WebViewJava
scriptBridge.onPageStarted(Unknown Source)
info: [debug] [SELENDROID ERR]  at com.android.webview.chromium.WebViewContentsC
lientAdapter.onPageStarted(WebViewContentsClientAdapter.java:444)
info: [debug] [SELENDROID ERR]  at com.android.org.chromium.android_webview.AwCo
ntentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelpe
r.java:104)
info: [debug] [SELENDROID ERR]  at android.os.Handler.dispatchMessage(Handler.ja
va:102)
info: [debug] [SELENDROID ERR]  at android.os.Looper.loop(Looper.java:136)
info: [debug] [SELENDROID ERR]  at android.app.ActivityThread.main(ActivityThrea
d.java:5001)
info: [debug] [SELENDROID ERR]  at java.lang.reflect.Method.invokeNative(Native
Method)
info: [debug] [SELENDROID ERR]  at java.lang.reflect.Method.invoke(Method.java:5
15)
info: [debug] [SELENDROID ERR]  at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:785)
info: [debug] [SELENDROID ERR]  at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:601)
info: [debug] [SELENDROID ERR]  at dalvik.system.NativeStart.main(Native Method)

Best Regards,
Lucas Luo

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
