### ISSUE TITLE
Connection getting reset while Launching App

### ISSUE THREAD

**Issue by raviautomation09** [selendroid/selendroid#668]
![selendroiderror](https://cloud.githubusercontent.com/assets/9444375/4823154/cbad93c6-5f4b-11e4-8f7b-36ec4013b7cc.png)
Hi
While launching the application i am getting below issue in Logs:

INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell am instrument -e main_activity wavecrest.mobile.activity.register.AppSplashActivity -e server_port 8080 io.selendroid.wavecrest.mobile.myfare/io.selendroid.ServerInstrumentation
Oct 29, 2014 2:16:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:8080 tcp:8080
Oct 29, 2014 2:16:30 PM io.selendroid.android.impl.AbstractDevice startLogging
INFO: starting logcat:
Oct 29, 2014 2:16:30 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8080/wd/hub/status
Oct 29, 2014 2:16:30 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
Oct 29, 2014 2:16:30 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
Oct 29, 2014 2:16:30 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
Oct 29, 2014 2:16:30 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
Oct 29, 2014 2:16:30 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset
Oct 29, 2014 2:16:30 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8080
Oct 29, 2014 2:16:30 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
=============================================================================
And the Application is getting launched but error prompting :
Error!
There was a problem communicating to the server.
============================================
Got stuck here. Need some solution on this.

Code snippet:
SelendroidCapabilities capa = new SelendroidCapabilities("wavecrest.mobile.myfare:1.0.0");
		
		WebDriver driver = new SelendroidDriver(capa);
		WebElement inputField = driver.findElement(By.id("my_text_field"));
		Assert.assertEquals("true", inputField.getAttribute("enabled"));
		inputField.sendKeys("Selendroid");
		Assert.assertEquals("Selendroid", inputField.getText());
		driver.quit();
==========================================================
Attaching the Image of application error.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
