### ISSUE TITLE
Getting "Unexpected error: TypeError: invalid media type" after trying to check if element is displayed

### ISSUE THREAD

**Issue by kirillzh** [selendroid/selendroid#671]
`info: <-- POST /wd/hub/session/14bcb8ff-200e-6db6-1860-46f8cace28f5/element 200 159.711 ms - 104
info: --> GET /wd/hub/session/14bcb8ff-200e-6db6-1860-46f8cace28f5/element/:wdc:1414793457544/displayed {}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/42f102ec-59ac-86e0-f25e-49269a36853a/element/:wdc:1414793457544/displayed","method":"GET"}
info: [debug] Proxied response received with status 500:
error: Unexpected error: TypeError: invalid media type
    at splitType (/Users/kirill/appium/node_modules/express/node_modules/media-typer/index.js:240:11)
    at Object.parse (/Users/kirill/appium/node_modules/express/node_modules/media-typer/index.js:160:13)
    at exports.setCharset (/Users/kirill/appium/node_modules/express/lib/utils.js:247:22)
    at ServerResponse.res.send (/Users/kirill/appium/node_modules/express/lib/response.js:133:32)
    at /Users/kirill/appium/lib/server/proxy.js:80:11
    at safely (/Users/kirill/appium/lib/server/helpers.js:306:5)
    at /Users/kirill/appium/lib/server/proxy.js:77:5
    at Request._callback (/Users/kirill/appium/lib/devices/common.js:121:5)
    at Request.self.callback (/Users/kirill/appium/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17) context: [GET /wd/hub/session/14bcb8ff-200e-6db6-1860-46f8cace28f5/element/:wdc:1414793457544/displayed {}]`

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
