### ISSUE TITLE
unable to connect to programmatically started server (io.selendroid.server.http.ServerHandler exceptionCaught)

### ISSUE THREAD

**Issue by twehlin** [selendroid/selendroid#675]
I have a running test suite that works fine as long as i start the server manually.
But now when I'm trying to start the server via code i keep getting this error.
Any ideas of what I'm missing?

Nov 03, 2014 12:38:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
running command: adb shell echo $EXTERNAL_STORAGE
Nov 03, 2014 12:38:12 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Applications/Android_sdk/platform-tools/adb -s bba4b0d8 shell echo $EXTERNAL_STORAGE
Nov 03, 2014 12:38:12 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /Applications/Android_sdk/platform-tools/adb -s bba4b0d8 shell ls /storage/emulated/legacy
Nov 03, 2014 12:38:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8080/wd/hub/status
Nov 03, 2014 12:38:13 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Got response status code: 200
Nov 03, 2014 12:38:13 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Got response value: {"value":{"supportedApps":[],"build":{"browserName":"selendroid","version":"0.12.0-SNAPSHOT"},"os":{"arch":"armeabi-v7a","version":"19","name":"Android"},"supportedDevices":[]},"status":0}
Nov 03, 2014 12:38:13 PM io.selendroid.server.http.ServerHandler exceptionCaught
SEVERE: Error handling request
java.lang.StackOverflowError
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.json.JSONObject.populateMap(JSONObject.java:1015)
	at org.json.JSONObject.<init>(JSONObject.java:279)
	at org.json.JSONObject.wrap(JSONObject.java:1527)
	at org.json.JSONObject.populateMap(JSONObject.java:1017)
	at org.json.JSONObject.<init>(JSONObject.java:279)
	at org.json.JSONObject.wrap(JSONObject.java:1527)
	at org.json.JSONObject.populateMap(JSONObject.java:1017)
	at org.json.JSONObject.<init>(JSONObject.java:279)
	at org.json.JSONObject.wrap(JSONObject.java:1527)
	at org.json.JSONObject.populateMap(JSONObject.java:1017)
	at org.json.JSONObject.<init>(JSONObject.java:279)
	at org.json.JSONObject.wrap(JSONObject.java:1527)
	at org.json.JSONObject.populateMap(JSONObject.java:1017)

...and so on for 200 lines or so

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
