### ISSUE TITLE
StackOverflowError with JDK8

### ISSUE THREAD

**Issue by friederbluemle** [selendroid/selendroid#678]
Trying to compile Selendroid using JDK8 results in the following error:

```
$ mvn clean install
[...]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project selendroid-server: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR]
[ERROR]
[ERROR] The system is out of resources.
[ERROR] Consult the following stack trace for details.
[ERROR] java.lang.StackOverflowError
[ERROR] at com.sun.tools.javac.comp.AttrContext.dup(AttrContext.java:103)
[ERROR] at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1737)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
[ERROR] at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607)
[ERROR] at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3254)
[...]
```

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by neoyagami** [comment]
Hi. I got this same error and fixed it passing this on MAVEN_OPTS
export MAVEN_OPTS="-Xss10m"
