### ISSUE TITLE
No session found for given sessionId

### ISSUE THREAD

**Issue by Ragnaroek** [selendroid/selendroid#688]
We are getting this error with the latest Selendroid-Release (0.12).
Test is running on a real device.

org.openqa.selenium.WebDriverException: No session found for given sessionId: null
io.selendroid.exceptions.SelendroidException: No session found for given sessionId: null
	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:49)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)

Probably related to this error in the server part:

/AndroidRuntime( 2869): CheckJNI is OFF
I/System.out( 2146): convertToJsArgs: {"ELEMENT":":wdc:1415274181315"}
I/System.out( 2146): Using timeout of 1415274222496 milli seconds.
I/System.out( 2146): find element command using 'tag name' with selector 'html'.
I/System.out( 2146): Error occurred while handling request.
W/System.err( 2146): java.lang.NullPointerException
W/System.err( 2146):    at io.selendroid.util.Preconditions.checkNotNull(Preconditions.java:191)
W/System.err( 2146):    at io.selendroid.server.model.DefaultSelendroidDriver.getSearchContext(DefaultSelendroidDriver.java:150)
W/System.err( 2146):    at io.selendroid.server.model.DefaultSelendroidDriver.findElement(DefaultSelendroidDriver.java:110)
W/System.err( 2146):    at io.selendroid.server.handler.FindElement.handle(FindElement.java:46)
W/System.err( 2146):    at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:236)
W/System.err( 2146):    at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:70)
W/System.err( 2146):    at org.webbitserver.netty.NettyHttpControl.nextHandler(NettyHttpControl.ja

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
