### ISSUE TITLE
Facing issue while installing the whatsapp applications through selendriod server .

### ISSUE THREAD

**Issue by SanthoshReddy118** [selendroid/selendroid#690]
Hi @DominikDary 

When I'm trying install whatsapp application from selendriod server its not getting installed.

Command Prompt Output:

Nov 08, 2014 12:38:23 PM io.selendroid.server.handler.ListSessionsHandler handle
INFO: list sessions command
Nov 08, 2014 12:38:33 PM io.selendroid.server.handler.CreateSessionHandler handle
INFO: new session command with capabilities: {"desiredCapabilities": {
  "aut": "com.UCMobile.intl:9.8.0",
  "automationName": "selendroid",
  "browserName": "selendroid",
  "emulator": false,
  "launchActivity": "com.UCMobile.main.UCMobile",
  "platform": "ANDROID",
  "platformName": "android",
  "platformVersion": "19"
}}
Nov 08, 2014 12:39:14 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 shell pm list packages com.UCMobile.intl
Nov 08, 2014 12:39:15 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 install -r C:\Selendriod\resigned-UC Browser.apk
Nov 08, 2014 12:39:23 PM io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
SEVERE: Error occurred while starting Selendroid session
io.selendroid.exceptions.AndroidSdkException: APK installation failed. Output:
        pkg: /data/local/tmp/resigned-UC Browser.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
4828 KB/s (13845259 bytes in 2.800s)

        at io.selendroid.android.impl.AbstractDevice.install(AbstractDevice.java:146)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:202)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)

Nov 08, 2014 12:39:30 PM io.selendroid.server.model.DeviceStore release
INFO: Releasing device HardwareDevice [serial=ZX1B32RLT8, model=XT1022, targetVersion=ANDROID19]
Nov 08, 2014 12:39:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 shell am force-stop com.UCMobile.intl
Nov 08, 2014 12:39:31 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 shell pm clear com.UCMobile.intl
Nov 08, 2014 12:39:32 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 shell pm list packages com.UCMobile.intl
Nov 08, 2014 12:39:33 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 install -r C:\Selendriod\resigned-UC Browser.apk
Nov 08, 2014 12:40:32 PM io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
SEVERE: Error occurred while starting Selendroid session
io.selendroid.exceptions.AndroidSdkException: APK installation failed. Output:
        pkg: /data/local/tmp/resigned-UC Browser.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
4792 KB/s (13845259 bytes in 2.821s)
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 install -r C:\Selendriod\resigned-UC Browser.apk

**Comment by nitikas** [comment]
ANY HELP HERE. I m facing same issue. Santosh please help.

Logs

[TestNG] Running:
  C:\Users\OWNER\AppData\Local\Temp\testng-eclipse--698844175\testng-customsuite.xml

FAILED: BookLaunch
org.openqa.selenium.SessionNotCreatedException: Error starting Selendroid session
io.selendroid.exceptions.SessionNotCreatedException: Error starting Selendroid session
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:277)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.AndroidSdkException: APK installation failed. Output:
	pkg: /data/local/tmp/resigned-PearsonEtextAndroidRUMBA.apk
Failure [INSTALL_FAILED_OLDER_SDK]
1433 KB/s (6758030 bytes in 4.603s)

	at io.selendroid.android.impl.AbstractDevice.install(AbstractDevice.java:146)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:202)
	... 25 more

Command duration or timeout: 179.17 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'OWNER-VAIO', ip: '192.168.1.43', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_17'
Driver info: io.selendroid.SelendroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:72)
	at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:84)
	at NativeApp.Native.BookLaunch(Native.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: io.selendroid.exceptions.SessionNotCreatedException: Error starting Selendroid session
io.selendroid.exceptions.SessionNotCreatedException: Error starting Selendroid session
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:277)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.AndroidSdkException: APK installation failed. Output:
	pkg: /data/local/tmp/resigned-PearsonEtextAndroidRUMBA.apk
Failure [INSTALL_FAILED_OLDER_SDK]
1433 KB/s (6758030 bytes in 4.603s)

	at io.selendroid.android.impl.AbstractDevice.install(AbstractDevice.java:146)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:202)
	... 25 more



===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@34f07ec4: 56 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@79826b7a: 39 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@6901dfa5: 10 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@368f7f42: 7 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@3b870cfc: 6 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 6 ms

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
