### ISSUE TITLE
App is not getting launched.

### ISSUE THREAD

**Issue by SanthoshReddy118** [selendroid/selendroid#692]
Hi @DominikDary 

I'm trying to install Skype apk with selendriod server in my mobile device, The application got installed but its not getting launched.

My Code is:

SelendroidConfiguration config = new SelendroidConfiguration();
		    config.setForceReinstall(true);
		    selendroidServer = new SelendroidLauncher(config);
		    selendroidServer.launchSelendroid();
		    
		    SelendroidCapabilities caps = new SelendroidCapabilities("com.skype.raider:4.9.0.45564");
		    caps.setPlatform(Platform.ANDROID);
		    caps.setEmulator(false);
		    
		    Thread.sleep(10000);
		    driver = new SelendroidDriver(caps);

And the command prompt output is:

Nov 10, 2014 1:41:59 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
running command: adb shell echo $EXTERNAL_STORAGE
Nov 10, 2014 1:42:01 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 shell echo $EXTERNAL_STORAGE
Nov 10, 2014 1:42:01 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Selendriod\Andriod SDK\sdk\platform-tools\adb.exe -s ZX1B32RLT8 shell ls C:\storage\emulated\legacy
Nov 10, 2014 1:42:01 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8087/wd/hub/status
Nov 10, 2014 1:42:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8087: Connection reset
Nov 10, 2014 1:42:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8087
Nov 10, 2014 1:42:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8087: Connection reset
Nov 10, 2014 1:42:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8087
Nov 10, 2014 1:42:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8087: Connection reset
Nov 10, 2014 1:42:01 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8087
Nov 10, 2014 1:42:01 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
        at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStandaloneDriver.java:295)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:235)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Unknown Source)

Will you please help me in sorting this issue as early.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
