### ISSUE TITLE
org.openqa.selenium.StaleElementReferenceException when revisiting a native page

### ISSUE THREAD

**Issue by operatiay** [selendroid/selendroid#698]
I know there's been this issue of not verifying native elements #28

My problem right now is that the call `driver.findElement(By.linkText("My button"))` returns with the element from the cache (I've been on the page before and am now revisiting).
When I then try to interact with the object I get the error.

the stacktrace for the error:
```
org.openqa.selenium.StaleElementReferenceException: The element with id 'cf770cca-4a33-260e-3ae1-fe9547c6ee14' was not found.
io.selendroid.exceptions.StaleElementReferenceException: The element with id 'cf770cca-4a33-260e-3ae1-fe9547c6ee14' was not found.
	at io.selendroid.server.SafeRequestHandler.getElementFromCache(SafeRequestHandler.java:50)
	at io.selendroid.server.handler.ClickElement.safeHandle(ClickElement.java:35)
	at io.selendroid.server.SafeRequestHandler.handle(SafeRequestHandler.java:83)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:319)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:841)
```
Is there a way to invalidate the cache? or is it supposed to work differently?

**Comment by vicwomg** [comment]
I'm also affected by this issue. Locators that worked in 0.12 now throw stale element exception, presumably because of caching from a previous element. All the solutions I'm seeing don't seem ideal (writing custom retry loops and overriding waits) surely there's a bug here? When would accessing a cached element be desired?

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
