### ISSUE TITLE
Unable to start session in selendroid

### ISSUE THREAD

**Issue by Sendlink** [selendroid/selendroid#701]
SelendroidCapabilities capa = SelendroidCapabilities.device(DeviceTargetPlatform.ANDROID15, "eWallet.Android:1.8");
		WebDriver driver = new SelendroidDriver(capa);

Selendroid server started successfully

C:\Users\raghuadmin1.ZENQATEST2\Downloads>java -jar selendroid-standalone-0.12.0
-with-dependencies.jar -app eWallet.Android-Signed.apk
################# Configuration in use #################
io.selendroid.SelendroidConfiguration@2f2c9b19[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[eWallet.Android-Signed.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
]
Nov 14, 2014 11:36:07 AM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/MANIFEST.MF
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/CERT.RSA
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/CERT.SF
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/ANDROIDD.SF
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/ANDROIDD.RSA
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/NDKEYSTO.SF
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\raghuadmin1.ZENQATEST2\Download
s\eWallet.Android-Signed.apk META-INF/NDKEYSTO.RSA
Nov 14, 2014 11:36:07 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner.exe -si
galg MD5withRSA -digestalg SHA1 -signedjar C:\Users\raghuadmin1.ZENQATEST2\Downl
oads\resigned-eWallet.Android-Signed.apk -storepass android -keystore C:\Users\r
aghuadmin1.ZENQATEST2\.android\debug.keystore C:\Users\raghuadmin1.ZENQATEST2\Do
wnloads\eWallet.Android-Signed.apk androiddebugkey
Nov 14, 2014 11:36:11 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a times
tamp, users may not be able to validate this jar after the signer certificate's
expiration date (2042-03-29) or after any future revocation date.

Nov 14, 2014 11:36:11 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: The app has been signed: C:\Users\raghuadmin1.ZENQATEST2\Downloads\resigne
d-eWallet.Android-Signed.apk
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe dump badging C:\Users\raghuadmin1.ZENQATEST2\Do
wnloads\resigned-eWallet.Android-Signed.apk
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe dump badging C:\Users\raghuadmin1.ZENQATEST2\Do
wnloads\resigned-eWallet.Android-Signed.apk
Nov 14, 2014 11:36:11 AM io.selendroid.server.model.SelendroidStandaloneDriver i
nitApplicationsUnderTest
INFO: App eWallet.Android:1.8 has been added to selendroid standalone server.
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/MANIFEST.MF
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/CERT.RSA
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/CERT.SF
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/ANDROIDD.SF
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/ANDROIDD.RSA
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/NDKEYSTO.SF
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\b
uild-tools\android-4.4W\aapt.exe remove C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp
\android-driver2985804848598548767.apk META-INF/NDKEYSTO.RSA
Nov 14, 2014 11:36:11 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Program Files\Java\jdk1.8.0_25\bin\jarsigner.exe -si
galg MD5withRSA -digestalg SHA1 -signedjar C:\Users\RAGHUA~1.ZEN\AppData\Local\T
emp\resigned-android-driver2985804848598548767.apk -storepass android -keystore
C:\Users\raghuadmin1.ZENQATEST2\.android\debug.keystore C:\Users\RAGHUA~1.ZEN\Ap
pData\Local\Temp\android-driver2985804848598548767.apk androiddebugkey
Nov 14, 2014 11:36:12 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: App signing output: jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a times
tamp, users may not be able to validate this jar after the signer certificate's
expiration date (2042-03-29) or after any future revocation date.

Nov 14, 2014 11:36:12 AM io.selendroid.builder.SelendroidServerBuilder signTestS
erver
INFO: The app has been signed: C:\Users\RAGHUA~1.ZEN\AppData\Local\Temp\resigned
-android-driver2985804848598548767.apk
Nov 14, 2014 11:36:16 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=HT34APG02807, model=null, targetVersion=nul
l]
Nov 14, 2014 11:36:17 AM io.selendroid.server.model.DeviceStore addDevice
INFO: Adding: HardwareDevice [serial=HT34APG02807, model=HTC Desire V, targetVer
sion=ANDROID15]
Nov 14, 2014 11:36:17 AM io.selendroid.android.impl.DefaultDeviceManager initial
izeAdbConnection
INFO: my devices: null
Nov 14, 2014 11:36:17 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\t
ools\android.bat list avds
Nov 14, 2014 11:36:17 AM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\p
latform-tools\adb.exe devices
Nov 14, 2014 11:36:17 AM io.selendroid.server.model.DeviceStore addEmulators
INFO: No emulators has been found.
selendroid-standalone server has been started on port: 4444

Below is the app id

{"value":{"os":{"name":"Windows 7","arch":"amd64","version":"6.1"},"build":{"browserName":"selendroid","version":"0.12.0"},"supportedDevices":[{"emulator":false,"screenSize":"(480, 800)","serial":"HT34APG02807","platformVersion":"15","model":"HTC Desire V"}],"supportedApps":[{"mainActivity":"io.selendroid.androiddriver.WebViewActivity","appId":"io.selendroid.androiddriver:0.12.0","basePackage":"io.selendroid.androiddriver"},{"mainActivity":"ewallet.android.activities.SplashActivity","appId":"eWallet.Android:1.8","basePackage":"eWallet.Android"}]},"status":0}

then executed

SelendroidCapabilities capa = SelendroidCapabilities.device(DeviceTargetPlatform.ANDROID15, "eWallet.Android:1.8");
		WebDriver driver = new SelendroidDriver(capa);

got following in log

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Error starting Selendroid session
io.selendroid.exceptions.SessionNotCreatedException: Error starting Selendroid session
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:277)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.SelendroidException: Selendroid server on the device didn't come up after 20sec:
	at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStandaloneDriver.java:307)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:235)
	... 25 more

Command duration or timeout: 166.67 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'WIN7ENTX64245', ip: '192.168.2.9', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: io.selendroid.SelendroidDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:72)
	at io.selendroid.SelendroidDriver.<init>(SelendroidDriver.java:84)
	at Selens.First.main(First.java:16)
Caused by: io.selendroid.exceptions.SessionNotCreatedException: Error starting Selendroid session
io.selendroid.exceptions.SessionNotCreatedException: Error starting Selendroid session
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:277)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Caused by: io.selendroid.exceptions.SelendroidException: Selendroid server on the device didn't come up after 20sec:
	at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStandaloneDriver.java:307)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:235)
	... 25 more

**Comment by nitikas** [comment]
Please help on this

**Comment by axelbarfod** [comment]
Did you delete the files inside the meta-inf folder then resign apk

**Comment by nitikas** [comment]
No
How to do that?

**Comment by axelbarfod** [comment]
Open apk file with 7 zip and delete files in meta inf folder

**Comment by nitikas** [comment]
it is not having any meta inf folder

**Comment by nitikas** [comment]
Please help

**Comment by shivakrishnach31** [comment]
I guess you need to add selendroid client jar to that project

No
How to do that?

—
Reply to this email directly or view it on GitHub
<https://github.com/selendroid/selendroid/issues/701#issuecomment-69466617>.

**Comment by nitikas** [comment]
I added selendroid client 12

**Comment by asm89** [comment]
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
