### ISSUE TITLE
Starting selendroid from gradle fails with exception

### ISSUE THREAD

**Issue by volodymyrpavlenko** [selendroid/selendroid#714]
Hi,

I'm trying to configure testing of a webview android application from a Gradle build. To achieve this, I tried adding a startSelendroidServer task, which creates a new instance of SelendroidLauncher and starts it. My tests perform app restarts (the test logic requires this). To achieve this, I perform driver.quit() and re-create the driver. Everything works fine with standalone server.
If I run it as a part of a gradle build, I get an exception during second driver creation (after the very first quit):
```
running command: adb shell setprop log.tag.SELENDROID VERBOSE
Error handling request
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:493)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
	at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:299)
	at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStandaloneDriver.java:295)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:235)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
```
If I start and stop selenium in @BeforeClass and @AfterClass methods - everything works fine.
I use the following code to start server in the gradle:
```groovy
import io.selendroid.SelendroidConfiguration
import io.selendroid.SelendroidLauncher
import io.selendroid.log.LogLevelEnum

apply plugin: 'java'

version = '1.0'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath('io.selendroid:selendroid-standalone:0.12.0')
    }
}
repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.11'
    testCompile 'io.selendroid:selendroid-standalone:0.12.0'
    testCompile 'io.selendroid:selendroid-client:0.12.0'
}

SelendroidLauncher launcher = null;

task startSeleniumServer() {
    SelendroidConfiguration conf = new SelendroidConfiguration();
    conf.setDeviceLog(false);
    conf.setLogLevel(LogLevelEnum.VERBOSE);
    conf.setNoClearData(true);
    conf.setForceReinstall(true);
    conf.addSupportedApp(rootProject.buildDir.absolutePath + "/outputs/apk/mobileapp-android-debug.apk");
    launcher = new SelendroidLauncher(conf);
    launcher.launchSelendroid();
}

test.dependsOn('startSeleniumServer')
```

Any ideas what can I be doing wrong?

Best Regards,

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
