### ISSUE TITLE
selendroid : apk install on device and open but not enter sendkeys on control 

### ISSUE THREAD

**Issue by fasiyuddin** [selendroid/selendroid#727]
Respected sir,
 i have used 
1) selenium-server-standalone-2.42.2.jar
2) selendroid-client-0.12.0.jar
3) selendroid-standalone-0.11.0-with-dependencies.jar
 and code is :
package io.selendroid.demo;

import io.selendroid.SelendroidCapabilities;
import io.selendroid.SelendroidConfiguration;
import io.selendroid.SelendroidDriver;
import io.selendroid.SelendroidLauncher;
import io.selendroid.device.DeviceTargetPlatform;
import java.net.URL;
import junit.framework.Assert;
//import org.junit.After;
//
//import org.junit.AfterClass;
//import org.junit.Assert;
//import org.junit.Before;
//import org.junit.BeforeClass;
//import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.events.EventFiringWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.*;

public class SelendroidIntegrationTest
{
    
    SelendroidLauncher selendroidServer = null;
    WebDriver driver;

    public SelendroidIntegrationTest() {
        this.driver = null;
    }
    
    @Test
    public void test() throws InterruptedException
    {
        System.out.println("testing started......");
        
        //WebDriverWait wait = new WebDriverWait(driver, 100);
       driver.switchTo().window("NATIVE_APP");
       driver.get("and-activity://io.selendroid.testapp.HomeScreenActivity");
    
        WebElement inputField = driver.findElement(By.id("my_text_field"));
       // wait.until(ExpectedConditions.visibilityOf(inputField));
        inputField.sendKeys("Selendroid");
        Assert.assertEquals("Selendroid", inputField.getText());
    }
    
    @BeforeTest
    public void startSelendroidServer() throws Exception
    {
        if (selendroidServer != null)
        {
            selendroidServer.stopSelendroid();
        }
        SelendroidConfiguration config = new SelendroidConfiguration();
        // Add the selendroid-test-app to the standalone server
        config.addSupportedApp("/mobiletesting/selendroid-test-app-0.11.0.apk");
        config.setDeviceScreenshot(true);
      //config.setPort(4444);
      //config.setEmulatorPort(8080);
        config.setSelendroidServerPort(4444);
         config.isForceReinstall();
       
         
         
        //config.setNoClearData(true);

       
        //config.getEmulatorOptions();
        
      
        selendroidServer = new SelendroidLauncher(config);
        selendroidServer.launchSelendroid();
        
              System.out.println("launchSelendroid......");
        
        SelendroidCapabilities caps= new SelendroidCapabilities("io.selendroid.testapp:0.11.0");
     
        caps.setAut("io.selendroid.testapp:0.11.0");
        //caps.setPlatformVersion(DeviceTargetPlatform.ANDROID10);
        caps.setEmulator(false);
        
        
       // caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
       // caps.wait();
   
        
             System.out.println("SelendroidCapabilities......");
             
   
             driver=new EventFiringWebDriver(new SelendroidDriver(caps));
        
     //driver = new SelendroidDriver(caps);
     // caps.wait();
     
     
                //driver = new SelendroidDriver(new SelendroidCapabilities("io.selendroid.testapp:0.11.0"));

        
        
     //driver = new SelendroidDriver(new URL("http://localhost:4444/wd/hub/status"),caps);

     
        System.out.println("SelendroidDriver......");
        
        
  
    }
    
    @AfterTest
    public void stopSelendroidServer()
    {
        if (driver != null)
        {
            driver.quit();
        }
        if (selendroidServer != null)
        {
           selendroidServer.stopSelendroid();
        }
    }
    
}

but it give error like :

Nov 29, 2014 6:33:28 PM io.selendroid.server.handler.CreateSessionHandler handle
INFO: new session command with capabilities: {"desiredCapabilities": {
  "aut": "io.selendroid.testapp:0.11.0",
  "emulator": false
}}
Nov 29, 2014 6:33:28 PM io.selendroid.server.model.DeviceStore findAndroidDevice
INFO: Evaluating if this device is a match for this session: AndroidEmulator [screenSize=320x480, targetPlatform=ANDROID19, serial=null, avdName=test_android]
Nov 29, 2014 6:33:28 PM io.selendroid.server.model.DeviceStore findAndroidDevice
INFO: Evaluating if this device is a match for this session: HardwareDevice [serial=870e2fe8, model=GT-S6312, targetVersion=ANDROID16]
Nov 29, 2014 6:33:28 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/njuser/AndroidEmuSetup/android-sdks/platform-tools/adb -s 870e2fe8 shell pm list packages io.selendroid.testapp
Nov 29, 2014 6:33:29 PM io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
INFO: the app under test is already installed.
Nov 29, 2014 6:33:29 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/njuser/AndroidEmuSetup/android-sdks/platform-tools/adb -s 870e2fe8 shell pm list packages io.selendroid.io.selendroid.testapp
Nov 29, 2014 6:33:30 PM io.selendroid.server.model.SelendroidStandaloneDriver createNewTestSession
running command: adb shell setprop log.tag.SELENDROID ERROR
INFO: selendroid-server will not be created and installed because it already exists for the app under test.
Nov 29, 2014 6:33:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/njuser/AndroidEmuSetup/android-sdks/platform-tools/adb -s 870e2fe8 shell setprop log.tag.SELENDROID ERROR
Nov 29, 2014 6:33:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/njuser/AndroidEmuSetup/android-sdks/build-tools/21.1.1/aapt dump badging /home/njuser/Desktop/mobiletesting/resigned-selendroid-test-app-0.11.0.apk
Nov 29, 2014 6:33:30 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/njuser/AndroidEmuSetup/android-sdks/platform-tools/adb -s 870e2fe8 shell am instrument -e main_activity io.selendroid.testapp.HomeScreenActivity -e server_port 4444 io.selendroid.io.selendroid.testapp/io.selendroid.ServerInstrumentation
Nov 29, 2014 6:33:31 PM io.selendroid.io.ShellCommand exec
INFO: executing command: /home/njuser/AndroidEmuSetup/android-sdks/platform-tools/adb -s 870e2fe8 forward tcp:4444 tcp:4444
io.selendroid.exceptions.ShellCommandException: An error occured while executing shell command: /home/njuser/AndroidEmuSetup/android-sdks/platform-tools/adb -s 870e2fe8 forward tcp:4444 tcp:4444
	at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
	at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevice.java:176)
	at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevice.java:171)
	at io.selendroid.android.impl.AbstractDevice.forwardPort(AbstractDevice.java:245)
	at io.selendroid.android.impl.AbstractDevice.forwardSelendroidPort(AbstractDevice.java:249)
	at io.selendroid.android.impl.AbstractDevice.startSelendroid(AbstractDevice.java:239)
	at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:294)
	at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:42)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.selendroid.exceptions.ShellCommandException: error: cannot bind to socket
error: cannot bind to socket

Please help to solve this issue.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity. If you still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
