### ISSUE TITLE
Start of selendroid-standalone

### ISSUE THREAD

**Issue by mic999** [selendroid/selendroid#755]
I know this has been up before. I have read many previous questions about it and tried the solutions but I can't get it to work. When I try to start the selendroid-standalone in Win8 it crashes because the aapt (that is now in build-tools\21.1.2\) can't be found. 

Here are some variables:
ANDROID_HOME="C:\Program Files\android_sdk\"
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_25
Path="C:\Program Files\android_sdk\";"C:\Program Files\android_sdk\build-tools\21.1.2";"C:\Program Files\android_sdk\tools";"C:\Program Files\android_
sdk\platform-tools";"C:\Program Files\Java\jdk1.8.0_25";...

I have created links from the android_home, the tools and the platform-tools folders leading to the lib folder and aapt.exe in 'build-tools\21.1.2' folder.

Here is where it crashes:

C:\Program Files\Selenium>java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app selendroid-test-app-0.12.0.apk
################# Configuration in use #################
io.selendroid.SelendroidConfiguration@2f2c9b19[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[selendroid-test-app-0.12.0.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
]
dec 15, 2014 5:57:40 EM io.selendroid.SelendroidLauncher launchServer
INFO: Starting selendroid-server port 4444
dec 15, 2014 5:57:40 EM io.selendroid.SelendroidLauncher launchServer
SEVERE: Error occurred while building server: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and t
ry again.
io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and t
ry again.
        at io.selendroid.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
        at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:47)
        at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:107)
        at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:135)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:144)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:114)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:84)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)
Exception in thread "main" io.selendroid.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the lat
est development tools and try again.
        at io.selendroid.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
        at io.selendroid.android.AndroidSdk.aapt(AndroidSdk.java:47)
        at io.selendroid.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:107)
        at io.selendroid.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:135)
        at io.selendroid.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:144)
        at io.selendroid.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:114)
        at io.selendroid.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:84)
        at io.selendroid.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:61)
        at io.selendroid.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:50)
        at io.selendroid.SelendroidLauncher.launchServer(SelendroidLauncher.java:64)
        at io.selendroid.SelendroidLauncher.main(SelendroidLauncher.java:112)

If you have any ideas about what I need to do, it is very appreciated.
Thanks,
mic

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
