### ISSUE TITLE
I have a problem after running the selendroid-standalone-0.12.0

### ISSUE THREAD

**Issue by IIkazumiII** [selendroid/selendroid#771]
When I used the code to run 
*java -jar selendroid-standalone-0.12.0-with-dependencies.jar -app "Globe SFA_20141229_v.0.15.apk"* everything seems to be fine until I check *http://localhost:4444/wd/hub/status*  I would get this log. 

Jan 07, 2015 2:36:31 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\Android\re
signed-Globe SFA_20141229_v 1.0.15.apk
Jan 07, 2015 2:37:17 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\Users\TEST
-T~1\AppData\Local\Temp\resigned-android-driver171534398016039675.apk
Jan 07, 2015 2:37:17 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\Users\TEST
-T~1\AppData\Local\Temp\resigned-android-driver171534398016039675.apk
Jan 07, 2015 2:37:17 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\build-tools\android-4.4W\aapt.exe dump badging C:\Users\TEST
-T~1\AppData\Local\Temp\resigned-android-driver171534398016039675.apk

Full Log is attached in this link
https://www.dropbox.com/s/ujurygctlhl1ugm/Selendroid%20Log.txt?dl=0

**Comment by operatiay** [comment]
I don't see a problem, those log messages are `INFO`. if something is not working (e.g. you see some `ERROR` messages), please reopen with problem description.

**Comment by IIkazumiII** [comment]
***I would get this log after running the code and it keeps on looping*** 

Jan 08, 2015 2:00:08 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF forward tcp:8081
tcp:8081
Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice startLogging
INFO: starting logcat:
Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8081/wd/hub/status
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:13
)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:15
)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClie
tConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:
71)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
        at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStand
loneDriver.java:295)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidSta
daloneDriver.java:235)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapin
Handler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:
03)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.j
va:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.ja
a:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:
16)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThread
actory.java:137)
        at java.lang.Thread.run(Unknown Source)

Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
running command: adb shell echo $EXTERNAL_STORAGE
Jan 08, 2015 2:00:10 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell echo $EXTE
NAL_STORAGE
Jan 08, 2015 2:00:10 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell ls C:\stor
ge\sdcard0
Jan 08, 2015 2:00:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8081/wd/hub/status
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:13
)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:15
)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClie
tConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:
71)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
        at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStand
loneDriver.java:295)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidSta
daloneDriver.java:235)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapin
Handler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:
03)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.j
va:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.ja
a:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:
16)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThread
actory.java:137)
        at java.lang.Thread.run(Unknown Source)

Jan 08, 2015 2:00:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
running command: adb shell echo $EXTERNAL_STORAGE
Jan 08, 2015 2:00:12 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell echo $EXTE
NAL_STORAGE
Jan 08, 2015 2:00:12 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell ls C:\stor
ge\sdcard0
Jan 08, 2015 2:00:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8081/wd/hub/status
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:13
)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:15
)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClie
tConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:
71)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
        at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStand
loneDriver.java:295)
        at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidSta
daloneDriver.java:235)
        at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
        at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
        at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
        at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapin
Handler.java:223)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:
03)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.j
va:148)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.ja
a:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:
16)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThread
actory.java:137)
        at java.lang.Thread.run(Unknown Source)

Jan 08, 2015 2:00:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
