### ISSUE TITLE
I would get this log after running the code and it keeps on looping..

### ISSUE THREAD

**Issue by IIkazumiII** [selendroid/selendroid#773]
Sorry im new at this. After I run my my test case for our app I would get this log and it keeps on repeating until it will reinstall and still the app wont open.

Jan 08, 2015 2:00:08 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF forward tcp:8081
tcp:8081
Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice startLogging
INFO: starting logcat:
Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8081/wd/hub/status
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:13
)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:15
)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:140)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:57)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClie
tConnection.java:161)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:
71)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStand
loneDriver.java:295)
at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidSta
daloneDriver.java:235)
at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapin
Handler.java:223)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:
03)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.j
va:148)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.ja
a:125)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:
16)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThread
actory.java:137)
at java.lang.Thread.run(Unknown Source)

Jan 08, 2015 2:00:08 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
running command: adb shell echo $EXTERNAL_STORAGE
Jan 08, 2015 2:00:10 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell echo $EXTE
NAL_STORAGE
Jan 08, 2015 2:00:10 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell ls C:\stor
ge\sdcard0
Jan 08, 2015 2:00:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8081/wd/hub/status
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:13
)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:15
)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:140)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:57)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClie
tConnection.java:161)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:
71)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStand
loneDriver.java:295)
at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidSta
daloneDriver.java:235)
at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapin
Handler.java:223)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:
03)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.j
va:148)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.ja
a:125)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:
16)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThread
actory.java:137)
at java.lang.Thread.run(Unknown Source)

Jan 08, 2015 2:00:10 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started
running command: adb shell echo $EXTERNAL_STORAGE
Jan 08, 2015 2:00:12 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell echo $EXTE
NAL_STORAGE
Jan 08, 2015 2:00:12 PM io.selendroid.io.ShellCommand exec
INFO: executing command: C:\Android\sdk\platform-tools\adb.exe -s 0123456789ABCDEF shell ls C:\stor
ge\sdcard0
Jan 08, 2015 2:00:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Using url: http://localhost:8081/wd/hub/status
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://localho
t:8081: Connection reset
Jan 08, 2015 2:00:12 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8081
Jan 08, 2015 2:00:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Error checking if selendroid-server has started.
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:13
)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:15
)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:140)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.
ava:57)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClie
tConnection.java:161)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:
71)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at io.selendroid.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:305)
at io.selendroid.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStand
loneDriver.java:295)
at io.selendroid.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidSta
daloneDriver.java:235)
at io.selendroid.server.handler.CreateSessionHandler.handle(CreateSessionHandler.java:44)
at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapin
Handler.java:223)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:
03)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.j
va:148)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerC
ntext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCon
ext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.ja
a:125)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:
16)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThread
actory.java:137)
at java.lang.Thread.run(Unknown Source)

Jan 08, 2015 2:00:12 PM io.selendroid.android.impl.AbstractDevice isSelendroidRunning
INFO: Assuming server has not started

**Comment by operatiay** [comment]
have you got something else running on localhost:8081?

**Comment by IIkazumiII** [comment]
I already checked but no I didnt run anything else on that port.. is this maybe because of my code or maybe my app?

**Comment by jankowskirobert** [comment]
or maybe you use adb in other proces and it is listening your device. I had similar situation when i opened eclipse and android studio

**Comment by IIkazumiII** [comment]
So what did you do mr jankowskirobert? Sorry Im really new at this.. and badly need help

**Comment by jankowskirobert** [comment]
I shut down one of the IDE, i only use Eclipse or IDEA/Android Studio but never both in same time. If it will not help then try uninstall manually your apk on device. Probably this could be problem with androidmainfest

**Comment by asm89** [comment]
I'm closing this issue due to inactivity. If you still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
