### ISSUE TITLE
Error building server: Command 'aapt' was not found inside the Android SDK while installing selendroid

### ISSUE THREAD

**Issue by neetika-gahlot** [selendroid/selendroid#794]
Hi,
I want to automate the testing of my app via selendroid, although I have set the Java_Home variable as:
/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
and ANDROID_HOME as:
/desktop/adt-bundle-mac-x86_64-20140702/sdk
updated the Android SDK and Android Support Library. I am still unable to configure selendroid on my system because of this error:

Macintosh-3:desktop mac_osx$ java -jar selendroid-standalone-0.13.0-with-dependencies.jar -app selendroid-test-app-0.13.0.apk
Jan 31, 2015 3:58:32 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Jan 31, 2015 3:58:32 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Configuration in use #################
Jan 31, 2015 3:58:32 PM io.selendroid.standalone.SelendroidLauncher main
INFO: io.selendroid.standalone.SelendroidConfiguration@522a4983[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[selendroid-test-app-0.13.0.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
]
Jan 31, 2015 3:58:32 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Jan 31, 2015 3:58:32 PM io.selendroid.standalone.SelendroidLauncher launchServer
SEVERE: Error building server: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
Exception in thread "main" io.selendroid.server.common.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK. Please update to the latest development tools and try again.
	at io.selendroid.standalone.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:118)
	at io.selendroid.standalone.android.AndroidSdk.aapt(AndroidSdk.java:47)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:107)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:135)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:144)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:65)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:54)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

Can please anyone suggest me what did I forget to do to use Selendroid.
Thanks in advance.

**Comment by sumitbera** [comment]
You can refer this if the issue is not resolved
https://github.com/selendroid/selendroid/issues/899

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by ajithlooyi** [comment]
I am facing the below error:

**_Jun 22, 2018 1:08:27 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Selendroid #################
Jun 22, 2018 1:08:27 PM io.selendroid.standalone.SelendroidLauncher main
INFO: ################# Configuration in use #################
Jun 22, 2018 1:08:27 PM io.selendroid.standalone.SelendroidLauncher main
INFO: io.selendroid.standalone.SelendroidConfiguration@31cefde0[
  port=4444
  timeoutEmulatorStart=300000
  supportedApps=[app-release.apk]
  verbose=false
  emulatorPort=5560
  deviceScreenshot=false
  selendroidServerPort=8080
  keystore=<null>
  keystorePassword=<null>
  keystoreAlias=<null>
  emulatorOptions=<null>
  keepEmulator=false
  registrationUrl=<null>
  proxy=<null>
  serverHost=<null>
  keepAdbAlive=false
  maxSession=5
  maxInstances=5
  registerCycle=0
  noWebViewApp=false
  noClearData=false
  sessionTimeoutSeconds=1800
  forceReinstall=false
  logLevel=ERROR
  deviceLog=true
  serverStartTimeout=20000
  printHelp=false
  serverStartRetries=5
  folder=<null>
  deleteTmpFiles=true
]
Jun 22, 2018 1:08:27 PM io.selendroid.standalone.SelendroidLauncher launchServer
INFO: Starting Selendroid standalone on port 4444
Jun 22, 2018 1:08:27 PM io.selendroid.standalone.SelendroidLauncher launchServer
SEVERE: Error building server: Command 'aapt' was not found inside the Android SDK: /home/ajith/home/ajith/android_linux_sdk/build-tools. Please update to the latest development tools and try again.
Exception in thread "main" io.selendroid.server.common.exceptions.SelendroidException: Command 'aapt' was not found inside the Android SDK: /home/ajith/home/ajith/android_linux_sdk/build-tools. Please update to the latest development tools and try again.
	at io.selendroid.standalone.android.AndroidSdk.findLatestAndroidPlatformFolder(AndroidSdk.java:119)
	at io.selendroid.standalone.android.AndroidSdk.aapt(AndroidSdk.java:48)
	at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:107)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
	at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:142)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.addToAppsStore(SelendroidStandaloneDriver.java:121)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:155)
	at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
	at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
	at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
	at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)_**


Please let me know what should i do ?
