### ISSUE TITLE
localhost:8080 failed to respond error 

### ISSUE THREAD

**Issue by niranjani23** [selendroid/selendroid#808]
Hello Dominik,

My test seems to be running fine but I still see the following exception being thrown:  Am using the latest stable version of the snapshot: 0.13.0.Am able to run this test on emulator but doesn't run on device.  Any thoughts on why this is happening? 

INFO: Error checking if selendroid-server has started.

org.apache.http.NoHttpResponseException: localhost:8080 failed to respond

at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)

at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)

at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)

at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)

at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)

at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)

at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)

at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)

at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)

at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)

at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)

at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)

at io.selendroid.standalone.android.impl.AbstractDevice.isSelendroidRunning(AbstractDevice.java:314)

at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.waitForServerStart(SelendroidStandaloneDriver.java:328)

at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:265)

at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.createNewTestSession(SelendroidStandaloneDriver.java:210)

at io.selendroid.standalone.server.handler.CreateSessionHandler.handleRequest(CreateSessionHandler.java:40)

at io.selendroid.standalone.server.BaseSelendroidStandaloneHandler.handle(BaseSelendroidStandaloneHandler.java:45)

**Comment by DominikDary** [comment]
Hi @niranjani23 

maybe your selendroid-server on the device is not the right one. have you tried to start the selendroid-standalone server with `-force-reinstall`?

**Comment by niranjani23** [comment]
Is there a way to start the selendroid-standalone server from my code? Or
do I have to give it from the command line? Could you pls specify the
complete command?

On Wed, Feb 18, 2015 at 11:09 AM, Dominik Dary <notifications@github.com>
wrote:

> Hi @niranjani23 <https://github.com/niranjani23>
>
> maybe your selendroid-server on the device is not the right one. have you
> tried to start the selendroid-standalone server with -force-reinstall?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/selendroid/selendroid/issues/808#issuecomment-74926590>
> .
>



-- 




Regards,
Niranjani Manoharan

**Comment by lukeis** [comment]
here's selendroid's tests that startup the standalone from code:

https://github.com/selendroid/selendroid/blob/master/selendroid-test-app/src/test/java/io/selendroid/support/BaseAndroidTest.java#L39-L40

and

https://github.com/selendroid/selendroid/blob/master/selendroid-test-app/src/test/java/io/selendroid/support/BaseAndroidTest.java#L109-L112


since there doesn't appear to be any real issue here, i'm going to close this issue
