### ISSUE TITLE
DOMElementException wile getPageSource

### ISSUE THREAD

**Issue by aluedeke** [selendroid/selendroid#809]
Hey,

i am getting the following exception when testing my hybrid cordova app:

E/SELENDROID(  502): io.selendroid.server.handler.SafeRequestHandler#handle:111 - Exception while handling action in: io.selendroid.server.handler.LogElementTree
E/SELENDROID(  502): org.w3c.dom.DOMException: 
E/SELENDROID(  502): 	at org.apache.harmony.xml.dom.NodeImpl.setName(NodeImpl.java:286)
E/SELENDROID(  502): 	at org.apache.harmony.xml.dom.ElementImpl.<init>(ElementImpl.java:56)
E/SELENDROID(  502): 	at org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:344)
E/SELENDROID(  502): 	at org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:48)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:70)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlNode(JsonXmlUtil.java:98)
E/SELENDROID(  502): 	at io.selendroid.server.model.internal.JsonXmlUtil.buildXmlDocument(JsonXmlUtil.java:42)
E/SELENDROID(  502): 	at io.selendroid.server.inspector.TreeUtil.getXMLSource(TreeUtil.java:99)
E/SELENDROID(  502): 	at io.selendroid.server.model.DefaultSelendroidDriver.getWindowSource(DefaultSelendroidDriver.java:506)
E/SELENDROID(  502): 	at io.selendroid.server.handler.LogElementTree.safeHandle(LogElementTree.java:31)
E/SELENDROID(  502): 	at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:87)
E/SELENDROID(  502): 	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)
E/SELENDROID(  502): 	at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)
E/SELENDROID(  502): 	at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
E/SELENDROID(  502): 	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
E/SELENDROID(  502): 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
E/SELENDROID(  502): 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
E/SELENDROID(  502): 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
E/SELENDROID(  502): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
E/SELENDROID(  502): 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
E/SELENDROID(  502): 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
E/SELENDROID(  502): 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
E/SELENDROID(  502): 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
E/SELENDROID(  502): 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
E/SELENDROID(  502): 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
E/SELENDROID(  502): 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
E/SELENDROID(  502): 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
E/SELENDROID(  502): 	at java.lang.Thread.run(Thread.java:818)
I/SELENDROID(  502): io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 257 tx_bytes 913

What is also weared is that it doesn't provide a WEBVIEW context. Any Ideas?

**Comment by aluedeke** [comment]
Might be related to the fact that the WebView was not debuggable.
