### ISSUE TITLE
Concurrent access to KnownElements ends up in ConcurrentModificationException

### ISSUE THREAD

**Issue by aluedeke** [selendroid/selendroid#815]
Hey,

i just wrote a simple test case for a native app. The code is linear and has no concurrency. I am using Appium Client and Appium Server in front of Selendroid. 

Although i wouldn't expect any concurrency i got randomly the following exceptions:

''
Command duration or timeout: 30 milliseconds
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'aluedeke', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-46-generic', java.version: '1.8.0_31'
Driver info: com.getyourguide.appium.util.SelendroidDriver
Capabilities [{app=/home/aluedeke/Development/source/appium/gyg/src/test/resources/getyourguide-alpha.apk, rotatable=true, networkConnectionEnabled=true, warnings={}, handlesAlerts=true, deviceName=selendroid, version=0.12.0, platform=ANDROID, desired={app=/home/aluedeke/Development/source/appium/gyg/src/test/resources/getyourguide-alpha.apk, automationName=Selendroid, platformName=Android, deviceName=selendroid}, acceptSslCerts=true, platformVersion=21, automationName=selendroid, takesScreenshot=true, browserName=selendroid, javascriptEnabled=true, platformName=android}]
Session ID: a3ce0ae2-d9ea-204c-3271-dc7438dbfd8e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:185)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:459)
	at com.getyourguide.screens.GetYourGuide.quit(GetYourGuide.java:94)
	at com.getyourguide.tests.SmokeTest.tearDown(SmokeTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException: null
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$EntryIterator.next(HashMap.java:824)
	at java.util.HashMap$EntryIterator.next(HashMap.java:822)
	at io.selendroid.server.model.KnownElements.getCacheKey(KnownElements.java:107)
	at io.selendroid.server.model.KnownElements.add(KnownElements.java:31)
	at io.selendroid.server.model.internal.AbstractNativeElementContext.newAndroidElement(AbstractNativeElementContext.java:97)
	at io.selendroid.server.model.internal.AbstractNativeElementContext.addChildren(AbstractNativeElementContext.java:161)
	at io.selendroid.server.model.internal.AbstractNativeElementContext.addChildren(AbstractNativeElementContext.java:166)
	at io.selendroid.server.model.internal.AbstractNativeElementContext.addChildren(AbstractNativeElementContext.java:166)
	at io.selendroid.server.model.internal.AbstractNativeElementContext.getElementTree(AbstractNativeElementContext.java:123)
	at io.selendroid.server.model.SelendroidNativeDriver.getWindowSource(SelendroidNativeDriver.java:69)
	at io.selendroid.server.model.DefaultSelendroidDriver.getWindowSource(DefaultSelendroidDriver.java:503)
	at io.selendroid.server.handler.LogElementTree.safeHandle(LogElementTree.java:33)
	at io.selendroid.server.SafeRequestHandler.handle(SafeRequestHandler.java:83)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:319)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:818)'
'''

I can provide a fix which changes cache in ConcurrentHashMap but i would like to understand first why something is invoked concurrently there. any ideas?

**Comment by aluedeke** [comment]
@lukeis any ideas why there could be concurrency in place?

**Comment by lukeis** [comment]
@aluedeke I can't tell what version of selendroid you are using. It looks like a custom version... since KnownElements hasn't had over 106 lines in any release (and yet your stack trace references line 107).

Can you please try to reproduce this using the latest Selendroid standalone server. We can not debug / ensure appium isn't making concurrent calls to the selendroid-server and that might mean it's a bug in appium.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity. If you still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
