### ISSUE TITLE
Error occured while communicating with selendroid server on the device

### ISSUE THREAD

**Issue by SunitaMK** [selendroid/selendroid#838]
Hi,

I am trying to run test script but I am facing following issue.
org.openqa.selenium.WebDriverException: Error occured while communicating with selendroid server on the device: 
io.selendroid.exceptions.SelendroidException: Error occured while communicating with selendroid server on the device: 
	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:74)
	at io.selendroid.server.SelendroidServlet.handleRequest(SelendroidServlet.java:143)
	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at character 0
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at io.selendroid.server.util.HttpClientUtil.parseJsonResponse(HttpClientUtil.java:57)
	at io.selendroid.server.handler.RequestRedirectHandler.redirectRequest(RequestRedirectHandler.java:121)
	at io.selendroid.server.handler.RequestRedirectHandler.handle(RequestRedirectHandler.java:64)

*******************************************

When I checked in actual ADB logcat I am getting following error

 java.lang.IllegalArgumentException: expected receiver of type android.view.WindowManagerImpl, but got java.util.HashMap

W/System.err( 4029): 	at java.lang.reflect.Field.getField(Native Method)

W/System.err( 4029): 	at java.lang.reflect.Field.get(Field.java:269)

W/System.err( 4029): 	at io.selendroid.android.ViewHierarchyAnalyzer.getTopLevelViews(ViewHierarchyAnalyzer.java:70)

W/System.err( 4029): 	at io.selendroid.server.model.DefaultSelendroidDriver$NativeSearchScope.getTopLevelViews(DefaultSelendroidDriver.java:469)

W/System.err( 4029): 	at io.selendroid.server.model.internal.AbstractNativeElementContext.findElementsById(AbstractNativeElementContext.java:274)

W/System.err( 4029): 	at io.selendroid.server.model.internal.AbstractNativeElementContext.findElementById(AbstractNativeElementContext.java:260)

W/System.err( 4029): 	at io.selendroid.server.model.internal.AbstractNativeElementContext.findElement(AbstractNativeElementContext.java:194)

W/System.err( 4029): 	at io.selendroid.server.model.By$ById.findElement(By.java:68)

W/System.err( 4029): 	at io.selendroid.server.model.DefaultSelendroidDriver.findElement(DefaultSelendroidDriver.java:118)

W/System.err( 4029): 	at io.selendroid.server.handler.FindElement.handle(FindElement.java:47)

W/System.err( 4029): 	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:301)

W/System.err( 4029): 	at io.selendroid.server.BaseServlet.handleHttpRequest(BaseServlet.java:67)

W/System.err( 4029): 	at io.selendroid.server.http.ServerHandler.channelRead(ServerHandler.java:50)

W/System.err( 4029): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

W/System.err( 4029): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

W/System.err( 4029): 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

W/System.err( 4029): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

W/System.err( 4029): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

W/System.err( 4029): 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)

W/System.err( 4029): 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)

W/System.err( 4029): 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

W/System.err( 4029): 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

W/System.err( 4029): 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)

W/System.err( 4029): 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)

W/System.err( 4029): 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)

W/System.err( 4029): 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)

W/System.err( 4029): 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)

W/System.err( 4029): 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)

W/System.err( 4029): 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

W/System.err( 4029): 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)

W/System.err( 4029): 	at java.lang.Thread.run(Thread.java:856)

E/SELENDROID( 4029): io.selendroid.util.SelendroidLogger#error:22 - Error occurred while handling request.: null

************************************************************************
I am running my test app on Android 4.0.3 version - API 15 

Please help me to resolve this issue.

**Comment by SunitaMK** [comment]
Hi @DominikDary , Could you please help me to resolve this issue
I am still getting 
SELENDROID( 6830): io.selendroid.server.android.ViewHierarchyAnalyzer#getTopLevelViews:76 - Cannot get top level views

E/SELENDROID( 6830): java.lang.IllegalArgumentException: expected receiver of type android.view.WindowManagerImpl, but got java.util.HashMap

E/SELENDROID( 6830): 	at java.lang.reflect.Field.getField(Native Method)

E/SELENDROID( 6830): 	at java.lang.reflect.Field.get(Field.java:269)

**Comment by omkarwani** [comment]
I am getting the same problem...anything i can do to resolve it??

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
