### ISSUE TITLE
selendroidDriver.readCallLog() fails with ClassCastException

### ISSUE THREAD

**Issue by NamrataBagerwal** [selendroid/selendroid#855]
Hi all, while getting call log details I am getting the following exception. 

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at io.selendroid.client.SelendroidDriver.readCallLog(SelendroidDriver.java:255)
	at com.spec.selendroidtestappdemo.nativetests.AddCallLogTest.addCallLogTest(AddCallLogTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

It fails internally in the following snippet:

public List<CallLogEntry> readCallLog() {
        
    String callLogString = null;  
    try {
        callLogString = (String)execute("readCallLog").getValue(); //fails here
        JSONArray json = new JSONArray(callLogString);
        List<CallLogEntry> logEntries = new ArrayList<CallLogEntry>(json.length());
        for(int i=0; i < json.length(); i++) {
            logEntries.add(CallLogEntry.fromJson(json.getString(i)));
        }
        return logEntries;
    }
    catch(JSONException e) {
        throw new IllegalStateException("Unable to parse CallLogEntry from json " + callLogString);
    }
  }

Can somebody please help me to get a workaround ? Or this should be considered a bug?

**Comment by NamrataBagerwal** [comment]
I wrote a workaround for this by implementing my own MySelendroidDriver class extending SelendroidDriver and overriding readCallLog  method. I simply changed 
 
callLogString = (String)execute("readCallLog").getValue(); //fails here      from
callLogString = String.valueOf(execute("readCallLog").getValue());  
 
Now it works fine without any crash. I think this workaround should be merged!

**Comment by DominikDary** [comment]
Hi @NamrataBagerwal,

interesting. Can you provide a Pull request with a fix?

Thanks!

**Comment by asm89** [comment]
Fixed in https://github.com/selendroid/selendroid/commit/4b637950ae1cbd1b5c1e904134b508127c9ddaa8.
