### ISSUE TITLE
sendKeys() not working in Seledroid

### ISSUE THREAD

**Issue by prasad1480** [selendroid/selendroid#872]
When we enter any text in text field then I am getting following error "CATCH_ALL: java.lang.NumberFormatException:invalid int 51.375

Can you please help me out

I am running selenium webdriver scripts in Samsung S5 device

**Comment by lukeis** [comment]
please provide some sort of reproducible scenario... just an exception message like this is not much to go on.

Although it may have been fixed recently with this commit:
85c479cc034c1e6b025a823ce82e8f02f820533b

**Comment by prasad1480** [comment]
I am filling one application form & I am calling all the values from the excel sheet. It is working fine for drop down values but only problem comes when it will enter in to text field.

I am using seledroid server & client 0.15.0, System: windows 32 bit

**Comment by prasad1480** [comment]
Caused by: java.lang.NumberFormatException: CATCH_ALL: java.lang.NumberFormatException: Invalid int: "51.375"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at io.selendroid.server.model.AndroidWebElement.getCenterCoordinates(AndroidWebElement.java:233)
	at io.selendroid.server.model.AndroidWebElement.click(AndroidWebElement.java:249)
	at io.selendroid.server.model.AndroidWebElement.sendKeys(AndroidWebElement.java:121)
	at io.selendroid.server.model.AndroidWebElement.enterText(AndroidWebElement.java:113)
	at io.selendroid.server.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:44)
	at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:87)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)
	at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:818)

**Comment by lukeis** [comment]
thanks for the stacktrace, and yes, your issue is fixed with the commit i refereneced before. Either build from source and use that or wait for the next release.

**Comment by prasad1480** [comment]
Can I know when the new release will come
