### ISSUE TITLE
Selendroid crash at CaptureScreenshot

### ISSUE THREAD

**Issue by esoests** [selendroid/selendroid#874]
I am using Selendroid 0.13.0 integrated in Appium, and the Selendroid crashes when it tries to check alert using CaptureScreenshot and it's the logic within Selendroid,
**This is the log from logcat**:

71587
I/SELENDROID(13476): io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:647 - checking currentAlertMessage: 0
I/SELENDROID(13476): io.selendroid.server.handler.GetCurrentUrl#safeHandle:31 - get current URL command
I/SELENDROID(13476): io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 14086 tx_bytes 71670
I/SELENDROID(13476): io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:647 - checking currentAlertMessage: 0
I/SELENDROID(13476): io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 14086 tx_bytes 71795
I/SELENDROID(13476): io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:647 - checking currentAlertMessage: 0
I/SELENDROID(13476): io.selendroid.server.handler.script.ExecuteScript#safeHandle:37 - execute script command
I/SELENDROID(13476): io.selendroid.server.model.SelendroidWebDriver#convertToJsArgs:105 - convertToJsArgs: 
I/SELENDROID(13476): io.selendroid.server.AndroidServlet#handleRequest:295 - traffic_stats: rx_bytes 14152 tx_bytes 71879
I/SELENDROID(13476): io.selendroid.server.model.SelendroidWebDriver#isAlertPresent:647 - checking currentAlertMessage: 0
I/SELENDROID(13476): io.selendroid.server.handler.CaptureScreenshot#safeHandle:32 - take screenshot command
D/dalvikvm(13476): GC_FOR_ALLOC freed 350K, 13% free 11664K/13328K, paused 25ms, total 25ms
I/dalvikvm-heap(13476): Grow heap (frag case) to 26.556MB for 15769616-byte allocation
D/dalvikvm(13476): GC_FOR_ALLOC freed <1K, 6% free 27063K/28732K, paused 23ms, total 23ms
W/ResourceType(13476): No package identifier when getting value for resource number 0x00000000
D/AndroidRuntime(13476): Shutting down VM
W/dalvikvm(13476): threadid=1: thread exiting with uncaught exception (group=0x41afcba8)
I/SELENDROID(13476): io.selendroid.server.UncaughtExceptionHandling$ExceptionDumper#uncaughtException:52 - Process has crashed, log has been written to: /storage/emulated/0/appcrash.log

**And the appcrash.log is**:
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.Resources.getValue(Resources.java:1123)
	at android.content.res.Resources.getDrawable(Resources.java:698)
	at io.selendroid.server.model.DefaultSelendroidDriver$1.run(DefaultSelendroidDriver.java:292)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5001)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)

**Checked the code in Selendroid**:
https://github.com/selendroid/selendroid/blob/0.13.0/selendroid-server/src/main/java/io/selendroid/server/model/DefaultSelendroidDriver.java#L292

Seems it tries to get some resource and the resource is not found.

**Comment by esoests** [comment]
Can anyone help take a look?

**Comment by operatiay** [comment]
can you please try reproducing it with pure selendroid?
what steps are needed to reproduce it?

**Comment by esoests** [comment]
This happens 100% on a particular test case, also repro on another appium version with Selendroid 0.10.0.
SelendroidDrvier is trying to get Resource ID #0x0 within Selendroid, not in my testApp. 
Our test steps do some operation in webview and sign in an account. After completed signin and redirects to the previous webview, the error will occurs. 

And maybe figure out why captureScreenShot is called can give a clue what's happening, since captureScreenShot is not called after every test step.

**Comment by operatiay** [comment]
could you please provide a test case to reproduce it? (using pure selendroid).

maybe someone else is able to see what's going wrong in this version based on your stack trace, for me it's not enough.

**Comment by asm89** [comment]
I'm closing this issue due to inactivity. If you still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
