### ISSUE TITLE
On Windows7 Build Failed : io.selendroid.server.common.SelendroidResponseTest

### ISSUE THREAD

**Issue by atobulredy** [selendroid/selendroid#901]
Hi,

I am trying to build the repository myself and adding some other extra things on it
I am getting failure message as per below.

C:\Recorder\selendroid-0.15.0>mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] selendroid
[INFO] android-driver-app
[INFO] selendroid-server-common
[INFO] selendroid-server
[INFO] selendroid-grid-plugin
[INFO] selendroid-common
[INFO] selendroid-standalone
[INFO] selendroid-client
[INFO] selendroid-test-app
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building selendroid 0.15.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ selendroid ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ selendroid ---
[INFO] Installing C:\Recorder\selendroid-0.15.0\pom.xml to C:\Users\op826782\.m2\repository\io\selendroid\selendroid\0.15.0\selendroid-0.15.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building android-driver-app 0.15.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ android-driver-app ---
[INFO] Deleting C:\Recorder\selendroid-0.15.0\android-driver\target
[INFO]
[INFO] --- android-maven-plugin:4.1.1:generate-sources (default-generate-sources) @ android-driver-app ---
[INFO] Manifest copied from C:\Recorder\selendroid-0.15.0\android-driver\AndroidManifest.xml to C:\Recorder\selendroid-0.15.0\android-driver\target\AndroidManifest.xml
[INFO] Extracting libs
[INFO] Generating R file for io.selendroid:android-driver-app:apk:0.15.0
[INFO] Adding R gen folder to compile classpath: C:\Recorder\selendroid-0.15.0\android-driver\target\generated-sources\r
[INFO] Adding AIDL gen folder to compile classpath: C:\Recorder\selendroid-0.15.0\android-driver\target\generated-sources\aidl
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ android-driver-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Recorder\selendroid-0.15.0\android-driver\src\main\resources
[INFO]
[INFO] --- android-maven-plugin:4.1.1:manifest-update (update-manifest) @ android-driver-app ---
[INFO] Attempting to update manifest C:\Recorder\selendroid-0.15.0\android-driver\target\AndroidManifest.xml
[INFO] Testing if node application is application
[INFO] No changes found to write to manifest file
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ android-driver-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Recorder\selendroid-0.15.0\android-driver\target\classes
[INFO]
[INFO] --- android-maven-plugin:4.1.1:emma (default-emma) @ android-driver-app ---
[INFO]
[INFO] --- android-maven-plugin:4.1.1:proguard (default-proguard) @ android-driver-app ---
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ android-driver-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Recorder\selendroid-0.15.0\android-driver\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ android-driver-app ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ android-driver-app ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- android-maven-plugin:4.1.1:dex (default-dex) @ android-driver-app ---
[INFO] Convert classes to Dex : C:\Recorder\selendroid-0.15.0\android-driver\target\classes.dex
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ android-driver-app ---
[INFO] Building jar: C:\Recorder\selendroid-0.15.0\android-driver\target\android-driver-app-0.15.0.jar
[INFO]
[INFO] --- android-maven-plugin:4.1.1:apk (default-apk) @ android-driver-app ---
[INFO] Generating debug apk.
[INFO] C:\Recorder\selendroid-0.15.0\android-driver\res\drawable-mdpi\icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[INFO] C:\Recorder\selendroid-0.15.0\android-driver\res\drawable-hdpi\icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
[INFO] Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.
[INFO] Adding native libraries : [C:\Recorder\selendroid-0.15.0\android-driver\target\ndk-libs]
[INFO]
[INFO] --- android-maven-plugin:4.1.1:internal-pre-integration-test (default-internal-pre-integration-test) @ android-driver-app ---
[INFO] maven.skip.tests set - skipping tests
[INFO]
[INFO] --- android-maven-plugin:4.1.1:internal-integration-test (default-internal-integration-test) @ android-driver-app ---
[INFO] maven.skip.tests set - skipping tests
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ android-driver-app ---
[INFO] Installing C:\Recorder\selendroid-0.15.0\android-driver\target\android-driver-app-0.15.0.apk to C:\Users\op826782\.m2\repository\io\selendroid\android-driver-app\0.15.0\android-driver-app-0.15.0.apk
[INFO] Installing C:\Recorder\selendroid-0.15.0\android-driver\pom.xml to C:\Users\op826782\.m2\repository\io\selendroid\android-driver-app\0.15.0\android-driver-app-0.15.0.pom
[INFO] Installing C:\Recorder\selendroid-0.15.0\android-driver\target\android-driver-app-0.15.0.jar to C:\Users\op826782\.m2\repository\io\selendroid\android-driver-app\0.15.0\android-driver-app-0.15.0.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building selendroid-server-common 0.15.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ selendroid-server-common ---
[INFO] Deleting C:\Recorder\selendroid-0.15.0\selendroid-server-common\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ selendroid-server-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Recorder\selendroid-0.15.0\selendroid-server-common\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ selendroid-server-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 35 source files to C:\Recorder\selendroid-0.15.0\selendroid-server-common\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ selendroid-server-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Recorder\selendroid-0.15.0\selendroid-server-common\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ selendroid-server-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Recorder\selendroid-0.15.0\selendroid-server-common\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ selendroid-server-common ---
[INFO] Surefire report directory: C:\Recorder\selendroid-0.15.0\selendroid-server-common\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.selendroid.server.common.SelendroidResponseTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec <<< FAILURE!
testRenderUnknownError(io.selendroid.server.common.SelendroidResponseTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertTrue(Assert.java:54)
        at io.selendroid.server.common.SelendroidResponseTest.testRenderUnknownError(SelendroidResponseTest.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testRenderCatchAllError(io.selendroid.server.common.SelendroidResponseTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertTrue(Assert.java:54)
        at io.selendroid.server.common.SelendroidResponseTest.testRenderCatchAllError(SelendroidResponseTest.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   testRenderUnknownError(io.selendroid.server.common.SelendroidResponseTest)
  testRenderCatchAllError(io.selendroid.server.common.SelendroidResponseTest)

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] selendroid ......................................... SUCCESS [  0.156 s]
[INFO] android-driver-app ................................. SUCCESS [  7.167 s]
[INFO] selendroid-server-common ........................... FAILURE [  1.407 s]
[INFO] selendroid-server .................................. SKIPPED
[INFO] selendroid-grid-plugin ............................. SKIPPED
[INFO] selendroid-common .................................. SKIPPED
[INFO] selendroid-standalone .............................. SKIPPED
[INFO] selendroid-client .................................. SKIPPED
[INFO] selendroid-test-app ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.431 s
[INFO] Finished at: 2015-06-22T15:37:29+05:30
[INFO] Final Memory: 25M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project selendroid-server-common: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Recorder\selendroid-0.15.0\selendroid-server-common\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :selendroid-server-common
C:\Recorder\selendroid-0.15.0>

Please let me know whether i can be able to build the repository with in windows OS or NOT ?

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
