### ISSUE TITLE
Next slide is not loaded in App 

### ISSUE THREAD

**Issue by 5654566** [selendroid/selendroid#907]
Hi All,
I am new seledroid and i am not able to load next slide in my app. 

Here is my script

WebDriverWait wait = new WebDriverWait(driver, 60);
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("heroGetYourOfferButton")));  
	    driver.findElement(By.linkText("Get your offer")).click();
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("2012"))).click();
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Acura"))).click();
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("MDX"))).click();	      
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Base"))).click();
	    TimeUnit.SECONDS.sleep(5);
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("I have clean  title."))).click();

While wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Base"))).click(); is clicked,Next slide is not loaded and app is crashed.

Here is log 

W/ActivityManager(  294): Error in app com.peddle.seller running instrumentation
 ComponentInfo{io.selendroid.com.peddle.seller/io.selendroid.ServerInstrumentati
on}:
W/ActivityManager(  294):   java.lang.IllegalAccessError
W/ActivityManager(  294):   java.lang.IllegalAccessError: Class ref in pre-verif
ied class resolved to unexpected implementation
I/ActivityManager(  294): Force stopping package com.peddle.seller appid=10047 u
ser=0
I/ActivityManager(  294): Killing proc 934:com.peddle.seller/u0a10047: force sto
p com.peddle.seller
W/ActivityManager(  294): Force removing ActivityRecord{41223548 u0 com.peddle.s
eller/.VehicleInfoActivity}: app died, no saved state
I/WindowState(  294): WIN DEATH: Window{40f6b588 u0 com.peddle.seller/com.peddle
.seller.VehicleInfoActivity}
Jun 26, 2015 4:06:10 PM io.selendroid.SelendroidLauncher$1 run
INFO: Shutting down Selendroid standalone
io.selendroid.exceptions.ShellCommandException: An error occured while executing
 shell command: D:\SDK\platform-tools\adb.exe -s emulator-5554 shell am force-st
op com.peddle.seller
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevi
ce.java:176)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevi
ce.java:171)
        at io.selendroid.android.impl.AbstractDevice.kill(AbstractDevice.java:20
6)
        at io.selendroid.server.model.DeviceStore.release(DeviceStore.java:75)
        at io.selendroid.server.model.SelendroidStandaloneDriver.stopSession(Sel
endroidStandaloneDriver.java:464)
        at io.selendroid.server.model.SelendroidStandaloneDriver.quitSelendroid(
SelendroidStandaloneDriver.java:477)
        at io.selendroid.server.SelendroidStandaloneServer.stop(SelendroidStanda
loneServer.java:80)
        at io.selendroid.SelendroidLauncher$1.run(SelendroidLauncher.java:66)
Caused by: io.selendroid.exceptions.ShellCommandException:
        ... 9 more
io.selendroid.exceptions.ShellCommandException: An error occured while executing
 shell command: D:\SDK\platform-tools\adb.exe -s emulator-5554 shell pm clear co
m.peddle.seller
        at io.selendroid.io.ShellCommand.exec(ShellCommand.java:49)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevi
ce.java:176)
        at io.selendroid.android.impl.AbstractDevice.executeCommand(AbstractDevi
ce.java:171)
        at io.selendroid.android.impl.AbstractDevice.clearUserData(AbstractDevic
e.java:199)
        at io.selendroid.server.model.DeviceStore.release(DeviceStore.java:81)
        at io.selendroid.server.model.SelendroidStandaloneDriver.stopSession(Sel
endroidStandaloneDriver.java:464)
        at io.selendroid.server.model.SelendroidStandaloneDriver.quitSelendroid(
SelendroidStandaloneDriver.java:477)
        at io.selendroid.server.SelendroidStandaloneServer.stop(SelendroidStanda
loneServer.java:80)
        at io.selendroid.SelendroidLauncher$1.run(SelendroidLauncher.java:66)
Caused by: io.selendroid.exceptions.ShellCommandException:
        
If anyone help me to solve this.Please it's urgent

Thanks in advance....

**Comment by asm89** [comment]
This is a question rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
