### ISSUE TITLE
Hardware device commands are executed too early after plugging (error: device offline)

### ISSUE THREAD

**Issue by mannaz** [selendroid/selendroid#933]
Following the Getting Started instructions and just checking if the selenium setup works I ran the command `java -jar selendroid-standalone-0.15.0-with-dependencies.jar` without any devices or emulators attached. 

After the server has finished starting up I connected a device (Android 5.1.1) and the following error was shown:

    INFO: Executing shell command: /var/android-sdk/platform-tools/adb -s TA993010AF shell ls /system/framework/*map*
            Jul 01, 2015 12:02:24 PM io.selendroid.standalone.android.impl.AbstractDevice executeCommandQuietly
            WARNING: Could not execute command: /var/android-sdk/platform-tools/adb -s TA993010AF shell ls /system/framework/*map*
            io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /var/android-sdk/platform-tools/adb -s TA993010AF shell ls /system/framework/*map*
            at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
            at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:179)
            at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:174)
            at io.selendroid.standalone.android.impl.AbstractDevice.runAdbCommand(AbstractDevice.java:435)
            at io.selendroid.standalone.android.impl.DefaultHardwareDevice.<init>(DefaultHardwareDevice.java:40)
        at io.selendroid.standalone.android.impl.DefaultDeviceManager.deviceConnected(DefaultDeviceManager.java:153)
        at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:816)
        at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:400)
        at com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:320)
        at com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:193)
        at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:44)
        at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:84)
        Caused by: io.selendroid.standalone.exceptions.ShellCommandException: error: device offline

Manually executing the command yields positive results:

    mannaz@thinkpad:~/workspace$ /var/android-sdk/platform-tools/adb -s TA993010AF shell ls /system/framework/*map*
            /system/framework/com.google.android.maps.jar
            /system/framework/qmapbridge.jar

I assume the command is executed too early before the ADB connection could be completely set up.

Accessing the hub status page produces this info in the command line (and the `supportedDevices` list is empty):

    Jul 01, 2015 12:14:22 PM io.selendroid.standalone.server.model.SelendroidStandaloneDriver getSupportedDevices
    INFO: Error occurred when building supported device info: null

---

>    java version "1.8.0_45"
>    Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
>    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

>    Ubuntu 14.04 - 64 bit

>    Android Debug Bridge version 1.0.32

If you need additional details please ask away.

**Comment by asm89** [comment]
@mannaz Can you try with selendroid-standalone built from master?

**Comment by mannaz** [comment]
After compiling with Java 1.7 (1.8 didn't work) I got the same result but a different error message:

    $ java -jar selendroid-standalone-0.16.0-SNAPSHOT-with-dependencies.jar
    ....
    WARNING: Could not execute command: /var/android-sdk/platform-tools/adb -s TA993010AF shell ls /system/framework/*map*
            io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: /var/android-sdk/platform-tools/adb -s TA993010AF shell ls /system/framework/*map*
            at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:53)
            at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:171)
            at io.selendroid.standalone.android.impl.AbstractDevice.executeCommandQuietly(AbstractDevice.java:166)
            at io.selendroid.standalone.android.impl.AbstractDevice.runAdbCommand(AbstractDevice.java:427)
            at io.selendroid.standalone.android.impl.DefaultHardwareDevice.<init>(DefaultHardwareDevice.java:40)
        at io.selendroid.standalone.android.impl.DefaultDeviceManager.deviceConnected(DefaultDeviceManager.java:155)
        at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:816)
        at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:400)
        at com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:320)
        at com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:193)
        at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:44)
        at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:84)
        Caused by: io.selendroid.standalone.exceptions.ShellCommandException: error: device unauthorized. Please check the confirmation dialog on your device.

The device is authorized as I'm using it for development and debugging just fine.

**Comment by lukeis** [comment]
So, that's a WARNING message (since the first adb commands it tried were not successful). Were you able to eventually connect / use the device? (if so, then I consider this a non-issue. maybe just annoying to have a big warning with accompanied stack trace)

**Comment by mannaz** [comment]
As stated above with 0.15.0 I got the warning + device couldn't be used.
With 0.16.0-SNAPSHOT from Master I got a different warning but the device could be used.

**Comment by lukeis** [comment]
ok, then I'll consider this fixed (there was some recent work related to this).
