### ISSUE TITLE
Send key is not working in selendroid version (0.16.0)

### ISSUE THREAD

**Issue by prasad1480** [selendroid/selendroid#952]
It is failing below code, 

commonUtil.enterText(propUtil.getElementProperty("first_name_id"), "id", CsvHelper.hm.get("First_name"));

or

driver.findElement(By.id("first_name_id")).sendKeys("First_name");

POM version:
<dependency>
			<groupId>io.selendroid</groupId>
			<artifactId>selendroid-standalone</artifactId>
			<version>0.16.0</version>
		</dependency>
		<dependency>
			<groupId>io.selendroid</groupId>
			<artifactId>selendroid-client</artifactId>
			<version>0.16.0</version>
		</dependency>

		<dependency>
			<groupId>io.selendroid</groupId>
			<artifactId>selendroid-common</artifactId>
			<version>0.16.0</version>
		</dependency>

org.openqa.selenium.WebDriverException: CATCH_ALL: java.lang.NumberFormatException: Invalid int: "51.375"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at io.selendroid.server.model.AndroidWebElement.getCenterCoordinates(AndroidWebElement.java:233)
	at io.selendroid.server.model.AndroidWebElement.click(AndroidWebElement.java:249)
	at io.selendroid.server.model.AndroidWebElement.sendKeys(AndroidWebElement.java:121)
	at io.selendroid.server.model.AndroidWebElement.enterText(AndroidWebElement.java:113)
	at io.selendroid.server.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:44)
	at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:87)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)
	at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:818)

**Comment by prasad1480** [comment]
Please help me on this

**Comment by prasad1480** [comment]
<dependency>
			<groupId>io.selendroid</groupId>
			<artifactId>selendroid-standalone</artifactId>
			<version>0.16.0</version>
		</dependency>
		<dependency>
			<groupId>io.selendroid</groupId>
			<artifactId>selendroid-client</artifactId>
			<version>0.16.0</version>
		</dependency>

**Comment by asm89** [comment]
Are you positive that you actually installed `0.16.0`? That version includes the following commit: https://github.com/selendroid/selendroid/commit/85c479cc034c1e6b025a823ce82e8f02f820533b. Your stack trace shows `Integer.parseInt()` being called from `AndroidWebElement` on line 233, but that line doesn't call that method anymore: https://github.com/selendroid/selendroid/blob/8c05757273fef03730087be5c915b4e74b04cd49/selendroid-server/src/main/java/io/selendroid/server/model/AndroidWebElement.java#L233.

Perhaps you still have the old selendroid version running on the device/emulator?

**Comment by prasad1480** [comment]
I have checked my app version & it is showing 0.16.0 but it is still failing.

if(Android.equals("Yes")){
				SelendroidLauncher selendroidServer = null;
		        SelendroidConfiguration config = new SelendroidConfiguration();
		        selendroidServer = new SelendroidLauncher(config);
		        selendroidServer.launchSelendroid();
		        SelendroidCapabilities sc = new SelendroidCapabilities();
		        sc.setBrowserName("android");
		        sc.setPlatform(Platform.ANDROID);
		        sc.setSerial("serial number");  //serial id of the device
		        try {
					driver = new SelendroidDriver(sc);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}

**Comment by asm89** [comment]
With the same error? In any case I'm really certain this doesn't have anything to do with selendroid itself, making the follow up a bunch of questions rather than an issue. Please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by prasad1480** [comment]
Yes it is showing same error.
