### ISSUE TITLE
Selendroid  Inspector doesnt load elements tree and also app get crashed while loading

### ISSUE THREAD

**Issue by Jacob15** [selendroid/selendroid#960]
The following are the steps i followed.
1. Started the selendroid standalone using java -jar selendroid standalone 0.16 -app Go2needs.apk
2. Then i started the c# client code to debug the app.
3. While debugging i inspected the app using http://localhost:4444/inspector.
4. Elements tree doesnt get loaded in the right side of the image.
5. Below is the output from selendroidstandalone.

INFO: I/O exception (java.net.SocketException) caught when processing request to
 {}->http://localhost:8080: Connection reset
Aug 12, 2015 7:07:24 PM org.apache.http.impl.client.DefaultHttpClient tryExecute

INFO: Retrying request to {}->http://localhost:8080
Aug 12, 2015 7:07:24 PM io.selendroid.standalone.server.handler.InspectorTreeHan
dler handleRequest
SEVERE: Cannot get element tree for inspector
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(Abstrac
tSessionInputBuffer.java:160)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffe
r.java:84)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractS
essionInputBuffer.java:273)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(Default
HttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(Default
HttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessagePa
rser.java:260)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHead
er(AbstractHttpClientConnection.java:283)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHead
er(DefaultClientConnection.java:251)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponse
Header(ManagedClientConnectionImpl.java:197)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRe
questExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecu
tor.java:123)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(Default
RequestDirector.java:685)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultReq
uestDirector.java:487)

**Comment by leo-13** [comment]
I'm getting the same error with version 0.15.0. Although it used to work before...

**Comment by metasonic** [comment]
I have the same error for one of our apps,  from what i saw in the issue list,  this problem appears if your app doesn't have a backgroud,  if i remember correctly.

**Comment by farhansumbul** [comment]
I am using version 0.17.0. Although the Test app selendroid-test-app-0.17.0.apk works very well and I am able to run the tests and also run the java code in debug mode to check the webElements. But my hybrid app always crashes when trying to do debug in selendroid Session. Please help. Tried all possible ways. Below is the error stack trace. 



D/AndroidRuntime( 8383): Shutting down VM
D/jdwp    ( 8383): Got wake-up signal, bailing out of select
D/AndroidRuntime( 8394):
D/AndroidRuntime( 8394): >>>>>> AndroidRuntime START com.android.internal.os.Run
timeInit <<<<<<
D/AndroidRuntime( 8394): CheckJNI is ON
E/memtrack( 8394): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 8394): failed to load memtrack module: -2
D/AndroidRuntime( 8394): Calling main entry com.android.commands.input.Input
I/Input   ( 8394): injectKeyEvent: KeyEvent { action=ACTION_DOWN, keyCode=KEYCOD
E_MENU, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=69652071, d
ownTime=69652071, deviceId=-1, source=0x101 }
I/Input   ( 8394): injectKeyEvent: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_
MENU, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=69652071, dow
nTime=69652071, deviceId=-1, source=0x101 }
D/AndroidRuntime( 8394): Shutting down VM
E/SoundPool(  355): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Eff
ect_Tick.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Eff
ect_Tick.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Eff
ect_Tick.ogg
D/jdwp    ( 8394): Got wake-up signal, bailing out of select
E/SoundPool(  355): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Eff
ect_Tick.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Eff
ect_Tick.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/KeypressStandard.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Key
pressStandard.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/KeypressSpacebar.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Key
pressSpacebar.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/KeypressDelete.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Key
pressDelete.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/KeypressReturn.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Key
pressReturn.ogg
E/SoundPool(  355): error loading /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService(  355): Soundpool could not load file: /system/media/audio/ui/Key
pressInvalid.ogg
W/AudioService(  355): onLoadSoundEffects(), Error -1 while loading samples
I/Choreographer(  639): Skipped 92 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 52 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 49 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 49 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 55 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 37 frames!  The application may be doing too muc
h work on its main thread.
D/AndroidRuntime( 8408):
D/AndroidRuntime( 8408): >>>>>> AndroidRuntime START com.android.internal.os.Run
timeInit <<<<<<
D/AndroidRuntime( 8408): CheckJNI is ON
E/memtrack( 8408): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 8408): failed to load memtrack module: -2
D/AndroidRuntime( 8408): Calling main entry com.android.commands.input.Input
I/Input   ( 8408): injectKeyEvent: KeyEvent { action=ACTION_DOWN, keyCode=KEYCOD
E_BACK, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=69655191, d
ownTime=69655191, deviceId=-1, source=0x101 }
I/Input   ( 8408): injectKeyEvent: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_
BACK, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=69655191, dow
nTime=69655191, deviceId=-1, source=0x101 }
D/AndroidRuntime( 8408): Shutting down VM
D/jdwp    ( 8408): Got wake-up signal, bailing out of select
I/Choreographer(  355): Skipped 31 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 61 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 43 frames!  The application may be doing too muc
h work on its main thread.
W/InputMethodManagerService(  355): Window already focused, ignoring focus gain
of: com.android.internal.view.IInputMethodClient$Stub$Proxy@b31621f0 attribute=n
ull, token = android.os.BinderProxy@b3382648
D/AndroidRuntime( 8419):
D/AndroidRuntime( 8419): >>>>>> AndroidRuntime START com.android.internal.os.Run
timeInit <<<<<<
D/AndroidRuntime( 8419): CheckJNI is ON
E/memtrack( 8419): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 8419): failed to load memtrack module: -2
D/AndroidRuntime( 8419): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 8419): Shutting down VM
D/jdwp    ( 8419): Got wake-up signal, bailing out of select
D/AndroidRuntime( 8430):
D/AndroidRuntime( 8430): >>>>>> AndroidRuntime START com.android.internal.os.Run
timeInit <<<<<<
D/AndroidRuntime( 8430): CheckJNI is ON
E/memtrack( 8430): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 8430): failed to load memtrack module: -2
D/AndroidRuntime( 8430): Calling main entry com.android.commands.pm.Pm
D/AndroidRuntime( 8430): Shutting down VM
D/AndroidRuntime( 8443):
D/AndroidRuntime( 8443): >>>>>> AndroidRuntime START com.android.internal.os.Run
timeInit <<<<<<
D/AndroidRuntime( 8443): CheckJNI is ON
E/memtrack( 8443): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 8443): failed to load memtrack module: -2
D/AndroidRuntime( 8443): Calling main entry com.android.commands.am.Am
I/ActivityManager(  355): Force stopping com.XXXX.XXXX appid=10058 user=0: start
 instr
D/AndroidRuntime( 8443): Shutting down VM
I/ActivityManager(  355): Start proc XXXXXX for added application com.XXXX
O.XXXX: pid=8454 uid=10058 gids={50058, 3003, 1028, 1015}
D/jdwp    ( 8443): Got wake-up signal, bailing out of select
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.
intent.category.LAUNCHER] flg=0x34020000 cmp=com.XXXX.XXXX/.MainActivity} from p
id 8454
D/gralloc (   55): Registering a buffer in the process that created it. This may
 cause memory ordering problems.
E/libEGL  (   55): called unimplemented OpenGL ES API
E/libEGL  (   55): called unimplemented OpenGL ES API
E/libEGL  (   55): called unimplemented OpenGL ES API
E/libEGL  (   55): called unimplemented OpenGL ES API
E/libEGL  (   55): called unimplemented OpenGL ES API
E/libEGL  (   55): called unimplemented OpenGL ES API
I/Choreographer(  355): Skipped 315 frames!  The application may be doing too mu
ch work on its main thread.
W/WindowManager(  355): Screenshot failure taking screenshot for (164x246) to la
yer 21005
I/Choreographer(  355): Skipped 67 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 209 frames!  The application may be doing too mu
ch work on its main thread.
I/Choreographer(  355): Skipped 318 frames!  The application may be doing too mu
ch work on its main thread.
I/Choreographer(  355): Skipped 53 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 171 frames!  The application may be doing too mu
ch work on its main thread.
I/Choreographer(  355): Skipped 36 frames!  The application may be doing too muc
h work on its main thread.
V/WebViewChromiumFactoryProvider( 8454): Binding Chromium to main looper Looper
(main, tid 1) {b2cb2040}
I/LibraryLoader( 8454): Expected native library version number "",actual native
library version number ""
I/chromium( 8454): [INFO:library_loader_hooks.cc(116)] Chromium logging enabled:
 level = 0, default verbosity = 0
I/Choreographer(  639): Skipped 243 frames!  The application may be doing too mu
ch work on its main thread.
I/BrowserStartupController( 8454): Initializing chromium process, renderers=0
E/AudioManagerAndroid( 8454): BLUETOOTH permission is missing!
E/chromium( 8454): [ERROR:gl_surface_egl.cc(169)] No suitable EGL configs found.

E/chromium( 8454): [ERROR:gl_surface_egl.cc(702)] GLSurfaceEGL::InitializeOneOff
 failed.
E/chromium( 8454): [ERROR:gl_surface_egl.cc(169)] No suitable EGL configs found.

E/chromium( 8454): [ERROR:gl_surface_egl.cc(702)] GLSurfaceEGL::InitializeOneOff
 failed.
E/chromium( 8454): [ERROR:gpu_info_collector.cc(86)] gfx::GLSurface::InitializeO
neOff() failed
E/chromium( 8454): [ERROR:gl_surface_egl.cc(169)] No suitable EGL configs found.

E/chromium( 8454): [ERROR:gl_surface_egl.cc(702)] GLSurfaceEGL::InitializeOneOff
 failed.
W/chromium( 8454): [WARNING:mailbox_synchronizer.cc(36)] MailboxSync not support
ed due to missing EGL image/fence support
I/dalvikvm-heap( 8454): Grow heap (frag case) to 3.210MB for 281896-byte allocat
ion
W/chromium( 8454): [WARNING:proxy_service.cc(890)] PAC support disabled because
there is no system implementation
D/SystemWebViewEngine( 8454): CordovaWebView is running on device made by: unkno
wn
I/dalvikvm-heap( 8454): Grow heap (frag case) to 4.783MB for 1566056-byte alloca
tion
I/Choreographer( 8454): Skipped 214 frames!  The application may be doing too mu
ch work on its main thread.
I/Choreographer( 8454): Skipped 86 frames!  The application may be doing too muc
h work on its main thread.
D/gralloc_goldfish( 8454): Emulator without GPU emulation detected.
I/ActivityManager(  355): Displayed com.XXXX.XXXX/.MainActivity: +6s832ms
I/Choreographer(  355): Skipped 41 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer(  355): Skipped 43 frames!  The application may be doing too muc
h work on its main thread.
I/Choreographer( 8454): Skipped 96 frames!  The application may be doing too muc
h work on its main thread.
D/AndroidRuntime( 8454): Shutting down VM
E/SELENDROID( 8454): io.selendroid.server.UncaughtExceptionHandling$ExceptionDum
per#uncaughtException:54 - Could not write crash log to: /storage/sdcard/appcras
h.log
E/SELENDROID( 8454): java.io.FileNotFoundException: /storage/sdcard/appcrash.log
: open failed: EACCES (Permission denied)
E/SELENDROID( 8454):    at libcore.io.IoBridge.open(IoBridge.java:409)
E/SELENDROID( 8454):    at java.io.FileOutputStream.<init>(FileOutputStream.java
:88)
E/SELENDROID( 8454):    at java.io.FileOutputStream.<init>(FileOutputStream.java
:73)
E/SELENDROID( 8454):    at java.io.PrintWriter.<init>(PrintWriter.java:127)
E/SELENDROID( 8454):    at io.selendroid.server.UncaughtExceptionHandling$Except
ionDumper.uncaughtException(UncaughtExceptionHandling.java:48)
E/SELENDROID( 8454):    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.j
ava:693)
E/SELENDROID( 8454):    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.j
ava:690)
E/SELENDROID( 8454):    at dalvik.system.NativeStart.main(Native Method)
E/SELENDROID( 8454): Caused by: libcore.io.ErrnoException: open failed: EACCES (
Permission denied)
E/SELENDROID( 8454):    at libcore.io.Posix.open(Native Method)
E/SELENDROID( 8454):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
E/SELENDROID( 8454):    at libcore.io.IoBridge.open(IoBridge.java:393)
E/SELENDROID( 8454):    ... 7 more
I/AndroidRuntime( 8454): VM exiting with result code -1, cleanup skipped.
I/ActivityManager(  355): Process com.XXXX.XXXX (pid 8454) has died.
I/WindowState(  355): WIN DEATH: Window{b2e0e980 u0 com.XXXX.XXXX/com.XXXX.XXXX.
MainActivity}
D/Zygote  (   56): Process 8454 exited cleanly (255)
W/ActivityManager(  355): Force removing ActivityRecord{b2dd4850 u0 com.XXXX.Keu
r/.MainActivity t29}: app died, no saved state
W/ActivityManager(  355): Crash of app com.XXXX.XXXX running instrumentation Com
ponentInfo{io.selendroid.com.XXXX.XXXX/io.selendroid.server.ServerInstrumentatio
n}
I/ActivityManager(  355): Force stopping com.XXXX.XXXX appid=10058 user=0: finis
hed inst
I/Choreographer(  639): Skipped 88 frames!  The application may be doing too muc
h work on its main thread.
Feb 16, 2016 11:04:27 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: D:\android-sdks\platform-tools\adb.exe -s emulato
r-5554 shell ps
Feb 16, 2016 11:04:27 AM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
USER     PID   PPID  VSIZE  RSS     WCHAN    PC         NAME
root      1     0     644    500   c00bd520 00019fac S /init
root      2     0     0      0     c00335a0 00000000 S kthreadd
root      3     2     0      0     c001e39c 00000000 S ksoftirqd/0
root      5     2     0      0     c002f170 00000000 S kworker/u:0
root      6     2     0      0     c002e744 00000000 S khelper
root      7     2     0      0     c0093bb4 00000000 S sync_supers
root      8     2     0      0     c0094470 00000000 S bdi-default
root      9     2     0      0     c002e744 00000000 S kblockd
root      10    2     0      0     c002e744 00000000 S rpciod
root      12    2     0      0     c008d790 00000000 S kswapd0
root      13    2     0      0     c00e34bc 00000000 S fsnotify_mark
root      14    2     0      0     c002e744 00000000 S crypto
root      25    2     0      0     c0216434 00000000 S mtdblock0
root      26    2     0      0     c0216434 00000000 S mtdblock1
root      27    2     0      0     c0216434 00000000 S mtdblock2
root      28    2     0      0     c002e744 00000000 S binder
root      29    2     0      0     c002e744 00000000 S deferwq
root      30    2     0      0     c002f170 00000000 S kworker/u:1
root      31    1     580    304   c00bd520 00019fac S /sbin/ueventd
root      33    2     0      0     c0142db4 00000000 S jbd2/mtdblock0-
root      34    2     0      0     c002e744 00000000 S ext4-dio-unwrit
root      40    2     0      0     c0142db4 00000000 S jbd2/mtdblock1-
root      41    2     0      0     c002e744 00000000 S ext4-dio-unwrit
root      44    2     0      0     c00cfa90 00000000 S flush-31:2
root      46    2     0      0     c0142db4 00000000 S jbd2/mtdblock2-
root      47    2     0      0     c002e744 00000000 S ext4-dio-unwrit
root      48    1     1428   144   c00e68a4 00011260 S /sbin/healthd
system    49    1     1000   340   c0253e80 b6eb241c S /system/bin/servicemanage
r
root      50    1     4660   1132  ffffffff b6f2dd14 S /system/bin/vold
root      52    1     9764   1264  ffffffff b6f04d14 S /system/bin/netd
root      53    1     1028   428   c0262d18 b6f47110 S /system/bin/debuggerd
radio     54    1     5504   860   ffffffff b6ec6d14 S /system/bin/rild
system    55    1     21280  5860  ffffffff b6ef35cc S /system/bin/surfaceflinge
r
root      56    1     204284 39932 ffffffff b6ead568 S zygote
drm       57    1     6936   2548  ffffffff b6ef441c S /system/bin/drmserver
media     58    1     21588  5760  ffffffff b6efc41c S /system/bin/mediaserver
install   59    1     1000   508   c02f5e30 b6f98158 S /system/bin/installd
keystore  60    1     3344   1224  c0253e80 b6ee241c S /system/bin/keystore
root      61    1     920    368   c00e68a4 b6f6a5cc S /system/bin/qemud
shell     64    1     924    468   c01eb6dc b6ed8158 S /system/bin/sh
root      65    1     5720   328   ffffffff 0001905c S /sbin/adbd
system    355   56    269916 42568 ffffffff b6eae5cc S system_server
u0_a7     407   56    228980 36160 ffffffff b6eae5cc S com.android.systemui
u0_a2     511   56    219452 23092 ffffffff b6eae5cc S android.process.acore
u0_a29    535   56    225168 25356 ffffffff b6eae5cc S com.android.inputmethod.l
atin
radio     558   56    238948 25996 ffffffff b6eae5cc S com.android.phone
u0_a8     639   56    228128 35192 ffffffff b6eae5cc S com.android.launcher
u0_a20    1008  56    216956 20768 ffffffff b6eae5cc S com.android.deskclock
u0_a3     1127  56    215336 18116 ffffffff b6eae5cc S com.android.defcontainer
root      6883  2     0      0     c002f170 00000000 S kworker/0:1
root      8138  2     0      0     c00cfa90 00000000 S flush-31:1
u0_a36    8143  56    214420 22608 ffffffff b6eae5cc S com.android.packageinstal
ler
u0_a6     8161  56    213180 17228 ffffffff b6eae5cc S com.android.externalstora
ge
system    8176  56    213344 18464 ffffffff b6eae5cc S com.android.keychain
u0_a23    8190  56    216008 20008 ffffffff b6eae5cc S com.android.documentsui
u0_a5     8204  56    215072 20012 ffffffff b6eae5cc S android.process.media
root      8221  2     0      0     c002f170 00000000 S kworker/0:0
u0_a37    8296  56    213168 16904 ffffffff b6eae5cc S com.svox.pico
root      8467  65    1676   1100  c00bd520 b6ee2568 S logcat
root      8532  65    1236   464   00000000 b6f3c158 R ps
<--

**Comment by lukeis** [comment]
@farhansumbul your error appears to be:

> E/SELENDROID( 8454): java.io.FileNotFoundException: /storage/sdcard/appcrash.log
: open failed: EACCES (Permission denied)

which means that either your device has run out of disk space? or you have some strange permissions set on the sdcard where selendroid can't write to it.

**Comment by farhansumbul** [comment]
@lukeis I am trying to run my test on emulator. Moreover my Hybrid app is built on Cordova 5.4.1. Does Selendroid 0.17.0 supports latest versions of Cordova? Because I see this fix was done for Cordova-Android 4.0 https://github.com/selendroid/selendroid/pull/859
