### ISSUE TITLE
Webview throwing an error upon clicking a Webelement 

### ISSUE THREAD

**Issue by sagarraj92** [selendroid/selendroid#970]
Invalid int: "{"message":"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"default-src 'self'\".\n"}" 
at java.lang.Integer.invalidInt(Integer.java:138) 
at java.lang.Integer.parse(Integer.java:410) 
at java.lang.Integer.parseInt(Integer.java:367) 
at java.lang.Integer.parseInt(Integer.java:334) 
at io.selendroid.server.model.AndroidWebElement.getCenterCoordinates(AndroidWebElement.java:233) 
at io.selendroid.server.model.AndroidWebElement.click(AndroidWebElement.java:249) 
at io.selendroid.server.handler.ClickElement.safeHandle(ClickElement.java:36) 
at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:87) 
at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264) 
at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67) 
at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) 
at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) 
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) 
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148) 
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) 
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) 
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) 
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) 
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) 
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) 
at java.lang.Thread.run(Thread.java:818)

**Comment by sagarraj92** [comment]
The WebElement it is trying to click on is,

<a class="storeapp-details-link list" href="#">
<img class="storeapp-icon list" data-iconid="7cf6bb7c-396b-4911-85f2-522ab58cc609%7E2629651449" alt="WorxMail" src="https://np.xen.net/cvpn/https/neptune.xen.net:8443/Citrix/Store/resources/v2/7cf6bb7c-396b-4911-85f2-522ab58cc609%7E2629651449/image"/>

**Comment by RogersGit** [comment]
I met same problem ， have u resolve it

**Comment by lukeis** [comment]
if possible, could someone provide a page to reproduce this on? Is this a hybrid app? Does it reproduce when using selendroid's "browser" (selendroid's 'android-driver' webview app).

**Comment by darkshadowray** [comment]
I had almost the same problem... 
we use Moto G with Android 5.1 (on 4.4.4 it works fine)
we use selendroid's 'android-driver' webview app
the html:
```
<html xmlns="http://www.w3.org/1999/xhtml"><head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
		<title>TEST</title>
	</head>
	<body>
		<div id="content">	
			<div id="button" class="line">
				<div style="height:100%">
					<form action="" name="link_form_1" method="post" id="link_form_1">
						<input type="hidden" name="last_page_segment" value="true" />
						<input type="hidden" name="action_submit" value="true" />
						<input id="buy" type="submit" name="test" value="TEST" />
					</form>
				</div>
			</div>
		</div>
       </body>
</html>
```


```
Caused by: org.openqa.selenium.WebDriverException: CATCH_ALL: java.lang.NumberFormatException: Invalid int: "56.96875"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at io.selendroid.server.model.AndroidWebElement.getCenterCoordinates(AndroidWebElement.java:233)
	at io.selendroid.server.model.AndroidWebElement.click(AndroidWebElement.java:249)
	at io.selendroid.server.handler.ClickElement.safeHandle(ClickElement.java:36)
	at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:87)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)
	at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:818)
```
