### ISSUE TITLE
Emulator die after driver.quit()

### ISSUE THREAD

**Issue by victorpotapov1991** [selendroid/selendroid#973]
Emulator die after driver.quit()
I hav black sceened emulator after driver.quit(), so Selendroid couldn't start new session.
I use <dependency>
          <groupId>io.selendroid</groupId>
          <artifactId>selendroid-standalone</artifactId>
          <version>0.16.0</version>
      </dependency>
      <dependency>
          <groupId>io.selendroid</groupId>
          <artifactId>selendroid-client</artifactId>
          <version>0.16.0</version>
      </dependency>

**Comment by smiklosovic** [comment]
I am experiencing the same issue on android 6.0

Emulator is restarted after that.

```
I am experiencing the same issue 

10-06 19:47:44.569  1318  1341 I ActivityManager: Force stopping io.selendroid.testapp appid=10053 user=-1: uninstall pkg
10-06 19:47:44.569  1318  1341 I ActivityManager: Killing 2366:io.selendroid.testapp/u0a53 (adj 0): stop io.selendroid.testapp
10-06 19:47:44.595  1318  1361 I art     : Starting a blocking GC Explicit
10-06 19:47:44.607  1318  1361 I art     : Explicit concurrent mark sweep GC freed 11495(931KB) AllocSpace objects, 8(192KB) LOS objects, 33% free, 6MB/10MB, paused 157us total 11.122ms
10-06 19:47:44.609  1318  1341 W ActivityManager: Crash of app io.selendroid.testapp running instrumentation ComponentInfo{io.selendroid.server_1/io.selendroid.server.ServerInstrumentation}
10-06 19:47:44.609  1318  1341 I ActivityManager: Force stopping io.selendroid.testapp appid=-1 user=0: finished inst
--------- beginning of crash
10-06 19:47:44.609  1318  1341 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: ActivityManager
10-06 19:47:44.609  1318  1341 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IUiAutomationConnection.shutdown()' on a null object reference
10-06 19:47:44.609  1318  1341 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2026)
10-06 19:47:44.609  1318  1341 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-06 19:47:44.609  1318  1341 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-06 19:47:44.609  1318  1341 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-06 19:47:44.609  1318  1341 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
10-06 19:47:44.610  1318  1488 W ActivityManager: Spurious death for ProcessRecord{edab98d 0:io.selendroid.testapp/u0a53}, curProc for 2366: null
10-06 19:47:44.611  1504  1504 W RecentsTaskLoader: Missing ActivityInfo for ComponentInfo{io.selendroid.testapp/io.selendroid.testapp.HomeScreenActivity} u=0
10-06 19:47:44.619  1318  1341 I Process : Sending signal. PID: 1318 SIG: 9
10-06 19:47:44.651   992   992 I ServiceManager: service 'telecom' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'launcherapps' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'media_projection' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'imms' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'wifi' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'wifiscanner' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'rttmanager' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'connectivity' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'servicediscovery' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'updatelock' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'notification' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'devicestoragemonitor' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'location' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'country_detector' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'search' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'netpolicy' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'wifip2p' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'dropbox' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'wallpaper' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'audio' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'network_management' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'textservices' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'network_score' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'netstats' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'DockObserver' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'midi' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'serial' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'jobscheduler' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'backup' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'appwidget' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'voiceinteraction' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'diskstats' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'samplingprofiler' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'commontime_management' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'dreams' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'assetatlas' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'graphicsstats' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'print' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'restrictions' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'media_session' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'media_router' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'trust' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'fingerprint' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'procstats' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'meminfo' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'gfxinfo' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'dbinfo' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'cpuinfo' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'permission' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'processinfo' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'sensorservice' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'battery' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'usagestats' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'webviewupdate' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'scheduling_policy' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'telephony.registry' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'media.camera.proxy' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'account' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'content' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'vibrator' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'consumer_ir' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'alarm' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'window' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'input' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'package' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'user' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'activity' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'input_method' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'accessibility' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'mount' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'uimode' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'lock_settings' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'deviceidle' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'device_policy' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'statusbar' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'clipboard' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'batterystats' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'appops' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'power' died
10-06 19:47:44.651   992   992 I ServiceManager: service 'display' died
10-06 19:47:44.651  1005  1005 W AudioFlinger: power manager service died !!!
10-06 19:47:44.651  1012  1012 D fingerprintd: binder died
10-06 19:47:44.651  1012  1012 V fingerprintd: nativeCloseHal()
10-06 19:47:44.653  1772  1928 E WifiManager: Channel connection lost
10-06 19:47:44.653  1504  1656 E WifiManager: Channel connection lost
10-06 19:47:44.654   993   993 D SurfaceFlinger: Set power mode=2, type=0 flinger=0x7f867cfc3c00
10-06 19:47:44.654   993   993 D SurfaceFlinger: Screen type=0 is already mode=2
10-06 19:47:44.655  1006  1006 E installd: eof
10-06 19:47:44.655  1006  1006 E installd: failed to read command
10-06 19:47:44.655  1006  1006 I installd: closing connection
10-06 19:47:44.655   991   991 I lowmemorykiller: ActivityManager disconnected
10-06 19:47:44.655   991   991 I lowmemorykiller: Closing Activity Manager data connection
10-06 19:47:44.659  2415  2447 D Documents: Update found 5 roots in 259ms
10-06 19:47:44.697   993  1073 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
```
