### ISSUE TITLE
Changing to a webview on an ionic app. 0.17.0

### ISSUE THREAD

**Issue by madiska** [selendroid/selendroid#993]
**Issue**
With Selendroid 0.17.0 I get an exception when trying to change to a webview. An ionic hybrid app. 

org.openqa.selenium.WebDriverException: CATCH_ALL: java.lang.VerifyError: io/selendroid/server/model/SelendroidWebDriver
	at io.selendroid.server.model.DefaultSelendroidDriver.initSelendroidWebDriver(DefaultSelendroidDriver.java:340)
	at io.selendroid.server.model.DefaultSelendroidDriver.switchContext(DefaultSelendroidDriver.java:334)
	at io.selendroid.server.handler.SwitchContext.safeHandle(SwitchContext.java:38)
	at io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:86)
	at io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)
	at io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)
	at io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:856)

**Comment by lukeis** [comment]
can you make sure you uninstall any previous selendroid apk's on your device and try rerunning?

This may be a conflict with another apk already installed.

try:  adb uninstall io.selendroid.<your app package>
or manually find the list of applications in the device and uninstall anything "selendroid"

**Comment by madiska** [comment]
I deleted all the apps in my device. The issue is still there. I have no problems staying with 0.16.0 with this project, but yeah. If you need more info regarding the issue let me know. Not sure how to help you with that though.

**Comment by lukeis** [comment]
Is this a real device or emulator? Can you list the exact specs of it?

**Comment by madiska** [comment]
I tested with 2 devices and several emulators. Can try with more devices if needed.
Huawei phone. Forgot the model. It is currently at work. Android 4.4
Philips tablet. PI2010 Android 4.2
Mostly Genymotion emulators

**Comment by madiska** [comment]
Ok I was able to run the app with Nexus 7 and Samsung S4. (Android 5.1.1 and 5.0.1), but my hybrid app crashed after trying to click the login button. oh well. Gonna stick to 0.16.0 with this app.

**Comment by Urbiwanus** [comment]
Have the same issue 
0.16.0 works fine
