### ISSUE TITLE
Phone using Android M restarting repetitively while running tests.

### ISSUE THREAD

**Issue by harshagarwal8** [selendroid/selendroid#996]
I am trying to run tests on Android M developer preview 3 and the device is getting restarted again and again.

Here are the logs:

Oct 26, 2015 8:15:52 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /users/harshag/Library/Android/sdk/platform-tools/adb -s ZX1G422WRH shell dumpsys power
Oct 26, 2015 8:15:52 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Exception occurred while dumping:
java.lang.NullPointerException: Attempt to invoke interface method 'int android.app.IActivityManager.checkPermission(java.lang.String, int, int)' on a null object reference
	at android.app.ContextImpl.checkPermission(ContextImpl.java:1380)
	at android.app.ContextImpl.checkCallingOrSelfPermission(ContextImpl.java:1421)
	at com.android.server.power.PowerManagerService$BinderService.dump(PowerManagerService.java:3436)
	at android.os.Binder.dump(Binder.java:326)
	at android.os.Binder.onTransact(Binder.java:292)
	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:318)
	at android.os.Binder.execTransact(Binder.java:453)
<--
Oct 26, 2015 8:15:52 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Executing shell command: /users/harshag/Library/Android/sdk/platform-tools/adb -s ZX1G422WRH shell pm list packages com.zenprise
Oct 26, 2015 8:15:53 PM io.selendroid.standalone.io.ShellCommand exec
INFO: Shell command output
-->
Error: Could not access the Package Manager.  Is the system running?
<--

**Comment by harshagarwal8** [comment]
Issue fixed on Marshmallow public release.
